In [1]:
import pandas as pd

# --- Load files ---
f1 = "Data/LLM_output/ai_development_deduplicated_custom_step1_extracted.csv"
f2 = "Data/ai_development_training_companies_200_jobs.csv"

# Read as string to avoid int/float mismatches on `uid`
df1 = pd.read_csv(f1, dtype={"uid": str})
df2 = pd.read_csv(f2, dtype={"uid": str})

# Normalize uid (trim whitespace)
df1["uid"] = df1["uid"].str.strip()
df2["uid"] = df2["uid"].str.strip()

# --- Merge on uid with indicator ---
merged = df1.merge(
    df2,
    how="outer",
    on="uid",
    indicator=True,
    suffixes=("_step1", "_train"),
)

# Unmatched sets
left_only = merged[merged["_merge"] == "left_only"]   # in step1 only
right_only = merged[merged["_merge"] == "right_only"] # in train only

# --- Show quick summary ---
print(f"Rows in step1: {len(df1)}")
print(f"Rows in train: {len(df2)}")
print(f"Unmatched (step1 only): {len(left_only)}")
print(f"Unmatched (train only): {len(right_only)}")

# --- Display unmatched rows (first 20 each) ---
step1_cols = ["uid"] + [c for c in merged.columns if c.endswith("_step1")]
train_cols = ["uid"] + [c for c in merged.columns if c.endswith("_train")]

print("\n=== Present in step1 only ===")
print(left_only[step1_cols].head(20).to_string(index=False))

print("\n=== Present in train only ===")
print(right_only[train_cols].head(20).to_string(index=False))

# (Optional) Save unmatched to CSVs:
# left_only.to_csv("unmatched_step1_only.csv", index=False)
# right_only.to_csv("unmatched_train_only.csv", index=False)

Rows in step1: 200
Rows in train: 200
Unmatched (step1 only): 80
Unmatched (train only): 80

=== Present in step1 only ===
                                 uid                                                 title_step1                                                 company_name_step1 company_size_step1              location_raw_step1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       content_clean_step1                tst_created_step1                                                                                                                                               url_step1                                           matched_keywords_step1  company_id_step1 company_is_recruiter_step1                tst_deleted_step1     x28_industries_step1    x28_occupations_step1                                                                                                cantons_step1                duplicate_group_step1
03189420-38c6-45f3-991c-1e0d1266cb11                    Senior Consultant Prozessdigitalisierung                                   Innovation Process Technology AG   Kleinunternehmen                     CH-6300 Zug                                                                                                                                 Senior Consultant Prozessdigitalisierung\n\nWir sind eine Schweizer IT-Consulting Firma. Wir bauen innovative Lösungen beim Kunden vor Ort. Uns gibt es schon seit über 20 Jahren, aber wir leben immer noch eine Start-up Mentalität – 160 Leute, Flat Hierarchy, No Politics, Lots of Fun! Bei uns gilt: People First! Jeder kann sich bei uns einbringen und zum Experten werden. Wissen wird geteilt und gegenseitige Unterstützung ist zentral. We’re ONE Team!\nBewirb dich jetzt!\nDeine Challenges\n\nDu berätst unsere Kunden bezüglich Prozessdigitalisierung, die für eine positive Customer Experience sorgt\n\nDu übernimmst die technische Verantwortung in einem mixed Projektteam (Kunde & ipt) für die Konzeption und Umsetzung mittels BPM-Technologien (Camunda, Appway, etc.)\n\nModellierung, Implementierung, Optimierung und Integration von kundenspezifischen Prozessen wie Client Onboarding, Marketing Automation mit Next Best Action, Schadensabrechnung bei Versicherungen, etc.\n\nEntwicklung von Microservices (z.B. mit Spring Boot und Kubernetes) und innovativen Front-Ends (Angular, React oder Vue)\n\nAufbau einer automatisierten CI/CD Pipeline (z.B. mit Jenkins oder in der Cloud mit entsprechenden Cloud Services wie Azure DevOps, etc.)\n\nDas bringst du mit\n\n5+ Jahre Projekterfahrung im Software Engineering\n\nErfahrung mit Prozessdigitalisierung, Front-End Entwicklung und DevOps Automatisierung\n\nBreites Technologieverständnis- und interesse, analytisches Vorgehen\n\nAbgeschlossenes Studium (Informatik, Wirtschaftsinformatik, Mathematik, Elektrotechnik, Physik)\n\nProfessionelles Auftreten, Teamplayer und fliessende Deutsch- und Englischkenntnisse\n\nDas sind unsere Benefits für dich\n\nAustausch unter Experten: Monatliche Mitarbeiterevents, TechBiers und Scrum’n’Wines garantieren Know-How Austausch und frische Ideen\n\nMit Komfort unterwegs: Der Umwelt zuliebe sind wir mit dem ÖV unterwegs. Und den Mitarbeitenden zuliebe in der 1. Klasse\n\nGarantierte Abwechslung: Verschiedene Kunden, Themen, Methoden und Technologien – als Consultant wird es nicht langweilig\n\nHardfacts\n\nDein Arbeitsort ist vor Ort beim Kunden in der Deutschschweiz (ZH, LU, BS, BE)\n\n80-100% Pensum\n\nDieses Stelleninserat umschreibt ein Szenario, das dich in einem Projekt erwarten könnte. Wir suchen daher Talente, die für verschiedene Themen und Technologien offen sind.\n\nP.S. Wir schauen optimistisch in die Zukunft und suchen auch in Zeiten von COVID-19 passende Bewerbende, die unser Team verstärken und uns weiterbringen.\n\nHast du Fragen?\n\nMichaela Kuhn\nHR + Mitglied der Geschäftsleitung\n\nWir freuen uns auf deine Bewerbung!\nAnrede Herr Frau Vorname Name E-Mail Telefon Dein Xing-Profil Dein Linkedin-Profil Bewerbungsschreiben\n\n.pdf, .doc, .docx, .zip (max. 20MB)\n\nLebenslauf\n\n.pdf, .doc, .docx, .zip (max. 20MB)\n\nWeitere Dokumente\n\n.pdf, .doc, .docx, .zip (max. 20MB)\n\nWeitere Links Bemerkung Wie bist du auf ipt aufmerksam geworden? Ich habe die Datenschutzbestimmungen gelesen und bin damit einverstanden. Comments 2020-08-26 13:13:03.809000+02:00                                                                               https://ipt.ch/de/karriere/jobs/senior-consultant-prozessdigitalisierung/                                                 next best action        40003413.0                      False 2021-09-30 09:55:25.063000+02:00             ['65000019']             ['11000066']                                                                                                       ['ZG']                                  NaN
05a53ea8-99a0-4e78-b98b-557b5613a30e                       Stagiaire Data Scientist (H/F) 6 mois Manufacture Jaeger-LeCoultre, Branch of Richemont International SA   Kleinunternehmen              Le Sentier, VD, CH                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Postuler »\nCode de référence: \n 93037\nStagiaire Data Scientist (H/F) 6 mois\nLe Sentier, VD, CH\nTrainee/Intern\n\nDepuis sa création, Jaeger-LeCoultre a fait de la précision un art à part entière, en trouvant le parfait équilibre entre savoir-faire pointu et sens artistique, sophistication et finesse esthétique. Fidèle à l'esprit d'invention initié en 1833 par son fondateur Antoine LeCoultre, les artisans de la Manufacture créent des collections à la pointe de la Haute Horlogerie: Reverso, Master, Jaeger-LeCoultre Polaris, RendezVous et Atmos - ce riche héritage construit par la Grande Maison au fil des siècles est une source d'inspiration constante qui ne cesse de repousser les limites à travers des garde-temps sans précédent.\nAu sein de notre département Qualité, nous sommes à la recherche d'un stagiaire pour une durée d'environ 6 mois dès septembre 2023 afin de participer à divers projets. Votre rôle principal consistera à travailler sur des sujets liés à l'analyse de données et à la modélisation, notamment :\n\nCréation de visualisations de données permettant aux différents secteurs de mettre en place des plans d'amélioration ;\nRéalisation d'analyses qualité variées, telles que la corrélation, la fiabilité, la comparaison, entre les ateliers de contrôle et les retours clients.\n\nLA CLÉ DE VOTRE SUCCÈS ? VOS COMPÉTENCES !\n\nVous êtes actuellement inscrit à un Baccalauréat ou à un Master avec un majeur ou un mineur en Data Science;\nVous êtes spécialiste en analyse et/ou visualisation de données;\nVous avez une bonne maîtrise des techniques d'interrogation et de manipulation des données statistiques, ainsi que des langages de programmation (python);\nVous maitrisez les outils de dashboarding tels que Power BI, ou autres;\nVous avez des compétences analytiques solides;\nVous avez des connaissance des outils de bureautique tels qu'Excel, PowerPoint, etc.\n\nPOURQUOI NOUS REJOINDRE ?\n\nVous êtes notre meilleur atout. En rejoignant Jaeger-LeCoultre, tout un monde d'opportunités s'ouvre à vous ! La transmission du savoir est l'âme même de notre métier : vous aurez accès à un programme de formation sur mesure. Dans nos bureaux Suisses, nous répondons à votre désir de bien-être et d'équilibre, grâce à un lieu de travail stimulant, du travail à distance, des horaires flexibles, une contribution à la mobilité durable, des services sur site et du temps pour le bénévolat. Notre Maison travaille sans relâche pour gérer son empreinte environnementale et créer un impact positif sur la société grâce à nos efforts collectifs. Apprenez-en davantage sur nos engagements en termes de Développement Durable dans notre programme « Rendre notre Monde Meilleur ».\nPostuler » 2023-05-30 15:26:01.789000+02:00                                       https://jobs.richemont.com/Jaeger-LeCoultre/job/Le-Sentier-Stagiaire-Data-Scientist-%28HF%29-6-mois-VD/940604901/                                                   data scientist        40034768.0                      False                              NaN ['65000037', '65000006']             ['11000879']                                                                                                       ['VD']                                  NaN
083d6c5e-c10c-418b-96a2-0d5692a6881a                          Senior Data Engineering Consultant                                   Innovation Process Technology AG   Kleinunternehmen                     CH 6300 Zug                                                                                                                                                                                                Senior Data Engineering Consultant\n\nWir sind eine Schweizer IT-Consulting Firma. Wir bauen innovative Lösungen beim Kunden vor Ort. Uns gibt es schon seit über 20 Jahren, aber wir leben immer noch eine Start-up Mentalität – 140 Leute, Flat Hierarchy, No Politics, Lots of Fun! Bei uns gilt: People First! Jeder kann sich bei uns einbringen und zum Experten werden. Wissen wird geteilt und gegenseitige Unterstützung ist zentral. We’re ONE Team!\n\nDeine Challenges\n\nDu berätst unsere Kunden und verstehst deren Bedürfnisse. Dabei konzipierst du Big Data Projekte und setzt diese im Team mit innovativen Technologien um\n\nDu bereitest strukturierte und unstrukturierte Datenbestände mit unterschiedlichen Datentypen und Formaten für analytische Zwecke auf\n\nKonzipieren und Einrichten von Werkzeugen für die Datenverarbeitung\n\nDaten Pipelines automatisieren für die Konsolidierung, Bereinigung und Bereitstellung von Daten\n\nDu bringst dich zu Themen ein, die Data Governance, Access Management und Security betreffen\n\nDas bringst du mit\n\n2-6 Jahre Projekterfahrung im Software oder Data Engineering und fundiertes Know-how Big Data Technologien\n\nSehr guter Umgang mit Daten, Speichertechnologien und Transformationswerkzeugen\n\nVertiefte Kenntnisse in mind. einer Big Data Technologie wie z.B. Spark, Hadoop, Rapidminer, Hive oder Impala\n\nAbgeschlossenes Studium (Informatik, Wirtschaftsinformatik, Mathematik, Elektrotechnik, Physik o.ä.)\n\nLeidenschaft, sich schnell in neue Themen und Technologien einzuarbeiten\n\nSehr gute analytische, methodische und konzeptionelle Fähigkeiten\n\nTeamplayer und starke kommunikative Fähigkeiten\n\nProfessionelles Auftreten und fliessende Deutsch- und Englischkenntnisse\n\nDas sind unsere Benefits für dich\n\nGarantierte Abwechslung: Verschiedene Kunden, Themen, Methoden und Technologien – als Consultant wird es nicht langweilig\n\nFrequent Check-in: Mitarbeitergespräche führen wir agil – du bestimmst selbst wann, mit wem und wie oft\n\nSoziales Engagement: Jeder hat die Möglichkeit, sich sozial zu engagieren\n\nHardfacts\n\nDein Arbeitsort ist vor Ort beim Kunden in der Deutschschweiz (ZH, LU, BS, BE)\n\n80-100% Pensum\n\nDieses Stelleninserat umschreibt ein Szenario, das dich in einem Projekt erwarten könnte. Wir suchen daher Talente, die für verschiedene Themen und Technologien offen sind.\n\nP.S. Wir schauen optimistisch in die Zukunft und suchen auch in Zeiten von COVID-19 passende Bewerbende, die unser Team verstärken und uns weiterbringen.\n\nHast du Fragen?\n\nSina Bachmann\nHuman Resources\n\nWir freuen uns auf deine Bewerbung!\nAnredeHerrFrauVornameNameE-MailTelefonDein Xing-ProfilDein Linkedin-ProfilBewerbungsschreiben\n\n.pdf, .doc, .zip (max. 20MB)\n\nLebenslauf\n\n.pdf, .doc, .zip (max. 20MB)\n\nWeitere Dokumente\n\n.pdf, .doc, .zip (max. 20MB)\n\nWeitere LinksBemerkungWie bist du auf ipt aufmerksam geworden?Ich habe die Datenschutzbestimmungen gelesen und bin damit einverstanden.Comments 2019-11-28 16:49:35.061000+01:00                                                                                        https://ipt.ch/karriere/jobs/senior-data-engineering-consultant/                                                           hadoop        40003413.0                      False 2020-04-28 19:04:43.763000+02:00             ['65000019']             ['11000066']                                                                                                       ['ZG']                                  NaN
095c2560-c278-484c-b22f-35914964822d                            Digital Transformation Architect                                Bundesamt für Zivilluftfahrt (BAZL)  Mittelunternehmen                    Ittigen (BE)                                                                                          Das Bundesamt für Zivilluftfahrt BAZL sucht\n\nDigital Transformation Architect*\n\n80 - 100% / Ittigen*\n\nBewegt die Schweiz.* Sie unterstützen die Leitung der Stabseinheit Innovation und Digitalisierung ID im Themenbereich Digitalisierung und Informationstechnologie. Im Vordergrund steht die ganzheitliche Analyse IT relevanter Fragestellungen bei Innovationsprozessen im Rahmen der digitalisierten Flugsicherung (U-Space) sowie die für Internet of Things (IoT) relevanten Aspekten der Drohnentechnologie.\n\nIhre Aufgaben*\n\nErarbeiten von Grundlagen für die Zulassung nicht-deterministischer Software-Ansätze in sicherheitsrelevanten Kontexten mit Fokus auf künstliche Intelligenz (AI)\n\nBeteiligen an Bewilligungsprozessen, bei denen U-Space Dienste als Risikomitigationsstrategien eingesetzt werden\n\nVertreten des Amtes in nationalen und internationalen Gremien, die sich mit Themen der Innovation und Digitalisierung befassen sowie unterstützen anderer Mitarbeitenden in diesem Bereich\n\nMitarbeiten im U-Space Integrationsprogramm des Amtes, inklusive leiten von Teilprojektgruppen und Erstellen von Dokumentation\n\nIhre Kompetenzen*\n\nHochschulabschluss (Lizentiat oder Master) und funktionsrelevante Erfahrung im Bereich IoT (Internet of Things)\n\nDiplomatisches Geschick und Erfahrung in der Vertretung von Interessen oder Leitung internationaler Policy und Rechtssetzungsprozesse\n\nRasche Auffassungsgabe, Flexibilität und Fähigkeit, sich auf veränderte, herausfordernde Situationen einstellen zu können, sowie Einsatzbereitschaft und Freude an der Arbeit im Team\n\nGute aktive Kenntnisse mindestens einer zweiten Amtssprache und wenn möglich passive Kenntnisse einer dritten Amtssprache und sehr gute Englischkennnisse\n\nZusatzinformationen*\n\nErgänzende Auskünfte erteilt Ihnen gerne: Herr Lorenzo Murzilli, Programmleiter U-Space Integrationsprogramm, Tel. +41 58 465 90 09 Arbeitsbeginn 01.04.2019 oder nach Vereinbarung. Die Anstellung ist auf 2 Jahre befristet.\n\nZum Arbeitgeber*\n\nDas Bundesamt für Zivilluftfahrt (BAZL) ist für die Aufsicht über die zivile Luftfahrt in der Schweiz und für die nachhaltige Luftfahrtentwicklung zuständig, sorgt für ein hohes Sicherheitsniveau und schafft die Voraussetzungen für eine optimale internationale Vernetzung. Das BAZL ist Teil des Eidgenössischen Departments für Umwelt, Verkehr, Energie und Kommunikation (UVEK). Als Mitarbeiterin oder Mitarbeiter des BAZL bewegen Sie die Schweiz. Sie übernehmen Verantwortung für die erfolgreiche Entwicklung unseres Landes. Das BAZL bietet Ihnen die Möglichkeit, in einem modernen und flexiblen Arbeitsumfeld einen wesentlichen Beitrag für eine sichere und international vernetzte Schweiz zu leisten.\n\nMühlestrasse 2, 3063 Ittigen\n\nDie Bundesverwaltung achtet die unterschiedlichen Biografien ihrer Mitarbeitenden und schätzt deren Vielfalt. Gleichbehandlung geniesst höchste Priorität. Da die französische und italienische Sprachgemeinschaft in unserer Verwaltungseinheit untervertreten ist, freuen wir uns über Bewerbungen von Personen dieser Sprachgemeinschaften. 2019-02-19 23:46:33.843000+01:00 https://www.job-room.ch/job-search/job-fingerprint-redirect?externalId=db785d0bfc2d8b79fac833153c85afbae03de9ba5bf709de10ab3b27fe03b3e845dcd88653169a8c               ai, kunstliche intelligenz, künstliche intelligenz        40003771.0                      False 2019-03-22 00:04:08.473000+01:00             ['65000028']             ['11000596']                                                                                                       ['BE']                                  NaN

In [6]:
import pandas as pd

# --- Load files ---
f1 = "Data/LLM_output/ai_development_training_companies_200_jobs_step1_extracted.csv"
f2 = "Data/ai_development_training_companies_200_jobs.csv"

# Read as string to avoid int/float mismatches on `uid`
df1 = pd.read_csv(f1, dtype={"uid": str})
df2 = pd.read_csv(f2, dtype={"uid": str})

# Normalize uid (trim whitespace)
df1["uid"] = df1["uid"].str.strip()
df2["uid"] = df2["uid"].str.strip()

# --- Merge on uid with indicator ---
merged = df1.merge(
    df2,
    how="outer",
    on="uid",
    indicator=True,
    suffixes=("_step1", "_train"),
)

# Unmatched sets
left_only = merged[merged["_merge"] == "left_only"]   # in step1 only
right_only = merged[merged["_merge"] == "right_only"] # in train only

# --- Show quick summary ---
print(f"Rows in step1: {len(df1)}")
print(f"Rows in train: {len(df2)}")
print(f"Unmatched (step1 only): {len(left_only)}")
print(f"Unmatched (train only): {len(right_only)}")

# --- Display unmatched rows (first 20 each) ---
step1_cols = ["uid"] + [c for c in merged.columns if c.endswith("_step1")]
train_cols = ["uid"] + [c for c in merged.columns if c.endswith("_train")]

print("\n=== Present in step1 only ===")
print(left_only[step1_cols].head(20).to_string(index=False))

print("\n=== Present in train only ===")
print(right_only[train_cols].head(20).to_string(index=False))

# (Optional) Save unmatched to CSVs:
# left_only.to_csv("unmatched_step1_only.csv", index=False)
# right_only.to_csv("unmatched_train_only.csv", index=False)

Rows in step1: 200
Rows in train: 200
Unmatched (step1 only): 0
Unmatched (train only): 0

=== Present in step1 only ===
Empty DataFrame
Columns: [uid, title_step1, company_name_step1, company_size_step1, location_raw_step1, content_clean_step1, tst_created_step1, url_step1, matched_keywords_step1, company_id_step1, company_is_recruiter_step1, tst_deleted_step1, x28_industries_step1, x28_occupations_step1, cantons_step1, duplicate_group_step1]
Index: []

=== Present in train only ===
Empty DataFrame
Columns: [uid, title_train, company_name_train, company_size_train, location_raw_train, content_clean_train, tst_created_train, url_train, matched_keywords_train, company_id_train, company_is_recruiter_train, tst_deleted_train, x28_industries_train, x28_occupations_train, cantons_train, duplicate_group_train]
Index: []

In [2]:
pd.read_parquet('Data/dedup_apps.parquet')

,job_uid,app_text,original_text,first_occurrence_tst_created
0,825250ee-2514-4bf7-8c1c-9dcf6cd1ac9a,detect performance degradation in deployed mac...,Detect performance degradation in deployed mac...,2022-08-11 13:11:05.675000+02:00
1,753c35b5-1e4c-4439-b8fc-10ca2b5baa51,publish standardized api endpoints and cli com...,Publish standardized API endpoints and CLI com...,2022-05-31 10:02:38.718000+02:00
2,c9ac2369-88c6-42a7-8f28-af45cd68e356,"flag incomplete, inconsistent, or out-of-range...","Flag incomplete, inconsistent, or out-of-range...",2023-11-22 19:16:21.510000+01:00
3,6bb7eb47-d5d7-4971-be79-e46cfcbbe2fc,rank actionable business insights derived from...,Rank actionable business insights derived from...,2022-04-19 19:37:10.451000+02:00
4,3926f308-27f7-4897-bcd2-a57e78575cb0,render high-fidelity three-dimensional models ...,Render high-fidelity three-dimensional models ...,2021-10-01 11:31:44.596000+02:00
...,...,...,...,...
584,908fc3d2-0878-4854-bd5a-10a24a08648e,detect and track faces within live camera feed...,Detect and track faces within live camera feed...,2022-05-11 13:55:49.372000+02:00
585,fe2ec994-3665-44dd-a540-6c1ba96c29eb,forecast time-series values for flexibility-po...,Forecast time-series values for flexibility-po...,2024-09-13 12:46:32.673000+02:00
586,f9ede764-ab55-4e43-ad92-195caddf272e,extract actionable customer segments from raw ...,Extract actionable customer segments from raw ...,2019-06-27 21:42:08.426000+02:00
587,7c9cfe87-4196-44e7-bdc4-4f03c87dc0db,cluster large-scale communication data streams...,Cluster large-scale communication data streams...,2025-05-29 05:09:44.231000+02:00
588,79dd79ae-a7c2-4db0-8b72-17c626c26cbe,forecast future values of target variables usi...,Forecast future values of target variables usi...,2019-06-27 21:42:07.276000+02:00

In [34]:
# Build ~1M jobs from companies found in Data/ai_development_deduplicated.csv
# Includes ALL seed UIDs + random sample of other jobs from those companies
# Exports only: uid, company_id, content_clean, duplicate_group

import os
import math
import csv
import psycopg2
import pandas as pd
from io import StringIO
from dotenv import load_dotenv

# -------------------
# Config
# -------------------
SEED_FILE = "Data/ai_development_deduplicated_custom.csv"
OUTPUT_FILE = "Data/ai_company_jobs_target1M.csv"
TARGET_TOTAL = 1_000_000  # desired total rows
UID_COL = "uid"           # must exist in seed file

# -------------------
# Load seed CSV
# -------------------
seed = pd.read_csv(SEED_FILE)

if UID_COL not in seed.columns:
    raise ValueError(f"Column '{UID_COL}' not found in {SEED_FILE}")

# Prefer company_id if present; otherwise fall back to company_name
if "company_id" in seed.columns and seed["company_id"].notna().any():
    COMPANY_MODE = "id"
    COMPANY_COL = "company_id"
    seed_companies = (
        seed[COMPANY_COL]
        .dropna()
        .astype(str)
        .drop_duplicates()
        .tolist()
    )
else:
    if "company_name" not in seed.columns:
        raise ValueError(f"Neither 'company_id' nor 'company_name' present/useful in {SEED_FILE}")
    COMPANY_MODE = "name"
    COMPANY_COL = "company_name"
    seed_companies = (
        seed[COMPANY_COL]
        .dropna()
        .astype(str)
        .drop_duplicates()
        .tolist()
    )

# UIDs as strings (must be valid UUIDs in DB)
seed_uids = (
    seed[UID_COL]
    .dropna()
    .astype(str)
    .drop_duplicates()
    .tolist()
)

print(f"Seed companies ({'company_id' if COMPANY_MODE=='id' else 'company_name'}): {len(seed_companies):,}")
print(f"Seed UIDs: {len(seed_uids):,}")

# -------------------
# Connect to DB
# -------------------
load_dotenv("config.env")
conn = psycopg2.connect(
    dbname=os.getenv("DB_NAME"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST", "localhost"),
    port=os.getenv("DB_PORT", "5432"),
)
conn.autocommit = True
conn.set_client_encoding('UTF8')
cur = conn.cursor()

# -------------------
# Create TEMP tables & bulk load (CSV-safe)
# -------------------
cur.execute("DROP TABLE IF EXISTS temp_companies;")
if COMPANY_MODE == "id":
    cur.execute("CREATE TEMP TABLE temp_companies(company_id text);")
else:
    cur.execute("CREATE TEMP TABLE temp_companies(company_name text);")

cur.execute("DROP TABLE IF EXISTS temp_uids;")
# Make temp_uids UUID so we can join jp.uid = tu.uid without casting (uses index on jp.uid)
cur.execute("CREATE TEMP TABLE temp_uids(uid uuid);")

def copy_list_to_temp(cur, table, col, items):
    sio = StringIO()
    w = csv.writer(sio)  # proper CSV quoting for commas/newlines
    for x in items:
        w.writerow([("" if x is None else str(x).strip())])
    sio.seek(0)
    cur.copy_expert(f"COPY {table}({col}) FROM STDIN WITH (FORMAT csv)", sio)

# Load companies/uids
if COMPANY_MODE == "id":
    copy_list_to_temp(cur, "temp_companies", "company_id", seed_companies)
    cur.execute("CREATE INDEX ON temp_companies(company_id);")
else:
    copy_list_to_temp(cur, "temp_companies", "company_name", seed_companies)
    cur.execute("CREATE INDEX ON temp_companies(company_name);")

# COPY will auto-cast valid UUID strings into uuid column
copy_list_to_temp(cur, "temp_uids", "uid", seed_uids)
cur.execute("CREATE INDEX ON temp_uids(uid);")

# Sanity counts (optional)
cur.execute("SELECT COUNT(*) FROM temp_companies"); print("temp_companies rows:", cur.fetchone()[0])
cur.execute("SELECT COUNT(*) FROM temp_uids"); print("temp_uids rows:", cur.fetchone()[0])

# -------------------
# Count already-included (seed) rows
# -------------------
cur.execute("""
    SELECT COUNT(*) 
    FROM job_postings jp 
    JOIN temp_uids tu ON jp.uid = tu.uid
    WHERE jp.content_clean IS NOT NULL
""")
included_ct = cur.fetchone()[0]
print(f"Already-included rows (seed UIDs): {included_ct:,}")

need_more = max(TARGET_TOTAL - included_ct, 0)
if need_more == 0:
    print("We already meet or exceed the target; exporting seed rows only.")

# -------------------
# Count eligible extras (same companies, not in seed uids)
# -------------------
if COMPANY_MODE == "id":
    join_company = "tc.company_id = jp.company_id::text"  # temp is text; cast jp side (unknown base type)
else:
    join_company = "tc.company_name = jp.company_name"

cur.execute(f"""
    SELECT COUNT(*)
    FROM job_postings jp
    JOIN temp_companies tc ON {join_company}
    LEFT JOIN temp_uids tu ON tu.uid = jp.uid
    WHERE tu.uid IS NULL
      AND jp.content_clean IS NOT NULL
""")
eligible_ct = cur.fetchone()[0]
print(f"Eligible additional rows: {eligible_ct:,}")

# -------------------
# Decide sampling modulus k (0..1000), md5-based predicate
# -------------------
if need_more > 0 and eligible_ct > 0:
    frac = need_more / float(eligible_ct)
    k = min(1000, max(0, math.ceil(1000 * frac)))
    if k == 0:
        k = 1  # ensure some sampling; LIMIT will cap to need_more
else:
    k = 0
print(f"Sampling modulus k: {k} (out of 1000)")

# -------------------
# Seed SQL (ALL seed UIDs, exact match)
# -------------------
seed_sql = """
    SELECT jp.uid::text, jp.company_id::text, jp.content_clean, jp.duplicate_group
    FROM job_postings jp
    JOIN temp_uids tu ON jp.uid = tu.uid
    WHERE jp.content_clean IS NOT NULL
"""

# -------------------
# Extra SQL (sample from same companies, excluding seed uids)
# Deterministic md5-based sampling; LIMIT caps to need_more
# -------------------
if need_more > 0 and eligible_ct > 0 and k > 0:
    extra_sql = f"""
        SELECT jp.uid::text, jp.company_id::text, jp.content_clean, jp.duplicate_group
        FROM job_postings jp
        JOIN temp_companies tc ON {join_company}
        LEFT JOIN temp_uids tu ON tu.uid = jp.uid
        WHERE tu.uid IS NULL
          AND jp.content_clean IS NOT NULL
          AND ( ('x' || substr(md5(jp.uid::text), 1, 8))::bit(32)::int % 1000 ) < {k}
        LIMIT {need_more}
    """
else:
    # empty result
    extra_sql = """
        SELECT uid::text, company_id::text, content_clean, duplicate_group
        FROM (SELECT NULL::text uid, NULL::text company_id, NULL::text content_clean, NULL::text duplicate_group) x
        WHERE false
    """

# -------------------
# UNION ALL + DISTINCT ON (uid) so seed rows win
# -------------------
final_sql = f"""
WITH seed AS (
  {seed_sql}
),
extra AS (
  {extra_sql}
),
unioned AS (
  SELECT 1 AS src, * FROM seed
  UNION ALL
  SELECT 2 AS src, * FROM extra
)
SELECT uid, company_id, content_clean, duplicate_group
FROM (
  SELECT DISTINCT ON (uid) uid, company_id, content_clean, duplicate_group, src
  FROM unioned
  ORDER BY uid, src        -- src=1 (seed) preferred over src=2 (extra)
) t
"""

print("Exporting to CSV via COPY ...")
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    cur.copy_expert(
        f"COPY ({final_sql}) TO STDOUT WITH CSV HEADER",
        f
    )

# -------------------
# Sanity checks
# -------------------
out_df = pd.read_csv(OUTPUT_FILE, usecols=["uid", "company_id", "content_clean", "duplicate_group"])
print(f"Wrote {len(out_df):,} rows to {OUTPUT_FILE}")
assert out_df["uid"].is_unique, "Duplicate UIDs detected in output (should be unique)"
print("UID uniqueness check passed ✅")

cur.close()
conn.close()
print("Done.")

Seed companies (company_id): 1,774
Seed UIDs: 56,942

InvalidTextRepresentation: invalid input syntax for type uuid: "surr_cbe0aa4810777b787fdac91940bc19c2bebbbf3b"
CONTEXT:  COPY temp_uids, line 1, column uid: "surr_cbe0aa4810777b787fdac91940bc19c2bebbbf3b"

In [35]:
df = pd.read_csv('Data/ai_company_jobs_target1M.csv')

df_deduped = pd.read_csv('Data/ai_development_deduplicated_custom.csv')

df.head(5)

,uid,company_id,content_clean,duplicate_group
0,surr_00002e8bb7f4d1731d432d6d181026799769e745,40002971,Assistant en pharmacie (f/h)\n\n«Tu apprécies ...,cc16bddc-4c2f-4f6e-9bd7-5d7a2159e4b5
1,surr_00003d0bf7e9a710320aa9f13c45dd266dd69dcf,40013969,"tilia bietet Menschen ab dem 18. Lebensjahr, w...",7f49333f-b382-4237-8aa2-8f933cdbbc57
2,surr_000057fad2392985f862b75acfc40b522fae4eac,40001514,L'Office fédéral de l'informatique et de la té...,6b1f72d9-030d-4b7a-81ba-2d44d704fbd4
3,surr_000060659aeade0864c7e1aaa3ee7f9cc144b859,40001635,"Primarlehrkraft, Ref.-Nr. 42805D\n\n Bezeichnu...",d07fe2ae-0eff-41d7-b3c1-41e6cfca238b
4,surr_0000689e9407a0bf94c41fc2af083459cd8e1990,40001349,Heute die Chancen von morgen erkennen.\nIhre u...,9f544892-126f-4d0c-a306-3002c42d2328

In [36]:
df_deduped.head()

,uid,title,company_name,company_size,location_raw,content_clean,tst_created,url,matched_keywords,company_id,company_is_recruiter,tst_deleted,x28_industries,x28_occupations,cantons,duplicate_group
0,surr_cbe0aa4810777b787fdac91940bc19c2bebbbf3b,Wissenschaftliche(r) Mitarbeiter(in) 80 %,Kanton Bern,Mittelunternehmen,Bern,Wissenschaftliche(r) Mitarbeiter(in) 80 %\nKad...,2012-01-02 02:57:28.579000+01:00,http://www.jobs.sites.be.ch/jobs_sites/de/inde...,ai(punct),40001635,False,2012-01-17 03:33:41.730000+01:00,['65000028'],['11001434'],['BE'],f2241899-081c-4289-9c2d-2b7bd35aaf10
1,surr_0394510f1b309137591d488c86ddc1aa842fd07a,Berufslehre Kauffrau / Kaufmann,Kendrion (Switzerland) AG,Grossunternehmen,CH-8915 Hausen am Albis,Berufslehre Kauffrau / Kaufmann\n\nWir bieten ...,2012-01-02 12:21:17.327000+01:00,http://www.kendrion-electromagnetic.com/job/au...,aa(punct),40015712,False,2012-01-13 16:31:58.532000+01:00,['65000006'],['11000034'],['ZH'],82fc221d-74e9-45de-9aed-4cbdd7da06c0
2,surr_fbf729a46653ca87cd398c3ce12ae1d060943aab,Berufslehre Kauffrau / Kaufmann,Kendrion (Switzerland) AG,Grossunternehmen,CH-8915 Hausen am Albis,Berufslehre Kauffrau / Kaufmann\n\nWir bieten ...,2012-01-02 12:21:26.947000+01:00,http://www.kendrion-electromagnetic.com/job/au...,aa(punct),40015712,False,2012-01-20 13:56:22.771000+01:00,['65000006'],['11000034'],['ZH'],e6000153-3168-41fd-8a2d-37d72012d8b0
3,surr_8bc65d6670785d55378bcb2fee3004efa51976d5,Team Leader pour service et cuisine et Employé...,Autogrill Schweiz AG,Grossunternehmen,Genève,Team Leader pour service et cuisine et Employé...,2012-01-04 12:34:32.229000+01:00,http://www.autogrill.ch/page/index.cfm?SelNavI...,caffe,40000111,False,2012-01-24 15:58:00.189000+01:00,['65000013'],"['11000051', '11001814']",['GE'],3ddc612d-8527-4da1-9a8d-94173d2a1093
4,surr_7dda7bd163b960db2f918e3c69c99ca41e156b7f,Senior Global Program Regulatory Manager (IHC),Novartis AG,Grossunternehmen,Basel,Senior Global Program Regulatory Manager (IHC)...,2012-01-04 22:08:46.177000+01:00,https://sjobs.brassring.com/2057/ASP/TG/cim_jo...,gpt,40001153,False,2012-02-03 18:54:55.452000+01:00,['65000030'],['11002231'],"['BS', 'BL']",0b2f72d0-9625-4e0f-89f7-15d49d07af03

In [37]:
df_merge = df[['uid','duplicate_group','content_clean']].merge(df_deduped[['uid']], on='uid', how='outer', indicator=True)
df_merge

,uid,duplicate_group,content_clean,_merge
0,surr_00002e8bb7f4d1731d432d6d181026799769e745,cc16bddc-4c2f-4f6e-9bd7-5d7a2159e4b5,Assistant en pharmacie (f/h)\n\n«Tu apprécies ...,left_only
1,surr_00003d0bf7e9a710320aa9f13c45dd266dd69dcf,7f49333f-b382-4237-8aa2-8f933cdbbc57,"tilia bietet Menschen ab dem 18. Lebensjahr, w...",left_only
2,surr_000057fad2392985f862b75acfc40b522fae4eac,6b1f72d9-030d-4b7a-81ba-2d44d704fbd4,L'Office fédéral de l'informatique et de la té...,both
3,surr_000060659aeade0864c7e1aaa3ee7f9cc144b859,d07fe2ae-0eff-41d7-b3c1-41e6cfca238b,"Primarlehrkraft, Ref.-Nr. 42805D\n\n Bezeichnu...",left_only
4,surr_0000689e9407a0bf94c41fc2af083459cd8e1990,9f544892-126f-4d0c-a306-3002c42d2328,Heute die Chancen von morgen erkennen.\nIhre u...,left_only
...,...,...,...,...
999995,surr_ffff8b822bbed1669ee52c750110fe21b1b1e238,3c095116-748e-4c7b-955b-4d04514b723d,Business Analyst - SQLin Geneva\n veröffentlic...,left_only
999996,surr_ffff9cf8cc9f87817851afbce7a33b48bd6e1367,d4b17ec4-8c6e-4823-bd47-4f06a0000063,NaN,left_only
999997,surr_ffffa673b81d6daa57f83c8597c800b3ba0b0926,7b0e772a-8c74-4d77-abbf-2bbaaa38f6de,"Departement Bildung, Kultur und Sport\nAbteilu...",left_only
999998,surr_ffffc0999f05716a547842325683aae451f141c3,21b6732f-2d38-4cf7-8973-7a052ebaaa5e,"Praktikum im Rahmen der Anwaltsausbildung, Ref...",left_only
999999,surr_ffffc86fb6ba25c027171b120e575d6b405ea364,314a7399-a4a2-4939-86dd-7092c408e9fe,De plus amples informations peuvent\n\nêtre ob...,left_only

In [38]:
len(df_deduped) - len(df_merge[df_merge['_merge']=='both'])

0

In [39]:
df[df['duplicate_group'].isna()]

Empty DataFrame
Columns: [uid, company_id, content_clean, duplicate_group]
Index: []

In [3]:
import os
import psycopg2
from dotenv import load_dotenv

# Load DB credentials
load_dotenv("config.env")
conn = psycopg2.connect(
    dbname=os.getenv("DB_NAME"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST", "localhost"),
    port=os.getenv("DB_PORT", "5432"),
)
cur = conn.cursor()

# Run the query
cur.execute("""
    SELECT 
        COUNT(*) AS total_rows,
        SUM(CASE WHEN duplicate_group IS NULL THEN 1 ELSE 0 END) AS null_rows
    FROM job_postings
    WHERE YEAR(tst_created) < 2018;
""")

total, nulls = cur.fetchone()
print(f"Total rows: {total:,}")
print(f"Rows with duplicate_group = NULL: {nulls:,} ({nulls/total:.1%})")

cur.close()
conn.close()

🔐 DB env check:
  DB_NAME=kurerallardice2024
  DB_USER=ballardice
  DB_HOST=localhost
  DB_PORT=5432
  DB_SSLMODE=prefer
  DB_PASSWORD=B…
🌐 localhost resolves to 127.0.0.1
🔌 TCP connect to localhost:5432 OK
❌ Table 'jobs' not found.

SystemExit: 1

/Users/bradyallardice/opt/miniconda3/envs/allardicekurer2025/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3513: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [27]:
import gzip, json, io
from collections import Counter

# If you have ijson, we'll use it for streaming arrays
try:
    import ijson
    HAVE_IJSON = True
except Exception:
    HAVE_IJSON = False

path = "/Users/bradyallardice/Downloads/240722_panel_data_data_000000000002.json.gzip"

# Try these field names; add more if needed.
CANDIDATES = ["duplicate_group", "duplicateGroup", "dup_group", "duplicate_group_id"]

def sniff_format_gz(path) -> str:
    """Return 'ndjson' or 'array' by peeking the first non-whitespace char."""
    with gzip.open(path, "rt", encoding="utf-8", errors="ignore") as f:
        while True:
            ch = f.read(1)
            if not ch:
                return "ndjson"   # empty -> treat as ndjson
            if ch.isspace():
                continue
            return "array" if ch == "[" else "ndjson"

def pick_field(record):
    for k in CANDIDATES:
        if k in record:
            return k
    return None

def normalize_group(val):
    """Return a normalized string id or None for null/empty."""
    if val is None:
        return None
    # sometimes the field can be a list; stringify consistently
    if isinstance(val, (list, tuple)):
        if not val:
            return None
        val = "|".join(str(x) for x in val)
    s = str(val).strip()
    return s if s else None

fmt = sniff_format_gz(path)
print(f"Detected JSON format: {fmt.upper()}")

total = 0
nulls = 0
group_counts = Counter()
chosen_col = None

if fmt == "ndjson":
    with gzip.open(path, "rt", encoding="utf-8", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            if chosen_col is None:
                chosen_col = pick_field(rec)
                if chosen_col is None:
                    raise RuntimeError(f"None of {CANDIDATES} present in records.")
            total += 1
            g = normalize_group(rec.get(chosen_col))
            if g is None:
                nulls += 1
            else:
                group_counts[g] += 1

elif fmt == "array":
    if HAVE_IJSON:
        with gzip.open(path, "rb") as f:
            for rec in ijson.items(f, "item"):
                if chosen_col is None:
                    chosen_col = pick_field(rec)
                    if chosen_col is None:
                        raise RuntimeError(f"None of {CANDIDATES} present in records.")
                total += 1
                g = normalize_group(rec.get(chosen_col))
                if g is None:
                    nulls += 1
                else:
                    group_counts[g] += 1
    else:
        # Fallback: one-shot load (may be memory heavy)
        import pandas as pd
        print("⚠️ ijson not installed; falling back to full load with pandas (no chunksize).")
        df = pd.read_json(path, lines=False, compression="gzip")
        # choose column
        for c in CANDIDATES:
            if c in df.columns:
                chosen_col = c
                break
        if chosen_col is None:
            raise RuntimeError(f"None of {CANDIDATES} found. Columns: {list(df.columns)[:50]}")
        s = df[chosen_col]
        total = len(s)
        # treat empty strings as null
        null_mask = s.isna() | s.astype(str).str.strip().eq("")
        nulls = int(null_mask.sum())
        # count groups (normalize lists)
        def norm(x):
            if isinstance(x, (list, tuple)):
                if not x: return None
                x = "|".join(str(v) for v in x)
            x = None if x is None else str(x).strip() or None
            return x
        vals = [norm(v) for v in s.tolist()]
        for v in vals:
            if v is not None:
                group_counts[v] += 1

nonnull_rows = total - nulls
n_groups = len(group_counts)
groups_size1 = sum(1 for n in group_counts.values() if n == 1)
groups_size_gt1 = sum(1 for n in group_counts.values() if n > 1)
rows_in_groups_gt1 = sum(n for n in group_counts.values() if n > 1)

print("\n=== Duplicate Group Coverage (from gzip JSON) ===")
print(f"Field used: {chosen_col}")
print(f"Total rows: {total:,}")
print(f"Rows with {chosen_col}=NULL/empty: {nulls:,} ({nulls/total:.1%})")
print(f"Rows with {chosen_col} present:   {nonnull_rows:,} ({nonnull_rows/total:.1%})")
print(f"Distinct {chosen_col} values:     {n_groups:,}")
print(f"  groups with size = 1:           {groups_size1:,}")
print(f"  groups with size > 1:           {groups_size_gt1:,}")
print(f"Rows in size>1 groups:            {rows_in_groups_gt1:,} "
      f"({rows_in_groups_gt1/total:.1%} of all rows)")

Detected JSON format: NDJSON

RuntimeError: None of ['duplicate_group', 'duplicateGroup', 'dup_group', 'duplicate_group_id'] present in records.

In [9]:
import os
import pandas as pd
import psycopg2
from dotenv import load_dotenv

# ---------- connect ----------
load_dotenv("config.env")
conn = psycopg2.connect(
    dbname=os.getenv("DB_NAME"),
    user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST", "localhost"),
    port=os.getenv("DB_PORT", "5432"),
)
conn.autocommit = True

def qdf(query, params=None):
    return pd.read_sql_query(query, conn, params=params)

def Q_ident(s: str) -> str:
    """Quote an identifier as "schema" or "table" safely for plain-string SQL."""
    return '"' + s.replace('"', '""') + '"'

def QT(schema: str, table: str) -> str:
    return f"{Q_ident(schema)}.{Q_ident(table)}"

print("Connected.")

# ---------- find tables that have duplicate_group ----------
cand = qdf("""
SELECT c.table_schema, c.table_name, c.column_name, c.data_type
FROM information_schema.columns c
WHERE c.column_name = 'duplicate_group'
ORDER BY c.table_schema, c.table_name
""")

if cand.empty:
    print("No exact 'duplicate_group' column found. Looking for similar names...")
    similar = qdf("""
        SELECT c.table_schema, c.table_name, c.column_name, c.data_type
        FROM information_schema.columns c
        WHERE c.column_name ILIKE '%dup%'
        ORDER BY c.table_schema, c.table_name, c.column_name
    """)
    display(similar.head(50))
    raise SystemExit("⚠️ No exact column; check the similar list above.")

# choose the largest table that has the column
sizes = qdf("""
SELECT n.nspname AS table_schema, c.relname AS table_name, c.reltuples::bigint AS est_rows
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('r','p','m','v')
""")
target = (cand.merge(sizes, on=["table_schema","table_name"], how="left")
              .sort_values("est_rows", ascending=False)
              .iloc[0])
SCHEMA = target["table_schema"]
TABLE  = target["table_name"]
DTYPE  = target["data_type"]
TQUAL  = QT(SCHEMA, TABLE)
print(f"Target: {SCHEMA}.{TABLE}  (est_rows≈{int(target['est_rows'] or 0):,})  duplicate_group type: {DTYPE}")

# ---------- basic counts ----------
total = qdf(f"SELECT COUNT(*) AS n FROM {TQUAL}").iloc[0,0]
nulls = qdf(f"SELECT COUNT(*) AS n FROM {TQUAL} WHERE duplicate_group IS NULL").iloc[0,0]
print(f"\nTotal rows: {total:,}")
print(f"NULL duplicate_group: {nulls:,} ({(nulls/total*100 if total else 0):.1f}%)")

# blanks only make sense if it's text-like
if any(x in (DTYPE or "").lower() for x in ["char", "text"]):
    blanks = qdf(f"""
        SELECT COUNT(*) AS n
        FROM {TQUAL}
        WHERE duplicate_group IS NOT NULL AND btrim(duplicate_group) = ''
    """).iloc[0,0]
    print(f"Blank duplicate_group: {blanks:,} ({(blanks/total*100 if total else 0):.1f}%)")

# distinct non-null groups
distinct_non_null = qdf(f"""
    SELECT COUNT(DISTINCT duplicate_group) AS n
    FROM {TQUAL}
    WHERE duplicate_group IS NOT NULL
""").iloc[0,0]
print(f"Distinct non-null duplicate_group: {distinct_non_null:,}")

# top group sizes (confirms grouping is functioning)
top_groups = qdf(f"""
    SELECT duplicate_group, COUNT(*) AS ct
    FROM {TQUAL}
    WHERE duplicate_group IS NOT NULL
    GROUP BY duplicate_group
    ORDER BY ct DESC
    LIMIT 10
""")
print("\nTop duplicate_group sizes:")
display(top_groups)

# ---------- month-by-month NULL rate (auto-picks a timestamp) ----------
ts_cols = qdf(f"""
    SELECT column_name, data_type
    FROM information_schema.columns
    WHERE table_schema = %s AND table_name = %s
      AND data_type IN ('timestamp without time zone','timestamp with time zone','date')
""", params=(SCHEMA, TABLE))
prefer = ['tst_created','created_at','posted_at','date_posted','ingested_at','updated_at','date','timestamp']
ts_col = next((c for c in prefer if (ts_cols['column_name'] == c).any()), None)
if ts_col is None and not ts_cols.empty:
    ts_col = ts_cols.iloc[0]['column_name']

if ts_col:
    print(f"\nUsing time column for trend analysis: {ts_col}")
    trend = qdf(f"""
        SELECT
          date_trunc('month', {Q_ident(ts_col)}::timestamp) AS month,
          COUNT(*) AS total_rows,
          SUM(CASE WHEN duplicate_group IS NULL THEN 1 ELSE 0 END) AS null_rows,
          ROUND(100.0 * SUM(CASE WHEN duplicate_group IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 2) AS null_pct
        FROM {TQUAL}
        WHERE {Q_ident(ts_col)} IS NOT NULL
        GROUP BY 1
        ORDER BY 1
    """)
    display(trend)
else:
    print("\n(No timestamp/date column found for month-by-month breakdown.)")

# ---------- which source/batch drives NULLs (if such columns exist) ----------
possible_dims = [
    'source', 'source_name', 'source_site', 'source_domain',
    'batch_id', 'etl_run_id', 'import_id', 'file_id',
    'country', 'language', 'platform'
]
present_cols = qdf("""
SELECT column_name
FROM information_schema.columns
WHERE table_schema = %s AND table_name = %s
""", params=(SCHEMA, TABLE))['column_name'].tolist()

for dim in [c for c in possible_dims if c in present_cols]:
    print(f"\nNULL breakdown by {dim} (top 15 by null count):")
    by_dim = qdf(f"""
        SELECT {Q_ident(dim)} AS {dim},
               COUNT(*) AS total_rows,
               SUM(CASE WHEN duplicate_group IS NULL THEN 1 ELSE 0 END) AS null_rows,
               ROUND(100.0 * SUM(CASE WHEN duplicate_group IS NULL THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 2) AS null_pct
        FROM {TQUAL}
        GROUP BY 1
        HAVING COUNT(*) > 0
        ORDER BY null_rows DESC
        LIMIT 15
    """)
    display(by_dim)

print("\n✅ Diagnostics complete.")

Connected.
Target: public.job_postings  (est_rows≈14,740,887)  duplicate_group type: uuid

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/3658314274.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)
/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/3658314274.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

Total rows: 14,740,887
NULL duplicate_group: 7,779,659 (52.8%)
Distinct non-null duplicate_group: 6,960,762

Top duplicate_group sizes:

                        duplicate_group  ct
0  58275e71-070d-4cd0-9ecb-d7e425cb3f87   2
1  12eb8dfc-f584-4429-9245-f4ac09bdfaf1   2
2  cbb6c266-50a8-4459-a566-2029de352b2b   2
3  441eec20-8e5c-4468-a50d-867d234d4d06   2
4  ade173c7-bc62-49db-84df-c2414b644378   2
5  b945a806-3cb7-40ad-a8ad-d036d87da853   2
6  5a365628-6735-4c12-97f6-f7a623701526   2
7  a621cbf7-0be3-4378-a219-99c51574c91b   2
8  c32ed4bc-65ca-47f4-9e57-6c6d55e687e3   2
9  23351fb4-a31e-4dea-9958-4d10dfa39fe4   2

Using time column for trend analysis: tst_created

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/3658314274.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

         month  total_rows  null_rows  null_pct
0   2012-01-01       77171      43518     56.39
1   2012-02-01       79127      44617     56.39
2   2012-03-01       76056      42886     56.39
3   2012-04-01       81128      45796     56.45
4   2012-05-01       89750      50656     56.44
..         ...         ...        ...       ...
158 2025-03-01       50623          0      0.00
159 2025-04-01       49131          0      0.00
160 2025-05-01       52526          0      0.00
161 2025-06-01       48910          0      0.00
162 2025-07-01         124          0      0.00

[163 rows x 4 columns]

✅ Diagnostics complete.

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/3658314274.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(query, conn, params=params)

In [10]:
import pandas as pd

def qdf(sql, params=None):
    return pd.read_sql_query(sql, conn, params=params)

def Q_ident(s: str) -> str:
    return '"' + s.replace('"','""') + '"'

SCHEMA = "public"
TABLE  = "job_postings"
TQUAL  = f'{Q_ident(SCHEMA)}.{Q_ident(TABLE)}'

cutoff = qdf(f"""
SELECT
  MIN(tst_created) FILTER (WHERE duplicate_group IS NOT NULL) AS first_with_group,
  MAX(tst_created) FILTER (WHERE duplicate_group IS NULL)     AS last_without_group,
  COUNT(*) FILTER (WHERE duplicate_group IS NOT NULL)         AS non_null_rows,
  COUNT(*) FILTER (WHERE duplicate_group IS NULL)             AS null_rows
FROM {TQUAL}
""")
cutoff

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/2378388116.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

,first_with_group,last_without_group,non_null_rows,null_rows
0,2012-01-01 00:49:07.582000+00:00,2023-12-31 23:55:58.233000+00:00,6961228,7779659

In [11]:
# Are there *any* pre-2025-03 rows with duplicate_group filled?
qdf(f"""
SELECT COUNT(*) AS pre_march_filled
FROM {TQUAL}
WHERE tst_created < '2025-03-01'
  AND duplicate_group IS NOT NULL
""")

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/2378388116.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

   pre_march_filled
0           6759914

In [12]:
# discover columns
cols = qdf("""
SELECT column_name
FROM information_schema.columns
WHERE table_schema = %s AND table_name = %s
""", params=(SCHEMA, TABLE))['column_name'].tolist()

candidates = [
    'source','source_name','source_site','source_domain','provider','platform',
    'batch_id','etl_run_id','import_id','file_id','pipeline_version','ingest_version',
    'country','language'
]
dims = [c for c in candidates if c in cols]
dims

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/2378388116.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

[]

In [17]:
for dim in dims:
    print(f"\nNULL breakdown by {dim} (top 15):")
    df = qdf(f"""
        SELECT {Q_ident(dim)} AS {dim},
               COUNT(*) AS total_rows,
               SUM(CASE WHEN duplicate_group IS NULL THEN 1 ELSE 0 END) AS null_rows,
               ROUND(100.0 * SUM(CASE WHEN duplicate_group IS NULL THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0),2) AS null_pct
        FROM {TQUAL}
        GROUP BY 1
        ORDER BY null_rows DESC
        LIMIT 15
    """)
    display(df)

In [18]:
# Pick likely input columns that often feed dedup keys; keep only those that exist
likely_inputs = [
    'title','company_name','city','region','country','location',
    'url','canonical_url','source_url',
    'normalized_title','normalized_company','normalized_location','job_hash'
]
inputs = [c for c in likely_inputs if c in cols]
inputs

['title', 'company_name', 'url']

In [21]:
uid_breakdown = qdf(f"""
WITH t AS (
  SELECT
    CASE
      WHEN uid::text ~ '^[0-9a-f]{{8}}-[0-9a-f]{{4}}-[0-9a-f]{{4}}-[0-9a-f]{{4}}-[0-9a-f]{{12}}$' THEN 'uuid_v4'
      WHEN uid::text ~ '^[0-9]+$' THEN 'numeric'
      WHEN uid::text LIKE 'x28-%' THEN 'x28_prefixed'
      ELSE 'other'
    END AS uid_kind,
    duplicate_group
  FROM {TQUAL}
)
SELECT uid_kind,
       COUNT(*) AS total_rows,
       SUM(CASE WHEN duplicate_group IS NULL THEN 1 ELSE 0 END) AS null_rows,
       ROUND(100.0 * SUM(CASE WHEN duplicate_group IS NULL THEN 1 ELSE 0 END)/NULLIF(COUNT(*),0),2) AS null_pct
FROM t
GROUP BY 1
ORDER BY null_rows DESC
""")
uid_breakdown

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/2378388116.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

  uid_kind  total_rows  null_rows  null_pct
0  uuid_v4    14740887    7779659     52.78

In [16]:
# choose an ID-ish column to show context
id_candidates = [c for c in ['uid','id','job_id','posting_id'] if c in cols]
idcol = id_candidates[0] if id_candidates else None

sel = [c for c in [idcol,'tst_created','source','source_domain','title','company_name','url','canonical_url'] if c in cols]
sel_list = ", ".join(Q_ident(c) for c in sel) if sel else '*'

print("Sample with duplicate_group = NULL")
display(qdf(f"""
SELECT {sel_list}
FROM {TQUAL}
WHERE duplicate_group IS NULL
ORDER BY tst_created DESC
LIMIT 20
"""))

print("Sample with duplicate_group present")
display(qdf(f"""
SELECT {sel_list}
FROM {TQUAL}
WHERE duplicate_group IS NOT NULL
ORDER BY tst_created DESC
LIMIT 20
"""))

Sample with duplicate_group = NULL

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/2378388116.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

,uid,tst_created,title,company_name,url
0,5fffe061-ca22-49a7-90c2-7d06e95647d3,2023-12-31 23:55:58.233000+00:00,Sachbearbeiter/in Human Resources 80 %,SRO AG,https://ohws.prospective.ch/public/v1/jobs/cb3...
1,469f913e-2f71-41e8-9d04-92d36fdb7e68,2023-12-31 23:55:58.233000+00:00,Sachbearbeiter/in Human Resources 80 %,SRO AG,https://ohws.prospective.ch/public/v1/jobs/cb3...
2,174d8e73-f8ef-4dab-92df-71c016e5826e,2023-12-31 23:46:42.113000+00:00,Citrix System Engineer 80-100 %,Abraxas Informatik AG,https://www.abraxas.ch/de/karriere/offene-stel...
3,4e30a278-36eb-4c4b-9a52-e5de99e1e076,2023-12-31 23:46:42.113000+00:00,Netzwerk-Administrator:in 80-100 %,Abraxas Informatik AG,https://www.abraxas.ch/de/karriere/offene-stel...
4,36226b4c-2681-41d6-bed0-7cf032efb6fd,2023-12-31 23:40:14.837000+00:00,Conducteur·trices d'autobus et de trolleybus à...,Transports publics genevois (TPG),https://career5.successfactors.eu/career?compa...
5,021a2b1d-67c1-4125-82d9-9e6edac21a30,2023-12-31 23:39:47.181000+00:00,"SRK-Praktikant/in (15 Tage Praxiseinsatz, 100%...",Stadt Winterthur,https://jobs.winterthur.ch/?yid=6267
6,bc0bd8c9-1874-43f9-8bd8-9d9f9db8cf48,2023-12-31 23:39:47.180000+00:00,"Praktikum Pflege (50-100 %), befristet für 3 b...",Stadt Winterthur,https://jobs.winterthur.ch/?yid=6266
7,2c2a5fe4-708b-4db9-95fa-a403032c862b,2023-12-31 23:39:47.176000+00:00,"Praktikum Pflege (50-100 %), befristet für 3 b...",Stadt Winterthur,https://jobs.winterthur.ch/?yid=6265
8,ee235fed-c565-4b2a-8bd0-f73fa52c10d7,2023-12-31 23:39:47.176000+00:00,"Praktikum Pflege (50-100 %), befristet für 3 b...",Stadt Winterthur,https://jobs.winterthur.ch/?yid=6265
9,c5d2a152-d795-411d-8be0-6c0f632084fc,2023-12-31 23:39:47.175000+00:00,"Praktikum Pflege (50-100 %), befristet für 3 b...",Stadt Winterthur,https://jobs.winterthur.ch/?yid=6264
10,f742f62c-ec4d-430f-a53b-71d30cd2e940,2023-12-31 23:39:47.175000+00:00,"Praktikum Pflege (50-100 %), befristet für 3 b...",Stadt Winterthur,https://jobs.winterthur.ch/?yid=6264
11,67406a1b-ed54-4b12-bbbc-c362a435f767,2023-12-31 23:39:47.173000+00:00,"Praktikum Pflege (50-100 %), befristet für 3 b...",Stadt Winterthur,https://jobs.winterthur.ch/?yid=6263
12,2649f5d9-8b46-4969-8542-540ebe33e6e0,2023-12-31 23:33:14.845000+00:00,(Assistant) Manager - Financial Services Legal...,KPMG AG,https://jobs.kpmg.ch/offene-stellen/assistant-...
13,764e3e3d-51a5-4512-9c7f-6fdb871deeec,2023-12-31 22:14:58.760000+00:00,Service Gastronomie,Coople (Schweiz) AG,https://www.coople.com/ch/public-jobs-top-work...
14,5ee22f82-7b68-490f-8ce6-34d1ec7c21e6,2023-12-31 22:14:58.753000+00:00,Spülküchen-Mitarbeiter/in mit Erfahrung,Coople (Schweiz) AG,https://www.coople.com/ch/public-jobs-top-work...
15,6861d2c1-03b8-49bc-8e0e-b987ed747208,2023-12-31 22:14:58.744000+00:00,Service Gastronomie,Coople (Schweiz) AG,https://www.coople.com/ch/public-jobs-top-work...
16,a74ca3c1-30b6-447e-9b74-ddb3fe8b1982,2023-12-31 22:14:58.740000+00:00,Service Gastronomie,Coople (Schweiz) AG,https://www.coople.com/ch/public-jobs-top-work...
17,ef859feb-c150-4fe3-8e44-be79f4cc205f,2023-12-31 22:14:58.734000+00:00,Verkaufsmitarbeiter/in / Detailhandel,Coople (Schweiz) AG,https://www.coople.com/ch/public-jobs-top-work...
18,a46d1cd2-61f2-4fbe-8df5-7a80666c62f6,2023-12-31 22:14:58.734000+00:00,Service Gastronomie,Coople (Schweiz) AG,https://www.coople.com/ch/public-jobs-top-work...
19,df0f2df5-93cd-4446-9252-895bd21734a2,2023-12-31 22:14:58.734000+00:00,Verkaufsmitarbeiter/in / Detailhandel,Coople (Schweiz) AG,https://www.coople.com/ch/public-jobs-top-work...

Sample with duplicate_group present

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/2378388116.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, conn, params=params)

,uid,tst_created,title,company_name,url
0,1fd7cba2-7b03-4dea-b5ac-8d3b5317baf8,2025-06-30 23:59:17.944000+00:00,Verwaltungsassistentin / Verwaltungsassistent ...,Universität Zürich,https://jobs.uzh.ch/offene-stellen/verwaltungs...
1,e10bea2b-4028-4e0c-94d6-b9eaf3c6fa98,2025-06-30 23:56:05.505000+00:00,Apprentissage Horloger/ère CFC,ETA SA Manufacture Horlogère Suisse,https://www.eta.ch/de/karriere-lehrstellen/ste...
2,802dc0aa-5816-4d62-acc4-5a6ce8c7aad0,2025-06-30 23:56:05.504000+00:00,Apprentissage Horloger/ère de production CFC,ETA SA Manufacture Horlogère Suisse,https://www.eta.ch/de/karriere-lehrstellen/ste...
3,00c25f82-faf9-433e-8fae-6ddf4d9d037c,2025-06-30 23:56:03.695000+00:00,"Professeur-e ordinaire, professeur-e associé-e",Université de Genève,https://jobs.unige.ch/www/wd_portal.show_job?p...
4,a11c797d-4d1f-4b08-b0a7-ca7ccd6d5559,2025-06-30 23:55:28.177000+00:00,"Lehrperson SEMO und PvB, Pensum 60-70% 60-70%",Zweckverband SNH Soziales Netz Bezirk Horgen,https://snh-portal.rexx-recruitment.com/Lehrpe...
5,d0bf77a2-2602-41b1-b12f-0c3fbc9f8dbb,2025-06-30 23:55:28.175000+00:00,Fachperson Recht (80-100 %) 80 - 100%,Zweckverband SNH Soziales Netz Bezirk Horgen,https://snh-portal.rexx-recruitment.com/Fachpe...
6,ccec3af6-6465-432a-aa4e-bfa36821d30e,2025-06-30 23:55:04.839000+00:00,Koch 100% (m/w/d) im Glattpark ZH,Compass Group (Suisse) S.A.,https://jobs.compass-group.ch/offene-stellen/k...
7,2d6f3995-1751-421c-b8fc-da706108ac05,2025-06-30 23:54:28.538000+00:00,Controller*in 60-80 %,Kanton Bern,https://jobs.phbern.ch/offene-stellen/controll...
8,b706bda9-0581-4064-98ac-f95ed4c7d50b,2025-06-30 23:54:18.919000+00:00,Lehrstelle als Mediamatiker/in EFZ 2026 m/w/d ...,RUAG AG,https://jobs.ruag.ch/offene-stellen/lehrstelle...
9,eb4d3f41-daad-4bbe-a0fd-3cdf24218a31,2025-06-30 23:54:09.721000+00:00,Conducteur d'autobus scolaire / Conductrice d'...,Transports publics fribourgeois Holding (TPF) SA,https://emploi.tpf.ch/?page=advertisement_disp...
10,7a7c3a7c-b6d2-448f-a272-d65967000fbf,2025-06-30 23:54:09.720000+00:00,Assistant administratif Offres Transports / As...,Transports publics fribourgeois Holding (TPF) SA,https://emploi.tpf.ch/?page=advertisement_disp...
11,867cd7c2-ce83-48ea-9373-d14f69500fbb,2025-06-30 23:53:37.839000+00:00,Gruppenleiter:in Logistik,Stiftung Brändi,https://www.spitalstellenmarkt.ch/job/gruppenl...
12,cf445a9c-2baa-430f-bc2e-3bad63b6661c,2025-06-30 23:53:13.567000+00:00,Fachfrau/Fachmann Gesundheit im Nachtdienst,TERTIANUM AG,https://www.spitalstellenmarkt.ch/job/fachfrau...
13,ab5b133f-5752-4555-825f-7398e9890e99,2025-06-30 23:53:13.563000+00:00,Mitarbeiter/in Technischer Dienst,TERTIANUM AG,https://www.spitalstellenmarkt.ch/job/mitarbei...
14,b2593db6-605d-4d3c-9015-49944aed04cd,2025-06-30 23:53:01.333000+00:00,"Sozialpädagog*in, Pflegefachperson Psychiatrie...",ikj Stiftung für psychosoziale Integration von...,https://www.schuljobs.ch/job/sozialpaedagogin-...
15,fe9e8e44-f638-4882-b079-6836ffba43be,2025-06-30 23:52:50.951000+00:00,Kaderarzt / Kaderärztin Endokrinologie/ Diabet...,Spital Limmattal,https://www.spitalstellenmarkt.ch/job/kaderarz...
16,3e9a3d47-5be9-4d47-a201-debcd16f1330,2025-06-30 23:52:10.735000+00:00,Teamleitung 90% (m/w/d),Stiftung MBF,https://www.spitalstellenmarkt.ch/job/teamleit...
17,481ebf27-5ba1-44ab-a7f8-59e07bd0397f,2025-06-30 23:50:58.335000+00:00,Kundenberater/in Trustees & Lawyers (m/w/d) -100%,VP Bank AG,https://jobs.vpbank.com/offene-stellen/kundenb...
18,71f8afac-e4a1-41dd-bb8c-f2af26e91ca0,2025-06-30 23:50:58.331000+00:00,(Senior) Compliance Officer (w/m/d) 80-100%,VP Bank AG,https://jobs.vpbank.com/offene-stellen/senior-...
19,24b3b2f5-7ce6-4c95-b958-2a80a4c329d3,2025-06-30 23:33:35.530000+00:00,Lernende:r Kauffrau / Kaufmann EFZ 2026 Genera...,AXA Versicherungen AG,https://jobs.axa.ch/offene-stellen/lernende-r-...

In [22]:
import os, glob, gzip, json, csv
from collections import Counter
from datetime import datetime

# where you downloaded the files
DATA_DIR = os.path.expanduser("~/Downloads/240826_panel_data_with_dg")
PATTERN  = os.path.join(DATA_DIR, "data_*.json.gzip")

files = sorted(glob.glob(PATTERN))
print(f"Found {len(files)} shards under {DATA_DIR}")

def scan_file(path, max_rows=None):
    total = 0
    nulls = 0
    has_dupgroup = False
    with gzip.open(path, "rt", encoding="utf-8") as f:
        for i, line in enumerate(f, 1):
            try:
                rec = json.loads(line)
            except json.JSONDecodeError:
                continue
            total += 1
            if "duplicate_group" in rec:
                has_dupgroup = True
                dg = rec.get("duplicate_group")
                if dg is None or (isinstance(dg, str) and dg.strip() == ""):
                    nulls += 1
            else:
                # treat missing key as NULL
                nulls += 1
            if max_rows and i >= max_rows:
                break
    return total, nulls, has_dupgroup

grand_total = 0
grand_nulls = 0
missing_key_files = []

for p in files:
    t, n, has = scan_file(p)  # full scan; pass max_rows=200_000 for quicker runs
    grand_total += t
    grand_nulls += n
    rate = (n/t*100) if t else 0.0
    if not has:
        missing_key_files.append(os.path.basename(p))
    print(f"{os.path.basename(p):>28}  rows={t:>9,d}  dup_group NULL={n:>9,d} ({rate:5.2f}%)")

overall = (grand_nulls/grand_total*100) if grand_total else 0.0
print("\n=== OVERALL ===")
print(f"Total rows: {grand_total:,}")
print(f"duplicate_group NULL rows: {grand_nulls:,} ({overall:.2f}%)")
print("Any shard missing the 'duplicate_group' key?:", bool(missing_key_files))
if missing_key_files:
    print("Example shards missing the key:", missing_key_files[:5])

Found 187 shards under /Users/bradyallardice/Downloads/240826_panel_data_with_dg
 data_000000000000.json.gzip  rows=   32,123  dup_group NULL=        0 ( 0.00%)
 data_000000000001.json.gzip  rows=   32,062  dup_group NULL=        0 ( 0.00%)
 data_000000000002.json.gzip  rows=   32,168  dup_group NULL=        0 ( 0.00%)
 data_000000000003.json.gzip  rows=   32,104  dup_group NULL=        0 ( 0.00%)
 data_000000000004.json.gzip  rows=   32,066  dup_group NULL=        0 ( 0.00%)
 data_000000000005.json.gzip  rows=   32,043  dup_group NULL=        0 ( 0.00%)
 data_000000000006.json.gzip  rows=   32,463  dup_group NULL=        0 ( 0.00%)
 data_000000000007.json.gzip  rows=   32,036  dup_group NULL=        0 ( 0.00%)
 data_000000000008.json.gzip  rows=   32,434  dup_group NULL=        0 ( 0.00%)
 data_000000000009.json.gzip  rows=   32,222  dup_group NULL=        0 ( 0.00%)
 data_000000000010.json.gzip  rows=   32,293  dup_group NULL=        0 ( 0.00%)
 data_000000000011.json.gzip  rows=   32,024  dup_group NULL=        0 ( 0.00%)
 data_000000000012.json.gzip  rows=   32,009  dup_group NULL=        0 ( 0.00%)
 data_000000000013.json.gzip  rows=   32,091  dup_group NULL=        0 ( 0.00%)
 data_000000000014.json.gzip  rows=   32,119  dup_group NULL=        0 ( 0.00%)
 data_000000000015.json.gzip  rows=   32,018  dup_group NULL=        0 ( 0.00%)
 data_000000000016.json.gzip  rows=   32,027  dup_group NULL=        0 ( 0.00%)
 data_000000000017.json.gzip  rows=   32,079  dup_group NULL=        0 ( 0.00%)
 data_000000000018.json.gzip  rows=   32,059  dup_group NULL=        0 ( 0.00%)
 data_000000000019.json.gzip  rows=   32,341  dup_group NULL=        0 ( 0.00%)
 data_000000000020.json.gzip  rows=   32,486  dup_group NULL=        0 ( 0.00%)
 data_000000000021.json.gzip  rows=   32,165  dup_group NULL=        0 ( 0.00%)
 data_000000000022.json.gzip  rows=   32,206  dup_group NULL=        0 ( 0.00%)
 data_000000000023.json.gzip  rows=   32,224  dup_group NULL=        0 ( 0.00%)
 data_000000000024.json.gzip  rows=   32,229  dup_group NULL=        0 ( 0.00%)
 data_000000000025.json.gzip  rows=   32,305  dup_group NULL=        0 ( 0.00%)
 data_000000000026.json.gzip  rows=   32,290  dup_group NULL=        0 ( 0.00%)
 data_000000000027.json.gzip  rows=   32,171  dup_group NULL=        0 ( 0.00%)
 data_000000000028.json.gzip  rows=   32,146  dup_group NULL=        0 ( 0.00%)
 data_000000000029.json.gzip  rows=   32,049  dup_group NULL=        0 ( 0.00%)
 data_000000000030.json.gzip  rows=   31,787  dup_group NULL=        0 ( 0.00%)
 data_000000000031.json.gzip  rows=   31,854  dup_group NULL=        0 ( 0.00%)
 data_000000000032.json.gzip  rows=   32,155  dup_group NULL=        0 ( 0.00%)
 data_000000000033.json.gzip  rows=   31,690  dup_group NULL=        0 ( 0.00%)
 data_000000000034.json.gzip  rows=   32,200  dup_group NULL=        0 ( 0.00%)
 data_000000000035.json.gzip  rows=   32,033  dup_group NULL=        0 ( 0.00%)
 data_000000000036.json.gzip  rows=   32,073  dup_group NULL=        0 ( 0.00%)
 data_000000000037.json.gzip  rows=   32,211  dup_group NULL=        0 ( 0.00%)
 data_000000000038.json.gzip  rows=   32,144  dup_group NULL=        0 ( 0.00%)
 data_000000000039.json.gzip  rows=   32,116  dup_group NULL=        0 ( 0.00%)
 data_000000000040.json.gzip  rows=   32,179  dup_group NULL=        0 ( 0.00%)
 data_000000000041.json.gzip  rows=   31,971  dup_group NULL=        0 ( 0.00%)
 data_000000000042.json.gzip  rows=   32,093  dup_group NULL=        0 ( 0.00%)
 data_000000000043.json.gzip  rows=   31,937  dup_group NULL=        0 ( 0.00%)
 data_000000000044.json.gzip  rows=   32,175  dup_group NULL=        0 ( 0.00%)
 data_000000000045.json.gzip  rows=   32,257  dup_group NULL=        0 ( 0.00%)
 data_000000000046.json.gzip  rows=   32,039  dup_group NULL=        0 ( 0.00%)
 data_000000000047.json.gzip  rows=   32,038  dup_group NULL=        0 ( 0.00%)
 data_000000000048.json.gzip  rows=   32,111  dup_group NULL=        0 ( 0.00%)
 data_000000000049.json.gzip  rows=   31,908  dup_group NULL=        0 ( 0.00%)
 data_000000000050.json.gzip  rows=   32,066  dup_group NULL=        0 ( 0.00%)
 data_000000000051.json.gzip  rows=   32,150  dup_group NULL=        0 ( 0.00%)
 data_000000000052.json.gzip  rows=   32,429  dup_group NULL=        0 ( 0.00%)
 data_000000000053.json.gzip  rows=   32,111  dup_group NULL=        0 ( 0.00%)
 data_000000000054.json.gzip  rows=   31,890  dup_group NULL=        0 ( 0.00%)
 data_000000000055.json.gzip  rows=   32,145  dup_group NULL=        0 ( 0.00%)
 data_000000000056.json.gzip  rows=   32,214  dup_group NULL=        0 ( 0.00%)
 data_000000000057.json.gzip  rows=   32,226  dup_group NULL=        0 ( 0.00%)
 data_000000000058.json.gzip  rows=   32,156  dup_group NULL=        0 ( 0.00%)
 data_000000000059.json.gzip  rows=   32,182  dup_group NULL=        0 ( 0.00%)
 data_000000000060.json.gzip  rows=   32,083  dup_group NULL=        0 ( 0.00%)
 data_000000000061.json.gzip  rows=   32,312  dup_group NULL=        0 ( 0.00%)
 data_000000000062.json.gzip  rows=   31,985  dup_group NULL=        0 ( 0.00%)
 data_000000000063.json.gzip  rows=   31,896  dup_group NULL=        0 ( 0.00%)
 data_000000000064.json.gzip  rows=   32,028  dup_group NULL=        0 ( 0.00%)
 data_000000000065.json.gzip  rows=   31,796  dup_group NULL=        0 ( 0.00%)
 data_000000000066.json.gzip  rows=   31,844  dup_group NULL=        0 ( 0.00%)
 data_000000000067.json.gzip  rows=   32,122  dup_group NULL=        0 ( 0.00%)
 data_000000000068.json.gzip  rows=   32,099  dup_group NULL=        0 ( 0.00%)
 data_000000000069.json.gzip  rows=   32,270  dup_group NULL=        0 ( 0.00%)
 data_000000000070.json.gzip  rows=   32,097  dup_group NULL=        0 ( 0.00%)
 data_000000000071.json.gzip  rows=   31,939  dup_group NULL=        0 ( 0.00%)
 data_000000000072.json.gzip  rows=   32,343  dup_group NULL=        0 ( 0.00%)
 data_000000000073.json.gzip  rows=   32,199  dup_group NULL=        0 ( 0.00%)
 data_000000000074.json.gzip  rows=   32,071  dup_group NULL=        0 ( 0.00%)
 data_000000000075.json.gzip  rows=   32,048  dup_group NULL=        0 ( 0.00%)
 data_000000000076.json.gzip  rows=   32,225  dup_group NULL=        0 ( 0.00%)
 data_000000000077.json.gzip  rows=   32,289  dup_group NULL=        0 ( 0.00%)
 data_000000000078.json.gzip  rows=   31,984  dup_group NULL=        0 ( 0.00%)
 data_000000000079.json.gzip  rows=   32,066  dup_group NULL=        0 ( 0.00%)
 data_000000000080.json.gzip  rows=   32,299  dup_group NULL=        0 ( 0.00%)
 data_000000000081.json.gzip  rows=   31,741  dup_group NULL=        0 ( 0.00%)
 data_000000000082.json.gzip  rows=   32,235  dup_group NULL=        0 ( 0.00%)
 data_000000000083.json.gzip  rows=   31,789  dup_group NULL=        0 ( 0.00%)
 data_000000000084.json.gzip  rows=   32,371  dup_group NULL=        0 ( 0.00%)
 data_000000000085.json.gzip  rows=   31,575  dup_group NULL=        0 ( 0.00%)
 data_000000000086.json.gzip  rows=   32,439  dup_group NULL=        0 ( 0.00%)
 data_000000000087.json.gzip  rows=   32,042  dup_group NULL=        0 ( 0.00%)
 data_000000000088.json.gzip  rows=   32,111  dup_group NULL=        0 ( 0.00%)
 data_000000000089.json.gzip  rows=   32,256  dup_group NULL=        0 ( 0.00%)
 data_000000000090.json.gzip  rows=   32,260  dup_group NULL=        0 ( 0.00%)
 data_000000000091.json.gzip  rows=   31,975  dup_group NULL=        0 ( 0.00%)
 data_000000000092.json.gzip  rows=   32,306  dup_group NULL=        0 ( 0.00%)
 data_000000000093.json.gzip  rows=   32,211  dup_group NULL=        0 ( 0.00%)
 data_000000000094.json.gzip  rows=   32,082  dup_group NULL=        0 ( 0.00%)
 data_000000000095.json.gzip  rows=   32,345  dup_group NULL=        0 ( 0.00%)
 data_000000000096.json.gzip  rows=   31,960  dup_group NULL=        0 ( 0.00%)
 data_000000000097.json.gzip  rows=   32,185  dup_group NULL=        0 ( 0.00%)
 data_000000000098.json.gzip  rows=   32,050  dup_group NULL=        0 ( 0.00%)
 data_000000000099.json.gzip  rows=   32,028  dup_group NULL=        0 ( 0.00%)
 data_000000000100.json.gzip  rows=   32,489  dup_group NULL=        0 ( 0.00%)
 data_000000000101.json.gzip  rows=   32,323  dup_group NULL=        0 ( 0.00%)
 data_000000000102.json.gzip  rows=   32,457  dup_group NULL=        0 ( 0.00%)
 data_000000000103.json.gzip  rows=   32,171  dup_group NULL=        0 ( 0.00%)
 data_000000000104.json.gzip  rows=   32,298  dup_group NULL=        0 ( 0.00%)
 data_000000000105.json.gzip  rows=   32,150  dup_group NULL=        0 ( 0.00%)
 data_000000000106.json.gzip  rows=   32,044  dup_group NULL=        0 ( 0.00%)
 data_000000000107.json.gzip  rows=   32,317  dup_group NULL=        0 ( 0.00%)
 data_000000000108.json.gzip  rows=   31,891  dup_group NULL=        0 ( 0.00%)
 data_000000000109.json.gzip  rows=   31,956  dup_group NULL=        0 ( 0.00%)
 data_000000000110.json.gzip  rows=   32,048  dup_group NULL=        0 ( 0.00%)
 data_000000000111.json.gzip  rows=   31,960  dup_group NULL=        0 ( 0.00%)
 data_000000000112.json.gzip  rows=   31,951  dup_group NULL=        0 ( 0.00%)
 data_000000000113.json.gzip  rows=   32,021  dup_group NULL=        0 ( 0.00%)
 data_000000000114.json.gzip  rows=   32,394  dup_group NULL=        0 ( 0.00%)
 data_000000000115.json.gzip  rows=   32,151  dup_group NULL=        0 ( 0.00%)
 data_000000000116.json.gzip  rows=   32,043  dup_group NULL=        0 ( 0.00%)
 data_000000000117.json.gzip  rows=   32,034  dup_group NULL=        0 ( 0.00%)
 data_000000000118.json.gzip  rows=   31,770  dup_group NULL=        0 ( 0.00%)
 data_000000000119.json.gzip  rows=   32,266  dup_group NULL=        0 ( 0.00%)
 data_000000000120.json.gzip  rows=   32,128  dup_group NULL=        0 ( 0.00%)
 data_000000000121.json.gzip  rows=   31,877  dup_group NULL=        0 ( 0.00%)
 data_000000000122.json.gzip  rows=   32,024  dup_group NULL=        0 ( 0.00%)
 data_000000000123.json.gzip  rows=   32,208  dup_group NULL=        0 ( 0.00%)
 data_000000000124.json.gzip  rows=   32,342  dup_group NULL=        0 ( 0.00%)
 data_000000000125.json.gzip  rows=   32,090  dup_group NULL=        0 ( 0.00%)
 data_000000000126.json.gzip  rows=   32,285  dup_group NULL=        0 ( 0.00%)
 data_000000000127.json.gzip  rows=   32,191  dup_group NULL=        0 ( 0.00%)
 data_000000000128.json.gzip  rows=   32,164  dup_group NULL=        0 ( 0.00%)
 data_000000000129.json.gzip  rows=   31,942  dup_group NULL=        0 ( 0.00%)
 data_000000000130.json.gzip  rows=   32,106  dup_group NULL=        0 ( 0.00%)
 data_000000000131.json.gzip  rows=   32,092  dup_group NULL=        0 ( 0.00%)
 data_000000000132.json.gzip  rows=   32,015  dup_group NULL=        0 ( 0.00%)
 data_000000000133.json.gzip  rows=   31,828  dup_group NULL=        0 ( 0.00%)
 data_000000000134.json.gzip  rows=   32,392  dup_group NULL=        0 ( 0.00%)
 data_000000000135.json.gzip  rows=   32,529  dup_group NULL=        0 ( 0.00%)
 data_000000000136.json.gzip  rows=   32,024  dup_group NULL=        0 ( 0.00%)
 data_000000000137.json.gzip  rows=   32,291  dup_group NULL=        0 ( 0.00%)
 data_000000000138.json.gzip  rows=   31,839  dup_group NULL=        0 ( 0.00%)
 data_000000000139.json.gzip  rows=   32,095  dup_group NULL=        0 ( 0.00%)
 data_000000000140.json.gzip  rows=   32,355  dup_group NULL=        0 ( 0.00%)
 data_000000000141.json.gzip  rows=   31,963  dup_group NULL=        0 ( 0.00%)
 data_000000000142.json.gzip  rows=   32,249  dup_group NULL=        0 ( 0.00%)
 data_000000000143.json.gzip  rows=   32,037  dup_group NULL=        0 ( 0.00%)
 data_000000000144.json.gzip  rows=   32,147  dup_group NULL=        0 ( 0.00%)
 data_000000000145.json.gzip  rows=   32,367  dup_group NULL=        0 ( 0.00%)
 data_000000000146.json.gzip  rows=   31,921  dup_group NULL=        0 ( 0.00%)
 data_000000000147.json.gzip  rows=   32,064  dup_group NULL=        0 ( 0.00%)
 data_000000000148.json.gzip  rows=   32,274  dup_group NULL=        0 ( 0.00%)
 data_000000000149.json.gzip  rows=   31,971  dup_group NULL=        0 ( 0.00%)
 data_000000000150.json.gzip  rows=   32,253  dup_group NULL=        0 ( 0.00%)
 data_000000000151.json.gzip  rows=   32,058  dup_group NULL=        0 ( 0.00%)
 data_000000000152.json.gzip  rows=   32,079  dup_group NULL=        0 ( 0.00%)
 data_000000000153.json.gzip  rows=   31,906  dup_group NULL=        0 ( 0.00%)
 data_000000000154.json.gzip  rows=   31,794  dup_group NULL=        0 ( 0.00%)
 data_000000000155.json.gzip  rows=   32,007  dup_group NULL=        0 ( 0.00%)
 data_000000000156.json.gzip  rows=   32,302  dup_group NULL=        0 ( 0.00%)
 data_000000000157.json.gzip  rows=   32,016  dup_group NULL=        0 ( 0.00%)
 data_000000000158.json.gzip  rows=   32,220  dup_group NULL=        0 ( 0.00%)
 data_000000000159.json.gzip  rows=   32,421  dup_group NULL=        0 ( 0.00%)
 data_000000000160.json.gzip  rows=   32,170  dup_group NULL=        0 ( 0.00%)
 data_000000000161.json.gzip  rows=   31,895  dup_group NULL=        0 ( 0.00%)
 data_000000000162.json.gzip  rows=   32,319  dup_group NULL=        0 ( 0.00%)
 data_000000000163.json.gzip  rows=   31,897  dup_group NULL=        0 ( 0.00%)
 data_000000000164.json.gzip  rows=   31,967  dup_group NULL=        0 ( 0.00%)
 data_000000000165.json.gzip  rows=   31,734  dup_group NULL=        0 ( 0.00%)
 data_000000000166.json.gzip  rows=   32,156  dup_group NULL=        0 ( 0.00%)
 data_000000000167.json.gzip  rows=   32,185  dup_group NULL=        0 ( 0.00%)
 data_000000000168.json.gzip  rows=   32,130  dup_group NULL=        0 ( 0.00%)
 data_000000000169.json.gzip  rows=   32,209  dup_group NULL=        0 ( 0.00%)
 data_000000000170.json.gzip  rows=   32,470  dup_group NULL=        0 ( 0.00%)
 data_000000000171.json.gzip  rows=   32,453  dup_group NULL=        0 ( 0.00%)
 data_000000000172.json.gzip  rows=   31,947  dup_group NULL=        0 ( 0.00%)
 data_000000000173.json.gzip  rows=   32,232  dup_group NULL=        0 ( 0.00%)
 data_000000000174.json.gzip  rows=   32,435  dup_group NULL=        0 ( 0.00%)
 data_000000000175.json.gzip  rows=   31,966  dup_group NULL=        0 ( 0.00%)
 data_000000000176.json.gzip  rows=   31,978  dup_group NULL=        0 ( 0.00%)
 data_000000000177.json.gzip  rows=   31,802  dup_group NULL=        0 ( 0.00%)
 data_000000000178.json.gzip  rows=   32,076  dup_group NULL=        0 ( 0.00%)
 data_000000000179.json.gzip  rows=   32,021  dup_group NULL=        0 ( 0.00%)
 data_000000000180.json.gzip  rows=   31,997  dup_group NULL=        0 ( 0.00%)
 data_000000000181.json.gzip  rows=   32,339  dup_group NULL=        0 ( 0.00%)
 data_000000000182.json.gzip  rows=   32,199  dup_group NULL=        0 ( 0.00%)
 data_000000000183.json.gzip  rows=   31,709  dup_group NULL=        0 ( 0.00%)
 data_000000000184.json.gzip  rows=   32,296  dup_group NULL=        0 ( 0.00%)
 data_000000000185.json.gzip  rows=   32,171  dup_group NULL=        0 ( 0.00%)
 data_000000000186.json.gzip  rows=   32,214  dup_group NULL=        0 ( 0.00%)

=== OVERALL ===
Total rows: 6,006,115
duplicate_group NULL rows: 0 (0.00%)
Any shard missing the 'duplicate_group' key?: False

In [24]:
import os, gzip, json, sqlite3, glob, itertools, hashlib
from datetime import datetime

# ============================
# CONFIG — EDIT THESE PATHS
# ============================
# Existing (“already downloaded”) files used to build the UID index
EXISTING_GLOB = os.path.expanduser("~/Downloads/240826_panel_data_with_dg/*.json.gzip")
# New files to check (e.g., 230907_export_export000000000003.gzip etc.)
NEW_GLOB = os.path.expanduser("~/Downloads/230907_export_export*.gzip")

# Field name candidates
UID_CANDS = ["uid", "job_uid", "id"]
DATE_CANDS = ["tst_created", "created_at", "published_at", "date"]
DUPG_CANDS = ["duplicate_group", "duplicateGroup"]

# SQLite index file (created if missing; safe to delete afterwards)
UID_DB = os.path.expanduser("~/uid_index.sqlite")

# Sampling for pretty head output
RAW_HEAD_LINES = 3     # raw text lines to show per file
PARSED_HEAD_OBJS = 3   # how many parsed objects to print per file

# ============================
# Helpers
# ============================
def detect_format(path):
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        sample = f.read(4096)
    s = sample.lstrip()
    if s.startswith('['):
        return "json_array"
    if s.startswith('{') or "\n{" in sample:
        return "ndjson"
    return "unknown"

def iter_ndjson(path):
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line: 
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue

def iter_json_array(path):
    # lightweight streaming of a gzip'd JSON array
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        # move to '['
        ch = f.read(1)
        while ch and ch.isspace():
            ch = f.read(1)
        if ch != '[':
            return
        buf = []
        depth = 0
        in_str = False
        esc = False
        # read after '['
        while True:
            ch = f.read(1)
            if not ch:
                return
            if in_str:
                buf.append(ch)
                if esc:
                    esc = False
                elif ch == '\\':
                    esc = True
                elif ch == '"':
                    in_str = False
                continue
            if ch.isspace() or ch == ',':
                continue
            if ch == ']':
                return
            if ch == '{':
                buf = ['{']
                depth = 1
                in_str = False
                esc = False
                while True:
                    ch = f.read(1)
                    if not ch:
                        return
                    buf.append(ch)
                    if in_str:
                        if esc:
                            esc = False
                        elif ch == '\\':
                            esc = True
                        elif ch == '"':
                            in_str = False
                    else:
                        if ch == '"':
                            in_str = True
                        elif ch == '{':
                            depth += 1
                        elif ch == '}':
                            depth -= 1
                            if depth == 0:
                                try:
                                    yield json.loads("".join(buf))
                                except Exception:
                                    pass
                                break

def iter_records(path):
    fmt = detect_format(path)
    if fmt == "ndjson":
        return iter_ndjson(path)
    elif fmt == "json_array":
        return iter_json_array(path)
    else:
        # best effort: try ndjson
        return iter_ndjson(path)

def pick_field(obj, cands):
    for c in cands:
        if c in obj:
            return c
    return None

def parse_dt(s):
    if s is None:
        return None
    if not isinstance(s, str):
        s = str(s)
    try:
        return datetime.fromisoformat(s.replace('Z', '+00:00'))
    except Exception:
        return None

def print_raw_head(path, n=RAW_HEAD_LINES):
    print(f"\n--- raw head of {os.path.basename(path)} ({n} lines) ---")
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        for i, line in zip(range(1, n+1), f):
            print(f"{i:>3}: {line.rstrip()[:300]}")

# ============================
# Build UID index (SQLite)
# ============================
def make_uid_index(db_path):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.execute("PRAGMA journal_mode=WAL;")
    cur.execute("PRAGMA synchronous=OFF;")
    cur.execute("""
        CREATE TABLE IF NOT EXISTS uids (
            uid TEXT PRIMARY KEY,
            src TEXT
        );
    """)
    cur.execute("CREATE INDEX IF NOT EXISTS idx_src ON uids(src);")
    conn.commit()
    return conn

def add_file_to_index(conn, path, uid_field=None):
    cur = conn.cursor()
    inserted = 0
    batch = []
    # print head for usability
    print_raw_head(path)
    # parse a few objects to pick fields
    test_records = []
    for i, obj in enumerate(iter_records(path)):
        test_records.append(obj)
        if i >= PARSED_HEAD_OBJS - 1:
            break
    if not test_records:
        print(f"(!) No records found in {os.path.basename(path)}")
        return 0, None, None, uid_field

    if uid_field is None:
        uid_field = pick_field(test_records[0], UID_CANDS)
    date_field = pick_field(test_records[0], DATE_CANDS)
    dup_field  = pick_field(test_records[0], DUPG_CANDS)

    print(f"Detected fields → uid: {uid_field}, date: {date_field}, duplicate_group: {dup_field}")
    print("--- parsed head ---")
    for j, t in enumerate(test_records, 1):
        print(f"{j:>3}: ", {k: t.get(k) for k in [uid_field, date_field, dup_field, "title", "company_name"] if k})

    # now stream all to index uids and compute date range + dup stats
    total = 0
    null_dup = 0
    dt_min = None
    dt_max = None

    def flush():
        nonlocal batch, inserted
        if not batch:
            return
        cur.executemany("INSERT OR IGNORE INTO uids(uid, src) VALUES (?, ?);", batch)
        conn.commit()
        inserted += cur.rowcount if cur.rowcount is not None else 0
        batch = []

    # include the head ones first
    for obj in test_records:
        total += 1
        uid = obj.get(uid_field)
        if uid:
            batch.append((str(uid), os.path.basename(path)))
        if date_field:
            dt = parse_dt(obj.get(date_field))
            if dt:
                dt_min = dt if dt_min is None else min(dt_min, dt)
                dt_max = dt if dt_max is None else max(dt_max, dt)
        if dup_field:
            dg = obj.get(dup_field)
            if dg is None or (isinstance(dg, str) and dg.strip() == ""):
                null_dup += 1
    flush()

    # continue streaming the rest (skip the number we already consumed)
    consumed = len(test_records)
    for i, obj in enumerate(itertools.islice(iter_records(path), consumed, None), start=consumed+1):
        total += 1
        if uid_field:
            uid = obj.get(uid_field)
            if uid:
                batch.append((str(uid), os.path.basename(path)))
        if date_field:
            dt = parse_dt(obj.get(date_field))
            if dt:
                dt_min = dt if dt_min is None else min(dt_min, dt)
                dt_max = dt if dt_max is None else max(dt_max, dt)
        if dup_field:
            dg = obj.get(dup_field)
            if dg is None or (isinstance(dg, str) and dg.strip() == ""):
                null_dup += 1
        if len(batch) >= 20_000:
            flush()
    flush()

    null_rate = (null_dup / total * 100) if total else 0.0
    print(f"Indexed {inserted:,} new uids from {os.path.basename(path)} | rows seen: {total:,} | "
          f"duplicate_group NULL/empty: {null_dup:,} ({null_rate:.2f}%)")
    if dt_min and dt_max:
        print(f"Date range: {dt_min} → {dt_max}")
    return inserted, dt_min, dt_max, uid_field

# ============================
# Overlap test for NEW files
# ============================
def overlap_check(conn, path, uid_field_hint=None):
    cur = conn.cursor()
    fmt = detect_format(path)
    # pick fields using first object
    it = iter_records(path)
    try:
        first = next(it)
    except StopIteration:
        print(f"(!) No records in {os.path.basename(path)}")
        return
    uid_field = uid_field_hint or pick_field(first, UID_CANDS)
    date_field = pick_field(first, DATE_CANDS)

    # print a tiny head
    print_raw_head(path)
    print("--- parsed head ---")
    print({k: first.get(k) for k in [uid_field, date_field, "duplicate_group", "title", "company_name"] if k})

    total = 0
    in_idx = 0
    not_in_idx = 0
    dt_min = parse_dt(first.get(date_field)) if date_field else None
    dt_max = dt_min

    # include the first record
    if uid_field and first.get(uid_field):
        uid = str(first.get(uid_field))
        row = cur.execute("SELECT 1 FROM uids WHERE uid = ? LIMIT 1;", (uid,)).fetchone()
        if row: in_idx += 1
        else:   not_in_idx += 1
        total += 1

    # stream the rest
    for obj in it:
        total += 1
        if uid_field and obj.get(uid_field):
            uid = str(obj.get(uid_field))
            row = cur.execute("SELECT 1 FROM uids WHERE uid = ? LIMIT 1;", (uid,)).fetchone()
            if row: in_idx += 1
            else:   not_in_idx += 1
        if date_field:
            dt = parse_dt(obj.get(date_field))
            if dt:
                dt_min = dt if dt_min is None else min(dt_min, dt)
                dt_max = dt if dt_max is None else max(dt_max, dt)

    pct_in = (in_idx/total*100) if total else 0.0
    print(f"\nOverlap for {os.path.basename(path)}")
    print(f"  total rows:     {total:,}")
    print(f"  in EXISTING:    {in_idx:,} ({pct_in:.2f}%)")
    print(f"  not in EXISTING:{not_in_idx:,} ({100-pct_in:.2f}%)")
    if dt_min and dt_max:
        print(f"  date range:     {dt_min} → {dt_max}")

# ============================
# Run: build index from EXISTING, then check NEW
# ============================
existing_files = sorted(glob.glob(EXISTING_GLOB))
new_files      = sorted(glob.glob(NEW_GLOB))

print(f"Found {len(existing_files)} EXISTING files")
print(f"Found {len(new_files)} NEW files")

if not existing_files:
    raise SystemExit("No EXISTING files matched. Edit EXISTING_GLOB.")

conn = make_uid_index(UID_DB)

# Build UID index (once). If you already created it earlier, you can skip this loop.
seen_uid_field = None
all_dt_min = None
all_dt_max = None
for fp in existing_files:
    added, dmin, dmax, seen_uid_field = add_file_to_index(conn, fp, uid_field=seen_uid_field)
    if dmin and dmax:
        all_dt_min = dmin if all_dt_min is None else min(all_dt_min, dmin)
        all_dt_max = dmax if all_dt_max is None else max(all_dt_max, dmax)

# How big is the index?
cur = conn.cursor()
count_index = cur.execute("SELECT COUNT(*) FROM uids;").fetchone()[0]
print(f"\nUID index size: {count_index:,} unique uids")
if all_dt_min and all_dt_max:
    print(f"EXISTING overall date range: {all_dt_min} → {all_dt_max}")

# Check each NEW file for overlap + its own date range & head
for fp in new_files:
    overlap_check(conn, fp, uid_field_hint=seen_uid_field)

# Close when done
conn.close()
print("\nDone.")

Found 187 EXISTING files
Found 1 NEW files

--- raw head of data_000000000000.json.gzip (3 lines) ---
  1: {"duplicate_group":"a9a52233-e553-4de0-a6c4-fb191056d266","title":"Fachspezialisten Land- und Forstwirtschaft (w/m/d) 80% - 100%","url":"https://www.ors-jobs.com/de-CH/Jobs/Schweiz/Bern-und-Region/Fachspezialisten-Land-und-Forstwirtschaft-w-m-d","content_clean":"Pensum: 80% - 100%\nArbeitsort: Emmen
  2: {"duplicate_group":"3342be6a-7da2-4324-b11d-00dca12e24d9","title":"Asylkoordinator bzw. stellvertretender Wohnheimleiter w/m","url":"http://www.ors-jobs.com/de-CH/Jobs/-in-der-Schweiz/Basel-und-Region/Asylkoordinator-bzw-stellvertretender-Wohnheimlei","content_clean":"Asylkoordinator bzw. stellvertr
  3: {"duplicate_group":"2c6dfccc-bb33-488e-b177-c5629961057d","title":"Audit Senior Asset Management/Banking (Liechtenstein \u0026 St. Gallen)","url":"https://direktlink.prospective.ch/?view=48014829-bc99-49a4-a861-c1bb8444f12d","content_clean":"","company_id":"40002024","company_name":"PwC","company_si
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2020-04-19 22:44:37.096 UTC', 'duplicate_group': 'a9a52233-e553-4de0-a6c4-fb191056d266', 'title': 'Fachspezialisten Land- und Forstwirtschaft (w/m/d) 80% - 100%', 'company_name': 'ORS'}
  2:  {'tst_created': '2016-02-03 20:00:05 UTC', 'duplicate_group': '3342be6a-7da2-4324-b11d-00dca12e24d9', 'title': 'Asylkoordinator bzw. stellvertretender Wohnheimleiter w/m', 'company_name': 'ORS'}
  3:  {'tst_created': '2018-08-02 11:00:28.748 UTC', 'duplicate_group': '2c6dfccc-bb33-488e-b177-c5629961057d', 'title': 'Audit Senior Asset Management/Banking (Liechtenstein & St. Gallen)', 'company_name': 'PwC'}
Indexed 0 new uids from data_000000000000.json.gzip | rows seen: 32,123 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000001.json.gzip (3 lines) ---
  1: {"duplicate_group":"87995706-6ba6-4811-923b-7dc5abc6d6af","title":"Mitarbeiter*in Betreuung 60 - 100% befristet mit Option auf Verlängerung","url":"https://kombi.jobs.ch/basic_kombi/display.php?aid=7e3ba50b-3b37-4e4b-b6cc-460c89999c85\u0026slim=clean","content_clean":"Mitarbeiter*in Betreuung 60 - 1
  2: {"duplicate_group":"90752c77-c2b0-4fbe-a17a-c4a02e249032","title":"Mitarbeiter*in Nachtbetreuung 60-80% / befristet für 3 bis 6 Monate 60 - 80%","url":"https://www.ors-jobs.com/de-CH/Jobs/Schweiz/Jobs-zur-Fluchtlingsbetreuung-Ukraine/Mitarbeiter-in-Nachtbetreuung-60-80-befristet-f","content_clean":"
  3: {"duplicate_group":"0ec0bef6-6fd7-4bff-b6bb-aaca0b87d8e1","title":"Audit Senior in Trade, Industry and Services (Liechtenstein)","url":"https://www.pwc.ch/ch/de/karriere-bei-pwc/stellensuche/beschreibung.html?wdjobreqid=124995WD\u0026wdjobsite=Global_Experienced_Careers\u0026wdjd=simple","content_cl
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2023-05-31 15:33:24.116 UTC', 'duplicate_group': '87995706-6ba6-4811-923b-7dc5abc6d6af', 'title': 'Mitarbeiter*in Betreuung 60 - 100% befristet mit Option auf Verlängerung', 'company_name': 'ORS'}
  2:  {'tst_created': '2022-03-03 11:32:28.638 UTC', 'duplicate_group': '90752c77-c2b0-4fbe-a17a-c4a02e249032', 'title': 'Mitarbeiter*in Nachtbetreuung 60-80% / befristet für 3 bis 6 Monate 60 - 80%', 'company_name': 'ORS'}
  3:  {'tst_created': '2020-01-30 17:55:13.392 UTC', 'duplicate_group': '0ec0bef6-6fd7-4bff-b6bb-aaca0b87d8e1', 'title': 'Audit Senior in Trade, Industry and Services (Liechtenstein)', 'company_name': 'PwC'}
Indexed 0 new uids from data_000000000001.json.gzip | rows seen: 32,062 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000002.json.gzip (3 lines) ---
  1: {"duplicate_group":"8363e81c-555c-4f73-b14d-baee0ab69f9b","title":"Pflegefachfrau/mann HF Betreuung","url":"http://www.ors-jobs.com/de-CH/Jobs/-in-der-Schweiz/Basel-und-Region/Pflegefachfrau-mann-HF-Betreuung","content_clean":"Pflegefachfrau/mann HF Betreuung\n\n(Pensum 70 - 100%) \nArbeitsort Pratt
  2: {"duplicate_group":"4e950d8b-546d-4372-840b-28c0f1a835d1","title":"Lehrperson Deutsch im Integrationsbereich (w/m/d) 100% oder 50% 50% - 100%","url":"https://www.ors-jobs.com/de-CH/Jobs/Schweiz/Bern-und-Region/Lehrperson-Deutsch-im-Integrationsbereich-w-m-d","content_clean":"Pensum: 50% - 100%\nArbe
  3: {"duplicate_group":"5ad2a971-b1c0-42b2-b33a-f355445a5509","title":"Audit Manager (Trade, Industries and Services)","url":"https://jobs.pwc.ch/offene-stellen/audit-manager-trade-industries-and-services/fa86209b-628c-4555-87b2-45e576edebed","content_clean":"Your tasks\n·         You will manage the ma
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2015-11-29 23:01:05 UTC', 'duplicate_group': '8363e81c-555c-4f73-b14d-baee0ab69f9b', 'title': 'Pflegefachfrau/mann HF Betreuung', 'company_name': 'ORS'}
  2:  {'tst_created': '2021-01-27 12:40:05.652 UTC', 'duplicate_group': '4e950d8b-546d-4372-840b-28c0f1a835d1', 'title': 'Lehrperson Deutsch im Integrationsbereich (w/m/d) 100% oder 50% 50% - 100%', 'company_name': 'ORS'}
  3:  {'tst_created': '2021-11-03 02:46:14.82 UTC', 'duplicate_group': '5ad2a971-b1c0-42b2-b33a-f355445a5509', 'title': 'Audit Manager (Trade, Industries and Services)', 'company_name': 'PwC'}
Indexed 0 new uids from data_000000000002.json.gzip | rows seen: 32,168 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000003.json.gzip (3 lines) ---
  1: {"duplicate_group":"1b28a630-e607-4d32-b2b1-bb40a19f3ab2","title":"infermiera-e","url":"https://www.job-room.ch/job-search/job-fingerprint-redirect?externalId=598fb7c14b629425f76d4839819bc79c6d260354bb778e0b84b6d6e0cbec5f8d71d0518d7c0dda99","content_clean":"Il Datore di lavoro è alla ricerca di un/a
  2: {"duplicate_group":"1af4433e-644c-48b4-9d8a-0f910089a640","title":"Lehrperson Deutsch im Integrationsbereich 60% - 100% (befristet) 60% - 100%","url":"https://www.ors-jobs.com/de-CH/Jobs/Schweiz/Bern-und-Region/Lehrperson-Deutsch-im-Integrationsbereich-60-10","content_clean":"Pensum: 60% - 100%\nArb
  3: {"duplicate_group":"cd720246-1296-492b-b651-33a6cb0c9cb9","title":"Transfer Pricing \u0026 Value Chain Transformation Consultant","url":"https://jobs.pwc.ch/offene-stellen/transfer-pricing-value-chain-transformation-consultant/c9597de8-ca14-4a3a-9719-824c82d4616c","content_clean":"Deine Aufgaben\nDu
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2019-06-20 10:16:42.533 UTC', 'duplicate_group': '1b28a630-e607-4d32-b2b1-bb40a19f3ab2', 'title': 'infermiera-e', 'company_name': 'ORS'}
  2:  {'tst_created': '2021-06-03 08:31:23.67 UTC', 'duplicate_group': '1af4433e-644c-48b4-9d8a-0f910089a640', 'title': 'Lehrperson Deutsch im Integrationsbereich 60% - 100% (befristet) 60% - 100%', 'company_name': 'ORS'}
  3:  {'tst_created': '2021-10-15 12:55:29.021 UTC', 'duplicate_group': 'cd720246-1296-492b-b651-33a6cb0c9cb9', 'title': 'Transfer Pricing & Value Chain Transformation Consultant', 'company_name': 'PwC'}
Indexed 0 new uids from data_000000000003.json.gzip | rows seen: 32,104 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000004.json.gzip (3 lines) ---
  1: {"duplicate_group":"6cc2e4a1-4931-44ca-a73b-14ce6af3f9c5","title":"Mitarbeiter/in Betreuung","url":"http://www.ors-jobs.com/de-CH/Jobs/-in-der-Schweiz/Obwalden-und-Region/Mitarbeiter-in-Betreuung-1","content_clean":"Mitarbeiter/in Betreuung\n\nPensum:100%\nArbeitsort: Glaubenberg\nArbeitsbeginn: per
  2: {"duplicate_group":"04a5e3e8-14d4-4820-996b-ee31f12902d8","title":"MS365 SharePoint Online Administrator","url":"https://jobs.pwc.ch/offene-stellen/ms365-sharepoint-online-administrator/357580a1-5eb4-451c-8f56-2628a9284455","content_clean":"Your tasks\n\nYou are part of our Communication and Collabo
  3: {"duplicate_group":"e3bdc673-26ce-41e6-a5a3-52049b3670f3","title":"Audit - Senior Associate / Assistant Manager - Insurance - 60-100%","url":"https://jobs.pwc.ch/offene-stellen/audit-senior-associate-assistant-manager-insurance/e573b099-97c1-42e1-8663-19770d2c8529","content_clean":"Audit - Senior As
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2016-08-08 14:46:03 UTC', 'duplicate_group': '6cc2e4a1-4931-44ca-a73b-14ce6af3f9c5', 'title': 'Mitarbeiter/in Betreuung', 'company_name': 'ORS'}
  2:  {'tst_created': '2021-02-04 11:30:09.095 UTC', 'duplicate_group': '04a5e3e8-14d4-4820-996b-ee31f12902d8', 'title': 'MS365 SharePoint Online Administrator', 'company_name': 'PwC'}
  3:  {'tst_created': '2023-02-20 20:39:10.084 UTC', 'duplicate_group': 'e3bdc673-26ce-41e6-a5a3-52049b3670f3', 'title': 'Audit - Senior Associate / Assistant Manager - Insurance - 60-100%', 'company_name': 'PwC'}
Indexed 0 new uids from data_000000000004.json.gzip | rows seen: 32,066 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000005.json.gzip (3 lines) ---
  1: {"duplicate_group":"6b1fddb4-7fde-40e7-b2a7-a2c983ef2afe","title":"Spontanbewerbung Betreuungsfunktion","url":"https://kombi.jobs.ch/basic_kombi/display.php?aid=214a282b-96e5-4e62-8e4f-bf16e8647018\u0026slim=clean","content_clean":"Spontanbewerbung Betreuungsfunktion\n\nWir suchen Teamplayer, die mi
  2: {"duplicate_group":"59eed7dc-3188-4a2e-82ef-c36cbddbee97","title":"Mitarbeiter*in Betreuung 80% 80%","url":"https://www.ors-jobs.com/de-CH/Jobs/Schweiz/Bern-und-Region/Mitarbeiter-in-Betreuung-80","content_clean":"Pensum: 80%\nArbeitsort: Langnau i. E.\nArbeitsbeginn: per sofort oder nach Vereinbaru
  3: {"duplicate_group":"febfe9fb-e574-4e2d-8e85-1f71c9560173","title":"Nacht- und Wochenendbetreuer*in 60% 60%","url":"https://www.ors-jobs.com/de-CH/Jobs/Schweiz/Bern-und-Region/Nacht-und-Wochenendbetreuer-in-60","content_clean":"Pensum: 60%\nArbeitsort: Langnau i. E. (BE)\nArbeitsbeginn: per sofort od
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2023-04-27 21:48:13.598 UTC', 'duplicate_group': '6b1fddb4-7fde-40e7-b2a7-a2c983ef2afe', 'title': 'Spontanbewerbung Betreuungsfunktion', 'company_name': 'ORS'}
  2:  {'tst_created': '2022-03-15 19:52:06.492 UTC', 'duplicate_group': '59eed7dc-3188-4a2e-82ef-c36cbddbee97', 'title': 'Mitarbeiter*in Betreuung 80% 80%', 'company_name': 'ORS'}
  3:  {'tst_created': '2023-03-30 08:57:54.313 UTC', 'duplicate_group': 'febfe9fb-e574-4e2d-8e85-1f71c9560173', 'title': 'Nacht- und Wochenendbetreuer*in 60% 60%', 'company_name': 'ORS'}
Indexed 0 new uids from data_000000000005.json.gzip | rows seen: 32,043 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000006.json.gzip (3 lines) ---
  1: {"duplicate_group":"07fda355-c509-41f8-9286-ace447dd30b8","title":"Desktop Support Specialist, Zug, Switzerland","url":"http://xerox.jobs/virtual-che/desktop-support-specialist-zug-switzerland/E4F190B4A83F4AB08F7520962A4B8B32/job/","content_clean":"/Xerox Corporation is a $22 billion leading global
  2: {"duplicate_group":"3a5c6ab3-f436-4e67-9502-89f646261c2e","title":"Restaurantfachfrau / Restaurantfachmann","url":"http://www.hotelcareer.ch/popup.php?sei_id=8\u0026id=1656381\u0026print=3","content_clean":"Weitere Bilder / InformationenDie Kartause Ittingen zählt zu den führenden Seminar- und Kultu
  3: {"duplicate_group":"ef933892-662d-4692-a5fd-75da26a81096","title":"ASSISTANT FORECASTING m/f/d","url":"https://jobs.dtswiss.com/job/Biel/842540401/","content_clean":"REFERENCE NO.:  819\nASSISTANT FORECASTING m/f/d\nUnbefristet 20.10.2022 Biel\nDIESE SPANNENDE HERAUSFORDERUNG WARTET AUF DICH\n\n·
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2015-04-17 07:23:44 UTC', 'duplicate_group': '07fda355-c509-41f8-9286-ace447dd30b8', 'title': 'Desktop Support Specialist, Zug, Switzerland', 'company_name': 'Xerox AG'}
  2:  {'tst_created': '2017-03-01 17:01:19 UTC', 'duplicate_group': '3a5c6ab3-f436-4e67-9502-89f646261c2e', 'title': 'Restaurantfachfrau / Restaurantfachmann', 'company_name': 'Stiftung Kartause Ittingen'}
  3:  {'tst_created': '2022-08-23 11:05:39.887 UTC', 'duplicate_group': 'ef933892-662d-4692-a5fd-75da26a81096', 'title': 'ASSISTANT FORECASTING m/f/d', 'company_name': 'DT Swiss AG'}
Indexed 0 new uids from data_000000000006.json.gzip | rows seen: 32,463 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000007.json.gzip (3 lines) ---
  1: {"duplicate_group":"258c9447-770a-417f-a803-84170adc874d","title":"Réceptionist*in 80-100%","url":"https://www.hotelcareer.ch/jobs/stiftung-kartause-ittingen-59310/receptionist-in-80-100-2793508?print=3#innercontent","content_clean":"Réceptionist*in 80-100%Stiftung Kartause Ittingen\n\nWarth-Weining
  2: {"duplicate_group":"c27db0d4-035b-42d2-abdb-80648b36e699","title":"ICT SUPPORTER:IN","url":"https://kombi.jobs.ch/basic_kombi/display.php?aid=10966171\u0026slim=clean","content_clean":"ICT SUPPORTER:IN\n\nJOBS \u0026 KARRIERE Wir bei DT Swiss sind ehrgeizig, engagiert und bestrebt zu lernen. Interes
  3: {"duplicate_group":"d969f529-58d4-4abe-b3c0-99c958dc6a8b","title":"PROJECT ENGINEER CARBON RIMS m/f/d","url":"https://kombi.jobs.ch/basic_kombi/display.php?aid=9b89b58e-c409-41d5-8443-70557482e37d\u0026slim=clean","content_clean":"PROJECT ENGINEER CARBON RIMS m/f/d\n\nJOBS \u0026 KARRIERE Wir bei DT
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2022-06-07 14:24:57.426 UTC', 'duplicate_group': '258c9447-770a-417f-a803-84170adc874d', 'title': 'Réceptionist*in 80-100%', 'company_name': 'Stiftung Kartause Ittingen'}
  2:  {'tst_created': '2022-01-16 20:20:25.713 UTC', 'duplicate_group': 'c27db0d4-035b-42d2-abdb-80648b36e699', 'title': 'ICT SUPPORTER:IN', 'company_name': 'DT Swiss AG'}
  3:  {'tst_created': '2022-10-08 01:13:09.13 UTC', 'duplicate_group': 'd969f529-58d4-4abe-b3c0-99c958dc6a8b', 'title': 'PROJECT ENGINEER CARBON RIMS m/f/d', 'company_name': 'DT Swiss AG'}
Indexed 0 new uids from data_000000000007.json.gzip | rows seen: 32,036 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000008.json.gzip (3 lines) ---
  1: {"duplicate_group":"93d98edd-9667-49a0-bd5b-0b24a1db232b","title":"Köchin/Koch (Chef de Partie/Commis) 80-100%","url":"https://www.hotelcareer.ch/jobs/stiftung-kartause-ittingen-59310/k%C3%B6chin-koch-chef-de-partie-commis-80-100-3051265?print=3#innercontent","content_clean":"Köchin/Koch (Chef de Pa
  2: {"duplicate_group":"718acc69-4bf9-40ef-a26d-968aa2caaae0","title":"AUSBILDUNG LOGISTIKER:IN EFZ 2025 m/w/d","url":"https://jobs.dtswiss.com/job/Biel-AUSBILDUNG-LOGISTIKERIN-EFZ-2025-mwd/857709201/","content_clean":"REFERENCE NO.: \n 941\nAUSBILDUNG LOGISTIKER:IN EFZ 2025 m/w/d\nBefristet\n04.08.2024
  3: {"duplicate_group":"2eb39710-80d5-46b3-ac52-cd1df714010f","title":"Mitarbeiter:in Sales \u0026 Event (80 - 100%)","url":"https://kombi.jobs.ch/basic_kombi/display.php?aid=8651bf11-9c7d-43cd-91a2-dc443f09d643\u0026slim=clean","content_clean":"Mitarbeiter:in Sales \u0026 Event (80 - 100%)\n\nBei uns g
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2022-06-09 08:59:27.401 UTC', 'duplicate_group': '93d98edd-9667-49a0-bd5b-0b24a1db232b', 'title': 'Köchin/Koch (Chef de Partie/Commis) 80-100%', 'company_name': 'Stiftung Kartause Ittingen'}
  2:  {'tst_created': '2022-10-07 13:51:58.966 UTC', 'duplicate_group': '718acc69-4bf9-40ef-a26d-968aa2caaae0', 'title': 'AUSBILDUNG LOGISTIKER:IN EFZ 2025 m/w/d', 'company_name': 'DT Swiss AG'}
  3:  {'tst_created': '2023-03-24 01:20:19.707 UTC', 'duplicate_group': '2eb39710-80d5-46b3-ac52-cd1df714010f', 'title': 'Mitarbeiter:in Sales & Event (80 - 100%)', 'company_name': 'Trauffer Holzspielwaren AG'}
Indexed 0 new uids from data_000000000008.json.gzip | rows seen: 32,434 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000009.json.gzip (3 lines) ---
  1: {"duplicate_group":"e1f6e956-4e70-41ed-88e2-448dcac3ece7","title":"Regionaler Kundenberater (w/m/d) 100%","url":"https://www.ors-jobs.com/de-CH/Jobs/Schweiz/Thurgau-und-Region/Regionaler-Kundenberater-w-m-d","content_clean":"Pensum: 100%\nArbeitsort: Deutschschweiz\nArbeitsbeginn: per sofort oder na
  2: {"duplicate_group":"ae88fa1c-585d-4f89-b120-4ee08aa70034","title":"Senior Associate/Manager SAP Portfolio \u0026 Project Management Consulting","url":"https://jobs.pwc.ch/offene-stellen/senior-associate-manager-sap-portfolio-project-management-consulting/aa04c039-f26d-488f-b7fd-f7b2cf4736d9","conten
  3: {"duplicate_group":"8ce352d4-6aec-4004-8743-8ae65a831a3a","title":"Manager Finance Consulting - Enterprise Performance Management/ Finance Transformation (EPM / FT)","url":"https://jobs.pwc.ch/offene-stellen/manager-finance-consulting-enterprise-performance-management-finance-transformation-epm-ft/b
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2019-10-29 19:40:21.046 UTC', 'duplicate_group': 'e1f6e956-4e70-41ed-88e2-448dcac3ece7', 'title': 'Regionaler Kundenberater (w/m/d) 100%', 'company_name': 'ORS'}
  2:  {'tst_created': '2022-10-31 19:17:28.022 UTC', 'duplicate_group': 'ae88fa1c-585d-4f89-b120-4ee08aa70034', 'title': 'Senior Associate/Manager SAP Portfolio & Project Management Consulting', 'company_name': 'PwC'}
  3:  {'tst_created': '2021-10-27 19:06:37.815 UTC', 'duplicate_group': '8ce352d4-6aec-4004-8743-8ae65a831a3a', 'title': 'Manager Finance Consulting - Enterprise Performance Management/ Finance Transformation (EPM / FT)', 'company_name': 'PwC'}
Indexed 0 new uids from data_000000000009.json.gzip | rows seen: 32,222 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000010.json.gzip (3 lines) ---
  1: {"duplicate_group":"35dc51fe-5c38-48bd-89c2-98f7796607c4","title":"Career Start in Audit - Financial Services - per sofort","url":"https://jobs.pwc.ch/offene-stellen/career-start-in-audit-financial-services-per-sofort/f5da6f20-c915-4f41-ad31-90a8d485a88c","content_clean":"Deine Aufgaben\n\nDu prüfst
  2: {"duplicate_group":"73bc25bc-dfdd-40bf-8667-3381e927ce3f","title":"Audit - Manager - Healthcare","url":"https://jobs.pwc.ch/offene-stellen/audit-manager-healthcare/ca535c96-8171-4326-9084-ff779ad2e520","content_clean":"Deine Aufgaben\n\nDu koordinierst und leitest die Prüfung von Jahres- und Konzern
  3: {"duplicate_group":"f33ed85d-f5b8-43f0-9815-6468ea0f6e5f","title":"Facharzt / Fachärztin Innere Medizin 20 - 30 %","url":"https://kombi.jobs.ch/basic_kombi/display.php?aid=b0805423-5846-4dea-bba1-77d18a1abc9f","content_clean":"Facharzt / Fachärztin Innere Medizin 20 - 30 %\n\nLuzern, Aarau, Basel, B
Detected fields → uid: None, date: tst_created, duplicate_group: duplicate_group
--- parsed head ---
  1:  {'tst_created': '2022-04-28 17:15:13.158 UTC', 'duplicate_group': '35dc51fe-5c38-48bd-89c2-98f7796607c4', 'title': 'Career Start in Audit - Financial Services - per sofort', 'company_name': 'PwC'}
  2:  {'tst_created': '2022-06-30 16:16:56.002 UTC', 'duplicate_group': '73bc25bc-dfdd-40bf-8667-3381e927ce3f', 'title': 'Audit - Manager - Healthcare', 'company_name': 'PwC'}
  3:  {'tst_created': '2021-01-08 00:16:28.062 UTC', 'duplicate_group': 'f33ed85d-f5b8-43f0-9815-6468ea0f6e5f', 'title': 'Facharzt / Fachärztin Innere Medizin 20 - 30 %', 'company_name': 'Suva'}
Indexed 0 new uids from data_000000000010.json.gzip | rows seen: 32,293 | duplicate_group NULL/empty: 0 (0.00%)

--- raw head of data_000000000011.json.gzip (3 lines) ---

In [28]:
import os, gzip, json
from collections import defaultdict
from datetime import datetime

PATH = os.path.expanduser("~/Downloads/240722_panel_data_data_000000000002.json.gzip")
RAW_HEAD_LINES = 5        # show this many raw lines
SCAN_LIMIT = 10000        # scan up to N records to summarize fields

def detect_format(path):
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        sample = f.read(4096).lstrip()
    if sample.startswith('['):
        return "json_array"
    if sample.startswith('{') or "\n{" in sample:
        return "ndjson"
    return "unknown"

def iter_ndjson(path):
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                continue

def iter_json_array(path):
    # very simple streaming JSON-array reader
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        buf = []
        in_obj = False
        depth = 0
        in_str = False
        esc = False
        # move to '['
        while True:
            c = f.read(1)
            if not c: 
                return
            if c == '[': 
                break
        while True:
            c = f.read(1)
            if not c:
                return
            if not in_obj:
                if c == '{':
                    in_obj = True
                    buf = ['{']
                    depth = 1
                    in_str = False
                    esc = False
                continue
            # inside object
            buf.append(c)
            if in_str:
                if esc:
                    esc = False
                elif c == '\\':
                    esc = True
                elif c == '"':
                    in_str = False
            else:
                if c == '"':
                    in_str = True
                elif c == '{':
                    depth += 1
                elif c == '}':
                    depth -= 1
                    if depth == 0:
                        try:
                            yield json.loads("".join(buf))
                        except Exception:
                            pass
                        in_obj = False

def iter_records(path):
    fmt = detect_format(path)
    return iter_ndjson(path) if fmt == "ndjson" else iter_json_array(path)

# ---- 1) Raw head (just to eyeball) ----
print(f"File: {os.path.basename(PATH)}")
print(f"Detected format: {detect_format(PATH)}")
print("\n--- RAW HEAD ---")
with gzip.open(PATH, "rt", encoding="utf-8", errors="replace") as f:
    for i, line in zip(range(1, RAW_HEAD_LINES+1), f):
        print(f"{i:>3}: {line.rstrip()[:200]}")

# ---- 2) Parse a few rows + schema summary ----
print("\n--- PARSED HEAD (first 5 objects) ---")
it = iter_records(PATH)
head = []
for i, obj in enumerate(it):
    head.append(obj)
    print(f"{i+1:>3}: ", {k: obj.get(k) for k in list(obj.keys())[:10]})  # show first ~10 keys & values
    if i >= 4:
        break

if not head:
    raise SystemExit("No records parsed from file.")

# ---- 3) Field coverage over up to SCAN_LIMIT records ----
field_counts = defaultdict(int)
total = 0
# count fields in the head we already pulled
for obj in head:
    total += 1
    for k, v in obj.items():
        if v is not None and (not isinstance(v, str) or v.strip() != ""):
            field_counts[k] += 1

# continue scanning
for obj in it:
    total += 1
    for k, v in obj.items():
        if v is not None and (not isinstance(v, str) or v.strip() != ""):
            field_counts[k] += 1
    if total >= SCAN_LIMIT:
        break

fields = sorted(field_counts.keys())
print(f"\nScanned {total:,} records (or until EOF).")
print(f"Number of distinct fields seen: {len(fields)}")
print("\nTop-level fields (alphabetical) with non-null presence %:")
for k in fields:
    pct = 100.0 * field_counts[k] / total if total else 0.0
    print(f"  {k}: {pct:5.1f}%")

# quick check for duplicate_group presence
has_dup_group = any(k == "duplicate_group" for k in fields)
print(f"\nHas 'duplicate_group' field? {'YES' if has_dup_group else 'NO'}")

File: 240722_panel_data_data_000000000002.json.gzip
Detected format: ndjson

--- RAW HEAD ---
  1: {"title":"Pflegefachperson HF (w/m/d) / befristet für 3 Monate 60% - 100%","url":"https://www.ors-jobs.com/de-CH/Jobs/Schweiz/Basel-und-Region/Pflegefachperson-HF-w-m-d-befristet-fur-3-Mona","content_
  2: {"title":"Senior Associate for Finance Transformation with SAP","url":"https://jobs.pwc.ch/offene-stellen/senior-associate-for-finance-transformation-with-sap/819c87ed-27bd-4ed4-ad8c-ca832cc62ff6","co
  3: {"title":"Associate / Senior Associate Public Sector Consulting","url":"https://jobs.pwc.ch/offene-stellen/associate-senior-associate-public-sector-consulting/ad80e97a-e18a-41cd-b1ac-2f7234f9dd5e","co
  4: {"title":"Audit Senior Manager Asset Management/Banking","url":"https://direktlink.prospective.ch/?view=27c5dd2b-c5e5-4f1a-986f-a15030b94e3e","content_clean":"Deine Aufgaben\n\nDu prüfst Jahres- und K
  5: {"title":"Senior Manager/Director SAP Portfolio \u0026 Project Management Consulting","url":"https://jobs.pwc.ch/offene-stellen/senior-manager-director-sap-portfolio-project-management-consulting/218b

--- PARSED HEAD (first 5 objects) ---
  1:  {'title': 'Pflegefachperson HF (w/m/d) / befristet für 3 Monate 60% - 100%', 'url': 'https://www.ors-jobs.com/de-CH/Jobs/Schweiz/Basel-und-Region/Pflegefachperson-HF-w-m-d-befristet-fur-3-Mona', 'content_clean': 'Pensum: 60% - 100%\nArbeitsort: Basel (BS), Allschwil (BL), Flumenthal (SO)\nArbeitsbeginn: genauer Zeitpunkt unbekannt, befristet für 3 Monate\n\nDie ORS Service AG ist ein politisch und religiös neutrales Unternehmen der ORS Gruppe, das sich auf die Betreuung, Unterbringung und Integration von Asylsuchenden und Flüchtlingen in der Schweiz spezialisiert hat. Dabei ist sie kompetente Partnerin von Bund, Kantonen und Gemeinden.\n\nZur Ergänzung unserer Teams in den Bundesasylzentren in Basel (BS), Allschwil (BL) und Flumenthal (SO) suchen wir eine\xa0Pflegefachperson (m/w/d) 60-100%\xa0im Tagdienst. Der Arbeitsbeginn ist nicht bekannt, da wir aktuell einen\xa0Kandidatenpool\xa0zusammenstellen. Es ist anzunehmen, dass in den genannten Bundesasylzentren demnächst ein höherer Personalbedarf ensteht. In dem Fall werden wir gerne auf den Kandidatenpool zurückgreifen und Sie kontaktieren. Ab diesem Zeitpunkt wäre der Arbeitsbeginn\xa0per sofort\xa0und die Anstellung\xa0befristet für 3 Monate.\n\nIhre Herausforderung\n\nIn dieser Funktion sind Sie für die medizinische Betreuung der uns anvertrauten Asylsuchenden verantwortlich und arbeiten in einem kleinen Team von Pflegenden. Der Umgang mit Menschen unterschiedlicher Kultur bereitet Ihnen Freude. Zu Ihren Aufgaben gehören unter anderem die medizinische Triage, Kontaktpflege mit den Hausärzten und Spitälern, Ansprechperson für medizinische Belange der Asylsuchenden, kontrollierte Medikamentenabgabe, Führen der zentrumsinternen Apotheke, Aufbau und Organisation der medizinischen Grundversorgung.\n\nIhr Profil\n\nAbgeschlossene Pflegefachausbildung HF, DNII\xa0oder eine anerkannte gleichwertige Ausbildung\n\nMehrjährige Berufserfahrung\xa0im Akutbereich\n\nHohe Beratungs- und Kommunikationskompetenz\n\nGute administrative Fähigkeiten\n\nBelastbarkeit und hohe Sozialkompetenzen\n\nKenntnisse im Bereich Migration oder Bereitschaft, diese zu erwerben\n\nStilsicheres Deutsch (Niveau C1), gute Englisch- oder Französischkenntnisse (Niveau B1), weitere Sprachen von Vorteil\n\nHohes Mass an Flexibilität\n\nAufenthaltsbewilligung C oder Schweizer Bürger\n\nMindestalter 25 Jahre\n\nFür den Ihnen anvertrauten Aufgabenbereich setzten Sie sich initiativ und vollumfänglich ein. Zu Ihren Stärken zählen Flexibilität und selbständiges Arbeiten sowie ein gesundes Durchsetzungsvermögen. Eine hohe Arbeitsqualität und konsequenter Service- und Dienstleistungsgedanke sind für Sie selbstverständlich. Sie kommunizieren geschickt und diplomatisch. Ihre positive Lebenseinstellung ist motivierend, erleichtert Ihnen den Zugang zu Menschen und fördert die Zusammenarbeit. Beratungs- und hohe Sozialkompetenz sowie sicheres Auftreten runden Ihr Profil ab.\n\nIhre Perspektiven\n\nEs erwartet Sie eine abwechslungsreiche, erfüllende Aufgabe in einem interessanten, dynamischen Umfeld. Als innovative Arbeitgeberin bieten wir unseren Mitarbeiter*innen permanente Aus- und Weiterbildungsmöglichkeiten.\n\nHaben wir Ihr Interesse geweckt? Dann freut sich Frau Melanie Schnetzer, HR Generalistin, auf Ihre vollständigen Bewerbungsunterlagen unter Angabe des gewünschten\xa0Arbeitsort\xa0und der Referenznummer «RNWCH-PFP-0421» an\xa0jobs@ors.ch.\xa0Bitte beachten Sie, dass wir Postbewerbungen nicht retournieren. Wir danken Ihnen für die Kenntnisnahme.\n\nWeitere Informationen finden Sie unter:\xa0www.ors-jobs.com', 'company_id': '40000683', 'company_name': 'ORS', 'company_size': 'Kleinunternehmen', 'company_is_recruiter': False, 'tst_created': '2021-04-01 14:19:10.236 UTC', 'tst_deleted': '2021-06-04 09:31:37.988 UTC', 'x28_industries': ['65000033']}
  2:  {'title': 'Senior Associate for Finance Transformation with SAP', 'url': 'https://jobs.pwc.ch/offene-stellen/senior-associate-for-finance-transformation-with-sap/819c87ed-27bd-4ed4-ad8c-ca832cc62ff6', 'content_clean': "Your tasks\n\nYou will work in challenging, international and fast paced SAP transformation programs focusing on strategy selection, design and implementation of the newest SAP solutions like S/4HANA and S/4HANA Central Finance.\n\nYou will analyze our client's finance and controlling business processes, evaluate the best use of SAP solutions and, advise our clients on design and implementation of best-practice SAP finance and controlling solutions.\n\nYou acquire a broad range of technical and soft skills through on the job and off the job trainings.\n\nYour will be part of a growing, dynamic team blending SAP innovation and industry expertise.\n\nYou thrive in an environment committed to teamwork, trust and mutual support.\n\nYou will be coached by inspiring and challenging leaders.\n\nYour profile\n\nYou have a degree (bachelor / master / diploma) preferred in business, IT, engineering or business information systems or digital discipline. Preferably you focused and specialized on finance/controlling during your primarily and further education.\n\nYou have more than 2 years of experience in process consulting and implementation of SAP Finance and Controlling solutions. It is beneficial if you have already first experience with S/4HANA.\n\nYou have experience in specific SAP Finance modules and a profound understanding of related business processes.\n\nYou have strong analytical and interpersonal skills, with a commitment to professional and client service excellence.\n\nYou are fluent in German and in English (both spoken and written), working knowledge of French is a plus.\n\nYou will be based in Zurich, Bern or Basel and are flexible to work on engagements in other parts of Switzerland and/or abroad.\n\nJoin our community of solvers\n\nFrancisca Richter\nRecruitment Team\nTel. +41 58 792 16 81 We believe that challenges are better solved together. That's why you'll join a diverse, global community of solvers – an unexpected mix of people that come together to build trust in society and solve important problems. We invite you to be a part of The New Equation.\n\nDo you have any questions? Give us a call, we are happy to help.\nLearn more about our application process.\n\nFrancisca Richter\nRecruitment Team\nTel. +41 58 792 16 81Apply now!Apply now!", 'company_id': '40002024', 'company_name': 'PwC', 'company_size': 'Grossunternehmen', 'company_is_recruiter': False, 'tst_created': '2022-08-15 19:46:36.48 UTC', 'tst_deleted': '2022-08-16 20:59:23.074 UTC', 'x28_industries': ['65000031']}
  3:  {'title': 'Associate / Senior Associate Public Sector Consulting', 'url': 'https://jobs.pwc.ch/offene-stellen/associate-senior-associate-public-sector-consulting/ad80e97a-e18a-41cd-b1ac-2f7234f9dd5e', 'content_clean': 'Deine Aufgaben\n\nDu möchtest aktiv zu einer modernen Verwaltung und einem wirkungsvollen Service Public beitragen.\n\nDu möchtest die digitale Transformation im öffentlichen Sektor und der Mobilität zusammen mit Kund:innen wie der Bundesverwaltung, Kantonen, staatsnahen Betrieben vorantreiben.\n\nDu interessiert dich für neue Geschäftsmodelle, Strategien und Organisationsformen und findest Themen wie ESG, E-Government, Smart Mobility/ City oder digitale Verwaltung spannend.\n\nDu hast bereits erste Erfahrungen in agilen Arbeitsweisen gesammelt und Scrum oder SAFe sind keine Fremdwörter für dich.\n\nDu bist interessiert, dich im Bereich Strategie und Transformationen zu bewegen und hast Lust auch über den Tellerrand hinaus zu schauen.\n\nDu willst Teil eines jungen und dynamischen Teams sein, in dem Du schnell Verantwortung übernehmen und gemeinsam wachsen kannst.\n\nDu teilst unsere Kultur und Werte, lebst flache Hierarchien, arbeitest unabhängig und selbstständig. Dir ist Wertschätzung wichtig und du legst Wert auf flexible Arbeitsmodelle sowie eine Work-Life-Balance.\n\nDein Profil\n\nDu besitzt einen Universitäts- oder ETH-Abschluss (alle Fachrichtungen).\n\nDu hast idealerweise erste Erfahrungen in der Strategie-/Managementberatung gesammelt und/oder andere relevante beruflichen Rollen wahrgenommen.\n\nDu hast sehr gute Deutsch- und Englischkenntnisse, Französisch ist von Vorteil.\n\nDu trittst überzeugend auf und du bist eine hoch motivierte, dynamische Persönlichkeit, die gerne im Team arbeitet und Verantwortung übernimmt.\n\nDu hast eine rasche Auffassungsgabe, ausgeprägte analytische und konzeptionelle Fähigkeiten und hast Spass daran, dich stetig weiter zu entwickeln.\n\nWerde Teil unserer «Community of Solvers»\n\nFrancisca Richter\nRecruitment Team\nTel. +41 58 792 16 81 Unserer Meinung nach lassen sich Herausforderungen besser gemeinsam bewältigen. Deshalb triffst du bei PwC auf eine vielfältige, globale «Community of Solvers» – einen unerwarteten Mix von Menschen, die gemeinsam Vertrauen in die Gesellschaft aufbauen und wichtige Probleme lösen wollen. Wir laden dich ein, Teil davon zu werden: Be a part of The New Equation.\n\nHast du Fragen? Ruf uns an, wir geben dir gerne Auskunft.\nHier erfährst du mehr über unseren Bewerbungsprozess.\n\nFrancisca Richter\nRecruitment Team\nTel. +41 58 792 16 81Jetzt bewerben!Jetzt bewerben!', 'company_id': '40002024', 'company_name': 'PwC', 'company_size': 'Grossunternehmen', 'company_is_recruiter': False, 'tst_created': '2022-07-14 13:48:32.413 UTC', 'tst_deleted': '2022-08-09 12:26:35.952 UTC', 'x28_industries': ['65000031']}
  4:  {'title': 'Audit Senior Manager Asset Management/Banking', 'url': 'https://direktlink.prospective.ch/?view=27c5dd2b-c5e5-4f1a-986f-a15030b94e3e', 'content_clean': 'Deine Aufgaben\n\nDu prüfst Jahres- und Konzernrechnungen bei Banken, Verwaltungsgesellschaften, Vermögensverwaltungen und Anlagefonds.\n\nDu führst aufsichtsrechtliche Prüfungen bei regulierten Finanzintermediären durch.\n\nDu unterstützt unsere Prüfteams und Kunden bei der Umsetzung von neuen Regulatorischen Richtlinien sowie der daraus abgeleiteten Rechtsakte, Leitlinien und Empfehlungen.\n\nDu bist verantwortlich für die Beurteilung von Geschäftsprozessen und bei Fragen zur Rechnungslegung nach verschiedenen Standards und du berätst Kunden im Bereich Rechnungslegung und zu regulatorischen Änderungen.\n\nDu führst Sonderaufträge und –prüfungen durch und übernimmst Verantwortung bei diversen Aufträgen im Rahmen von Produktlancierungen und anderen Spezialsituationen.\n\nDu bist verantwortlich für die Leitung verschiedener Teams und für die Koordination mit Spezialisten der IT-Prüfung, Regulatory Compliance, der Steuern oder im Bereich von Bewertungen.\n\nDu entwickelst dein technisches Know-How sowie deine Soft-Skills durch Trainings on-and-off-the-job laufend weiter.\n\nDein Profil\n\nDu hast einen Bachelor oder Masterabschluss in Wirtschaftswissenschaften oder in einem ähnlichen Fachbereich oder einen Fachausweis zum Treuhänder.\n\nDu bist diplomierter Wirtschaftsprüfer oder stehst in der Ausbildung dazu.\n\nDu hast mindestens vier Jahre Audit-Erfahrung im Bereich Financial Services und hast im Idealfall schon Erfahrungen gesammelt in der Prüfung von liechtensteinischen Finanzintermediären im Bereich Banking und/oder Asset Management.\n\nDu hast vorzugsweise bereits Kenntnisse der relevanten spezialgesetzlichen Vorschriften (BankG, UCITSG, AIFMG, IUG).\n\nDu verfügst über sehr gute Deutsch- und Englischkenntnisse in Wort und Schrift.\n\nDu bist innovativ, arbeitest gerne im Team und hast sehr gute Projektmanagement-Fähigkeiten.\n\nDas sind wir – PwC als Arbeitgeber\n\nBei PwC tun wir für unsere Mitarbeitenden genau das, was wir auch für unsere Kunden tun: Mehrwert schaffen in den Bereichen Wirtschaftsprüfung, Steuer- und Rechtsberatung, Consulting, Deals und Digital Services. Und du kannst dasselbe tun. Liebst du Veränderung und möchtest du die Zukunft eines der weltweit führenden Beratungsunternehmen mitgestalten? Dann hast du genau das, worauf es ankommt. Die Fähigkeit «to reimagine the possible»!\nJede Karriere ist einzigartig. Deshalb bietet dir PwC unzählige persönliche und berufliche Entwicklungsmöglichkeiten, die zu deinen Zielen passen und dir ermöglichen, deinen eigenen Weg zu gehen. Damit du alles erreichen kannst, was du möchtest. Und noch ein wenig mehr.\nMehr zur Wirtschaftsprüfung', 'company_id': '40002024', 'company_name': 'PwC', 'company_size': 'Grossunternehmen', 'company_is_recruiter': False, 'tst_created': '2018-06-18 12:52:43.802 UTC', 'tst_deleted': '2019-11-19 07:43:46.529 UTC', 'x28_industries': ['65000031']}
  5:  {'title': 'Senior Manager/Director SAP Portfolio & Project Management Consulting', 'url': 'https://jobs.pwc.ch/offene-stellen/senior-manager-director-sap-portfolio-project-management-consulting/218bcc09-de45-48f5-a1db-f7c7f853be69', 'content_clean': 'Deine Aufgaben\n\nDu arbeitest mit unseren Kunden an ihren Portfolio- und Projektmanagementprozessen, bewertest die beste Nutzung von SAP-Lösungen und berätst sie beim Design und der Implementierung erstklassiger SAP-Lösungen.\n\nDu hilfst unseren Kunden, Lösungen basierend auf der neuesten Technologie wie Predictive Analytics in ihre S4 HANA-Lösung zu integrieren.\n\nDu hast die Möglichkeit, Verantwortung für das Management von Projekten und Projektarbeitsabläufen in herausfordernden und schnelllebigen SAP-Transformationsprogrammen zu übernehmen.\n\nDu trägst zur Entwicklung unseres erstklassigen SAP-Beratungsteams bei.\n\nDu erweiterst Deine Fähigkeiten durch spezifische Schulungen gemäß Deinem persönlichen Entwicklungsplan.\n\nDu wirst Teil eines wachsenden, dynamischen Teams, das SAP-Innovation und Branchenexpertise verbindet.\n\nDu bewegst Dich in einem Umfeld, das auf Teamarbeit, Vertrauen und gegenseitige Unterstützung ausgerichtet ist.\n\nDu wirst von inspirierenden und herausfordernden Führungskräften gecoacht.\n\nDein Profil\n\nDu hast ein abgeschlossenes Studium (Bachelor / Master / Diplom) bevorzugt in Wirtschaftsinformatik, Ingenieurwesen, Wirtschaftsinformatik oder einer digitalen Fachrichtung.\n\nDu hast mehr als 7 Jahre Erfahrung in der Prozessberatung und Implementierung von SAP-Lösungen.\n\nDu bringst einschlägige Erfahrung im SAP Portfolio & Project Management sowie der Integration in Finanz- und Logistikmodule und ein profundes Verständnis der damit verbundenen Geschäftsprozesse mit.\n\nDu verfügst über ausgeprägte analytische Fähigkeiten und engagierst Dich für professionelle Exzellenz.\n\nDu bist ein:e Teamplayer:in und bereit, Verantwortung in Projekten zu übernehmen und innovative Lösungen voranzutreiben.\n\nDu verfügst über einschlägige Führungserfahrung, die Coaching, die Leitung von Engagement-Teams und das Management von Kundenbeziehungen umfasst.\n\nDu verfügst über ein großes Kundennetzwerk und kannst als Key Account Manager für bestimmte Kunden agieren.\n\nDu sprichst fließend Deutsch und Englisch (in Wort und Schrift), Grundkenntnisse in Französisch sind von Vorteil.\n\nDu arbeitest in Zürich, Bern oder Basel und bist flexibel für Einsätze in anderen Teilen der Schweiz.\n\nWerde Teil unserer «Community of Solvers»\n\nFrancisca Richter\nRecruitment Team\nTel. +41 58 792 16 81 Unserer Meinung nach lassen sich Herausforderungen besser gemeinsam bewältigen. Deshalb triffst du bei PwC auf eine vielfältige, globale «Community of Solvers» – einen unerwarteten Mix von Menschen, die gemeinsam Vertrauen in die Gesellschaft aufbauen und wichtige Probleme lösen wollen. Wir laden dich ein, Teil davon zu werden: Be a part of The New Equation.\n\nHast du Fragen? Ruf uns an, wir geben dir gerne Auskunft.\nHier erfährst du mehr über unseren Bewerbungsprozess.\n\nFrancisca Richter\nRecruitment Team\nTel. +41 58 792 16 81Jetzt bewerben!Jetzt bewerben!', 'company_id': '40002024', 'company_name': 'PwC', 'company_size': 'Grossunternehmen', 'company_is_recruiter': False, 'tst_created': '2022-04-08 19:36:08.511 UTC', 'tst_deleted': '2022-09-14 12:22:25.828 UTC', 'x28_industries': ['65000031']}

Scanned 10,000 records (or until EOF).
Number of distinct fields seen: 13

Top-level fields (alphabetical) with non-null presence %:
  cantons: 100.0%
  company_id: 100.0%
  company_is_recruiter: 100.0%
  company_name: 100.0%
  company_size:  95.0%
  content_clean:  98.5%
  location_raw:  98.7%
  title: 100.0%
  tst_created: 100.0%
  tst_deleted:  99.7%
  url: 100.0%
  x28_industries: 100.0%
  x28_occupations: 100.0%

Has 'duplicate_group' field? NO

In [30]:
import os, gzip, json, hashlib, sqlite3, re
from glob import glob
from urllib.parse import urlparse, parse_qsl, urlunparse
from datetime import datetime
from collections import defaultdict

import os, sqlite3, tempfile
from pathlib import Path

# pick a path & make sure its directory exists
DB_PATH = os.path.expanduser("~/tmp/overlap_index.sqlite")  # or change to something you like
p = Path(DB_PATH).expanduser()
p.parent.mkdir(parents=True, exist_ok=True)  # <-- create ~/tmp if missing

# if a stale file exists, remove it (optional)
if p.exists():
    try: p.unlink()
    except Exception as e: print("Could not remove old DB:", e)

# connect; if this location still fails, fall back to /tmp
try:
    con = sqlite3.connect(str(p))
except sqlite3.OperationalError as e:
    print("Primary location failed:", e, "\nFalling back to /tmp …")
    DB_PATH = os.path.join(tempfile.gettempdir(), "overlap_index.sqlite")
    con = sqlite3.connect(DB_PATH)

cur = con.cursor()
print("Using SQLite at:", DB_PATH)


# ---------- CONFIG ----------
DG_DIR = os.path.expanduser("~/Downloads/240826_panel_data_with_dg")   # folder with data_*.json.gzip
OLD_FILE = os.path.expanduser("~/Downloads/240722_panel_data_data_000000000002.json.gzip")
DB_PATH = os.path.expanduser("~/tmp/overlap_index.sqlite")             # temp local index

# ---------- Helpers: streaming JSON(.gzip) ----------
def detect_format(path):
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        sample = f.read(4096).lstrip()
    if sample.startswith('['): return "json_array"
    if sample.startswith('{') or "\n{" in sample: return "ndjson"
    return "unknown"

def iter_ndjson(path):
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        for line in f:
            line=line.strip()
            if not line: continue
            try: yield json.loads(line)
            except json.JSONDecodeError: continue

def iter_json_array(path):
    with gzip.open(path, "rt", encoding="utf-8", errors="replace") as f:
        buf=[]; in_obj=False; depth=0; in_str=False; esc=False
        # seek to '['
        while True:
            c=f.read(1); 
            if not c: return
            if c=='[': break
        while True:
            c=f.read(1)
            if not c: return
            if not in_obj:
                if c=='{':
                    in_obj=True; buf=['{']; depth=1; in_str=False; esc=False
                continue
            buf.append(c)
            if in_str:
                if esc: esc=False
                elif c=='\\': esc=True
                elif c=='"': in_str=False
            else:
                if c=='"': in_str=True
                elif c=='{': depth+=1
                elif c=='}':
                    depth-=1
                    if depth==0:
                        try: yield json.loads("".join(buf))
                        except Exception: pass
                        in_obj=False

def iter_records(path):
    fmt = detect_format(path)
    return iter_ndjson(path) if fmt == "ndjson" else iter_json_array(path)

# ---------- Key builders ----------
ID_PARAMS = {"id","jobid","job_id","vacancy_id"}  # keep these query params if present

def normalize_url(u:str)->str:
    if not u: return ""
    try:
        p = urlparse(u)
        netloc = (p.netloc or "").lower()
        path = (p.path or "").rstrip('/') or '/'
        # keep only id-like params, sorted
        qdict = [(k,v) for k,v in parse_qsl(p.query, keep_blank_values=True) if k.lower() in ID_PARAMS]
        qdict.sort()
        q = "&".join(f"{k}={v}" for k,v in qdict)
        norm = urlunparse((p.scheme.lower(), netloc, path, "", q, ""))
        return norm
    except Exception:
        return u.strip()

def url_hash(u:str)->str:
    return hashlib.sha1(normalize_url(u).encode("utf-8",errors="ignore")).hexdigest()

_ws = re.compile(r"\s+")
def soft_key(company:str, title:str, tst_created:str)->str:
    def clean(s):
        if s is None: return ""
        s = s.strip().lower()
        s = _ws.sub(" ", s)
        return s
    # use date (day) granularity
    day = ""
    if tst_created:
        try:
            day = datetime.fromisoformat(str(tst_created).replace("Z","+00:00")).date().isoformat()
        except Exception:
            day = str(tst_created)[:10]
    key = f"{clean(company)}||{clean(title)}||{day}"
    return hashlib.sha1(key.encode("utf-8")).hexdigest()

# ---------- SQLite index ----------
if os.path.exists(DB_PATH):
    os.remove(DB_PATH)
con = sqlite3.connect(DB_PATH)
cur = con.cursor()
cur.execute("PRAGMA journal_mode=WAL;")
cur.execute("CREATE TABLE urls_dg (url_hash TEXT PRIMARY KEY, example_url TEXT)")
cur.execute("CREATE TABLE soft_dg (soft_hash TEXT PRIMARY KEY, ex_company TEXT, ex_title TEXT, ex_day TEXT)")
cur.execute("CREATE INDEX IF NOT EXISTS idx_soft ON soft_dg(soft_hash)")
con.commit()

# ---------- Pass 1: index the with-dg bundle ----------
dg_files = sorted(glob(os.path.join(DG_DIR, "*.json.gzip")))
if not dg_files:
    raise SystemExit(f"No files found in {DG_DIR}")

dg_min_dt = None
dg_max_dt = None
urls_seen = 0
soft_seen = 0

def up_minmax(dt_str, cur_min, cur_max):
    try:
        dt = datetime.fromisoformat(str(dt_str).replace("Z","+00:00"))
        cur_min = dt if cur_min is None or dt < cur_min else cur_min
        cur_max = dt if cur_max is None or dt > cur_max else cur_max
    except Exception:
        pass
    return cur_min, cur_max

BATCH = 5000
buf_url = []
buf_soft = []

for path in dg_files:
    for rec in iter_records(path):
        u = rec.get("url")
        t = rec.get("title")
        c = rec.get("company_name")
        tc = rec.get("tst_created")
        dg_min_dt, dg_max_dt = up_minmax(tc, dg_min_dt, dg_max_dt)

        if u:
            h = url_hash(u)
            buf_url.append((h, u))
            urls_seen += 1
        if t and c and tc:
            s = soft_key(c, t, tc)
            buf_soft.append((s, c, t, str(tc)[:10]))
            soft_seen += 1

        if len(buf_url)>=BATCH:
            cur.executemany("INSERT OR IGNORE INTO urls_dg(url_hash, example_url) VALUES (?,?)", buf_url)
            buf_url.clear()
        if len(buf_soft)>=BATCH:
            cur.executemany("INSERT OR IGNORE INTO soft_dg(soft_hash, ex_company, ex_title, ex_day) VALUES (?,?,?,?)", buf_soft)
            buf_soft.clear()

# flush
if buf_url:
    cur.executemany("INSERT OR IGNORE INTO urls_dg(url_hash, example_url) VALUES (?,?)", buf_url)
if buf_soft:
    cur.executemany("INSERT OR IGNORE INTO soft_dg(soft_hash, ex_company, ex_title, ex_day) VALUES (?,?,?,?)")
con.commit()

dg_url_count = cur.execute("SELECT COUNT(*) FROM urls_dg").fetchone()[0]
dg_soft_count = cur.execute("SELECT COUNT(*) FROM soft_dg").fetchone()[0]

print("Indexed with-dg bundle:")
print(f"  files: {len(dg_files)}")
print(f"  date range (tst_created): {dg_min_dt} → {dg_max_dt}")
print(f"  distinct URL hashes: {dg_url_count:,}  (raw seen: {urls_seen:,})")
print(f"  distinct soft keys:  {dg_soft_count:,}  (raw seen: {soft_seen:,})")

# ---------- Pass 2: scan the OLD file and compare ----------
old_min_dt = None
old_max_dt = None
old_total = 0
old_url_have = 0
old_soft_have = 0

# to show a few examples that matched:
ex_url_hashes = set()
ex_soft_hashes = set()

def batch_membership(table, col, keys):
    # returns set(keys_present)
    if not keys: return set()
    # chunk to stay under SQLite variable limits (~999)
    present = set()
    for i in range(0, len(keys), 800):
        sub = keys[i:i+800]
        qmarks = ",".join(["?"]*len(sub))
        if table=="urls_dg":
            rows = cur.execute(f"SELECT {col} FROM urls_dg WHERE {col} IN ({qmarks})", sub).fetchall()
        else:
            rows = cur.execute(f"SELECT {col} FROM soft_dg WHERE {col} IN ({qmarks})", sub).fetchall()
        present.update(r[0] for r in rows)
    return present

buf_old_url = []
buf_old_soft = []

for rec in iter_records(OLD_FILE):
    old_total += 1
    u = rec.get("url")
    t = rec.get("title")
    c = rec.get("company_name")
    tc = rec.get("tst_created")
    old_min_dt, old_max_dt = up_minmax(tc, old_min_dt, old_max_dt)

    if u:
        buf_old_url.append(url_hash(u))
    if t and c and tc:
        buf_old_soft.append(soft_key(c, t, tc))

    if len(buf_old_url) >= 5000 or len(buf_old_soft) >= 5000:
        pres = batch_membership("urls_dg", "url_hash", buf_old_url)
        old_url_have += len(pres)
        ex_url_hashes |= set(list(pres)[:5])
        buf_old_url.clear()

        pres = batch_membership("soft_dg", "soft_hash", buf_old_soft)
        old_soft_have += len(pres)
        ex_soft_hashes |= set(list(pres)[:5])
        buf_old_soft.clear()

# flush remainder
if buf_old_url:
    pres = batch_membership("urls_dg", "url_hash", buf_old_url)
    old_url_have += len(pres)
    ex_url_hashes |= set(list(pres)[:5])

if buf_old_soft:
    pres = batch_membership("soft_dg", "soft_hash", buf_old_soft)
    old_soft_have += len(pres)
    ex_soft_hashes |= set(list(pres)[:5])

print("\nOld file scan:")
print(f"  file: {os.path.basename(OLD_FILE)}")
print(f"  date range (tst_created): {old_min_dt} → {old_max_dt}")
print(f"  records scanned: {old_total:,}")

pct_url = 100.0*old_url_have/old_total if old_total else 0.0
pct_soft = 100.0*old_soft_have/old_total if old_total else 0.0
print(f"\nOverlap by URL:  {old_url_have:,}/{old_total:,}  ({pct_url:.1f}%)")
print(f"Overlap by soft:  {old_soft_have:,}/{old_total:,}  ({pct_soft:.1f}%)")

# show a few examples
if ex_url_hashes:
    print("\nExamples (URL matches):")
    for h in list(ex_url_hashes)[:5]:
        row = cur.execute("SELECT example_url FROM urls_dg WHERE url_hash=?", (h,)).fetchone()
        if row:
            print("  ", row[0])

if ex_soft_hashes:
    print("\nExamples (soft matches: company | title | day):")
    for h in list(ex_soft_hashes)[:5]:
        row = cur.execute("SELECT ex_company, ex_title, ex_day FROM soft_dg WHERE soft_hash=?", (h,)).fetchone()
        if row:
            print("  ", " | ".join(row))

Using SQLite at: /Users/bradyallardice/tmp/overlap_index.sqlite

TypeError: function takes exactly 2 arguments (1 given)

In [33]:
# Independent status check - won't interfere with running operations
print("🔍 Opening independent connection to check status...")

import os
from dotenv import load_dotenv
import psycopg2
import pandas as pd

load_dotenv("config.env")
status_conn = psycopg2.connect(
    dbname=os.getenv("DB_NAME"), user=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"), host=os.getenv("DB_HOST"),
    port=os.getenv("DB_PORT")
)
status_conn.autocommit = True

def status_qdf(sql, params=None):
    return pd.read_sql_query(sql, status_conn, params=params)

try:
    staging_result = status_qdf("SELECT COUNT(*) as count FROM public.job_postings_unified_staging;")
    final_result = status_qdf("SELECT COUNT(*) as count FROM public.job_postings_unified;")

    staging_count = staging_result['count'].iloc[0]
    final_count = final_result['count'].iloc[0]x

    print(f"📊 Staging: {staging_count:,} rows")
    print(f"📊 Final: {final_count:,} rows")
    print(f"📈 Progress: {final_count:,}/{staging_count:,} ({100*final_count/staging_count if staging_count > 0 else 0:.1f}%)")

finally:
    status_conn.close()

🔍 Opening independent connection to check status...

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/4258377430.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql_query(sql, status_conn, params=params)

📊 Staging: 6,961,228 rows
📊 Final: 0 rows
📈 Progress: 0/6,961,228 (0.0%)

In [41]:
df = pd.read_csv('Data/ai_development_deduplicated_custom.csv')
df

,uid,title,company_name,company_size,location_raw,content_clean,tst_created,url,matched_keywords,company_id,company_is_recruiter,tst_deleted,x28_industries,x28_occupations,cantons,duplicate_group
0,surr_cbe0aa4810777b787fdac91940bc19c2bebbbf3b,Wissenschaftliche(r) Mitarbeiter(in) 80 %,Kanton Bern,Mittelunternehmen,Bern,Wissenschaftliche(r) Mitarbeiter(in) 80 %\nKad...,2012-01-02 02:57:28.579000+01:00,http://www.jobs.sites.be.ch/jobs_sites/de/inde...,ai(punct),40001635,False,2012-01-17 03:33:41.730000+01:00,['65000028'],['11001434'],['BE'],f2241899-081c-4289-9c2d-2b7bd35aaf10
1,surr_0394510f1b309137591d488c86ddc1aa842fd07a,Berufslehre Kauffrau / Kaufmann,Kendrion (Switzerland) AG,Grossunternehmen,CH-8915 Hausen am Albis,Berufslehre Kauffrau / Kaufmann\n\nWir bieten ...,2012-01-02 12:21:17.327000+01:00,http://www.kendrion-electromagnetic.com/job/au...,aa(punct),40015712,False,2012-01-13 16:31:58.532000+01:00,['65000006'],['11000034'],['ZH'],82fc221d-74e9-45de-9aed-4cbdd7da06c0
2,surr_fbf729a46653ca87cd398c3ce12ae1d060943aab,Berufslehre Kauffrau / Kaufmann,Kendrion (Switzerland) AG,Grossunternehmen,CH-8915 Hausen am Albis,Berufslehre Kauffrau / Kaufmann\n\nWir bieten ...,2012-01-02 12:21:26.947000+01:00,http://www.kendrion-electromagnetic.com/job/au...,aa(punct),40015712,False,2012-01-20 13:56:22.771000+01:00,['65000006'],['11000034'],['ZH'],e6000153-3168-41fd-8a2d-37d72012d8b0
3,surr_8bc65d6670785d55378bcb2fee3004efa51976d5,Team Leader pour service et cuisine et Employé...,Autogrill Schweiz AG,Grossunternehmen,Genève,Team Leader pour service et cuisine et Employé...,2012-01-04 12:34:32.229000+01:00,http://www.autogrill.ch/page/index.cfm?SelNavI...,caffe,40000111,False,2012-01-24 15:58:00.189000+01:00,['65000013'],"['11000051', '11001814']",['GE'],3ddc612d-8527-4da1-9a8d-94173d2a1093
4,surr_7dda7bd163b960db2f918e3c69c99ca41e156b7f,Senior Global Program Regulatory Manager (IHC),Novartis AG,Grossunternehmen,Basel,Senior Global Program Regulatory Manager (IHC)...,2012-01-04 22:08:46.177000+01:00,https://sjobs.brassring.com/2057/ASP/TG/cim_jo...,gpt,40001153,False,2012-02-03 18:54:55.452000+01:00,['65000030'],['11002231'],"['BS', 'BL']",0b2f72d0-9625-4e0f-89f7-15d49d07af03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56937,surr_c285f10710a3494b5c08ff835c550496ea67e49c,SAP Senior consultant (EWM),Capgemini Suisse SA,Grossunternehmen,Geneva,<div><div style='padding:10.0px 0.0px;border:1...,2025-06-30 19:13:58.522000+02:00,https://www.capgemini.com/jobs/195134-en_GB_SA...,"ai, generative ai",40003260,False,NaN,['65000031'],['11002095'],['GE'],3753a14b-3cb1-46ea-b373-d74cc15c759d
56938,surr_3479df7ae00e76cab633d12076f0bac65273ebb9,Manager HR Strategy and Consulting,Capgemini Suisse SA,Grossunternehmen,Geneva,<div><div style='padding:10.0px 0.0px;border:1...,2025-06-30 19:13:58.524000+02:00,https://www.capgemini.com/jobs/239713-en_GB_SA...,"ai, generative ai",40003260,False,NaN,['65000031'],['11001460'],['GE'],3d0de251-3855-4a66-ab8b-610ad122d577
56939,surr_ebc7e95a9805e68f131afb895bd78d9e2ee199e1,Internship in Brand & Reputation Centre of Exc...,F. Hoffmann-La Roche AG,Grossunternehmen,"Basel, Basel-City","At Roche you can show up as yourself, embraced...",2025-06-30 19:54:05.823000+02:00,https://careers.roche.com/global/en/job/202506...,ai,40001150,False,2025-07-07 02:53:46.896000+02:00,['65000030'],NaN,['BS'],1c4ea457-dda6-4ebf-9193-27af12660458
56940,surr_1b59a877d7acf5098dc67012a5caecf58b80bf41,Developer Experience (DevX) Engineer (w/m/d) 4...,Schweizerische Mobiliar Versicherungsgesellsch...,Grossunternehmen,Bern,Stellenbeschreibung Jetzt bewerben\n\nDevelope...,2025-07-01 00:02:44.784000+02:00,https://jobs.mobiliar.ch/job/Developer-Experie...,ai,40003298,False,2025-08-11 16:04:31.706000+02:00,['65000041'],"['11001045', '11000699']",['BE'],084f5a75-aa44-45e1-b753-6197e4e35e8c
56941,surr_5421613b20dfc9e3444eb465be3211a9ff1dad80,Ispettore/trice finanziario/a a tempo parziale...,Cantone Ticino,Mittelunternehmen,Cantone Ticino Bellinzona,Repubblica e Cantone Ticino\nSezione delle ris...,2025-07-01 01:22:05.740000+02:00,https://www.concorsi.ti.ch/offerte-d'impieghi....,ai,40011534,False,2025-07-16 02:03:25.670000+02:00,['65000028'],['11002210'],['TI'],00f8151f-68fb-4bb4-be72-eab2dd8ebd28

In [43]:
len(df[df['x28_occupations'].isna()])/len(df)

0.07535738119490007

In [47]:
df_x28 = pd.read_csv('x28_cwalk.csv')
df_x28.tail(20)

      x28_code  isco_code
2546  11000624       9329
2547  11000766       9329
2548  11002222       9329
2549  11002226       9329
2550  11002655       9332
2551  11002357       9333
2552  11002372       9333
2553  11003074       9334
2554  11002358       9411
2555  11002565       9411
2556  11001814       9412
2557  11002236       9611
2558  11002944       9613
2559  11003117       9620
2560  11003209       9620
2561  11002491       9621
2562  11002728       9623
2563  11002874       9623
2564  11002698       9629
2565  11002746       9629

In [62]:
df = pd.read_csv('x28_codes.csv')
df.head(50)

,company_id,company_name,year,title,x28_occupations,x28_codes
0,40000008,DXC Technology Switzerland GmbH,2012,(Junior) Wireless Network Engineer (w/m),['11001015'],['11001015']
1,40000008,DXC Technology Switzerland GmbH,2012,Application Developer JAVA (m/w),['11000976'],['11000976']
2,40000008,DXC Technology Switzerland GmbH,2012,Business Analyst (m/w),['11000155'],['11000155']
3,40000008,DXC Technology Switzerland GmbH,2012,CH - Application Developer Java Application De...,['11000976'],['11000976']
4,40000008,DXC Technology Switzerland GmbH,2012,CH - Business Developer Life Sciences,['11000156'],['11000156']
5,40000008,DXC Technology Switzerland GmbH,2012,CH - Solution Architect mit Sales-Erfahrung (m/w),['11000965'],['11000965']
6,40000008,DXC Technology Switzerland GmbH,2012,CH- Project Manager (m/w),['11000224'],['11000224']
7,40000008,DXC Technology Switzerland GmbH,2012,CH- VIP Support Engineer (m/w),['11000974' '11002066'],"['11000974', '11002066']"
8,40000008,DXC Technology Switzerland GmbH,2012,CH-Business Architect Rail (m/w),['11000623'],['11000623']
9,40000008,DXC Technology Switzerland GmbH,2012,CH-Java Application Developer (w/m),['11000976'],['11000976']
10,40000008,DXC Technology Switzerland GmbH,2012,CH-Network Engineer Avaya Voice Specialist Con...,['11001015' '11001504'],"['11001015', '11001504']"
11,40000008,DXC Technology Switzerland GmbH,2012,Ch - Functional Coordinator (m/w),['11000980'],['11000980']
12,40000008,DXC Technology Switzerland GmbH,2012,Consultant / Berater / (Teil-) Projektleiter i...,['11000066' '11000228'],"['11000066', '11000228']"
13,40000008,DXC Technology Switzerland GmbH,2012,Financial Controller (f/m),['11000344'],['11000344']
14,40000008,DXC Technology Switzerland GmbH,2012,IT Service Center Support Engineer (m/w),['11000974' '11002066'],"['11000974', '11002066']"
15,40000008,DXC Technology Switzerland GmbH,2012,IT Solution Architekt mit Sales Affinität (w/m),['11000965'],['11000965']
16,40000008,DXC Technology Switzerland GmbH,2012,IT-Architekt (w/m),['11000975'],['11000975']
17,40000008,DXC Technology Switzerland GmbH,2012,IT-Projektleiter (w/m),['11000939'],['11000939']
18,40000008,DXC Technology Switzerland GmbH,2012,Information Security Analyst Identity & Access...,['11000970'],['11000970']
19,40000008,DXC Technology Switzerland GmbH,2012,Information System Architect (m/w),['11000975'],['11000975']
20,40000008,DXC Technology Switzerland GmbH,2012,JAVA Application Architect (m/w),['11000976'],['11000976']
21,40000008,DXC Technology Switzerland GmbH,2012,Java Application Architect (w/m),['11000976'],['11000976']
22,40000008,DXC Technology Switzerland GmbH,2012,Java Application Developer mit Schwerpunkt Fil...,['11000976'],['11000976']
23,40000008,DXC Technology Switzerland GmbH,2012,Junior/Senior Business Analyst mit Schwerpunkt...,['11002179'],['11002179']
24,40000008,DXC Technology Switzerland GmbH,2012,Kaufmännischer Sachbearbeiter / Billing Specia...,['11000034' '11000317'],"['11000034', '11000317']"
25,40000008,DXC Technology Switzerland GmbH,2012,Mehrere Business Consultants / Senior Consulta...,['11000255'],['11000255']
26,40000008,DXC Technology Switzerland GmbH,2012,Microsoft Application Architect (w/m),['11001045'],['11001045']
27,40000008,DXC Technology Switzerland GmbH,2012,Network Engineer (w/m) - Engineering Secure Co...,['11001015'],['11001015']
28,40000008,DXC Technology Switzerland GmbH,2012,Network Engineer (w/m) - Engineering Secure Co...,['11001015'],['11001015']
29,40000008,DXC Technology Switzerland GmbH,2012,SAP Solution Architekt für den Ausbau unser SA...,['11002063'],['11002063']
30,40000008,DXC Technology Switzerland GmbH,2012,Senior SharePoint Developer / Architekt (m/w),['11001042' '11000596'],"['11001042', '11000596']"
31,40000008,DXC Technology Switzerland GmbH,2012,Solution Architect (w/m),['11000965'],['11000965']
32,40000008,DXC Technology Switzerland GmbH,2012,System Architect (w/m),['11000975'],['11000975']
33,40000008,DXC Technology Switzerland GmbH,2012,System Engineer - Avaya Operations (w/m),['11000811'],['11000811']
34,40000008,DXC Technology Switzerland GmbH,2012,System Engineer – Avaya Operations (w/m),['11000811'],['11000811']
35,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCCM - ConfigMgr,['11000992' '11001563'],"['11000992', '11001563']"
36,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCO - Opalis - Orchestr...,['11001563'],['11001563']
37,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCO – Opalis - Orchestr...,['11001563'],['11001563']
38,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCOM - OpsMgr (m/w),['11001563'],['11001563']
39,40000008,DXC Technology Switzerland GmbH,2012,Traineeprogramm – Ihr Einstieg in die IT (w/m),['11001931'],['11001931']
40,40000008,DXC Technology Switzerland GmbH,2013,(Junior) Wireless Network Engineer (w/m),['11001015'],['11001015']
41,40000008,DXC Technology Switzerland GmbH,2013,Application Developer JAVA (m/w),['11000976'],['11000976']
42,40000008,DXC Technology Switzerland GmbH,2013,Avaya Call Center Specialist,['11001504'],['11001504']
43,40000008,DXC Technology Switzerland GmbH,2013,Business Analyst,['11000155'],['11000155']
44,40000008,DXC Technology Switzerland GmbH,2013,Business Analyst (m/w),['11000155'],['11000155']
45,40000008,DXC Technology Switzerland GmbH,2013,Business Consultant,['11000255'],['11000255']
46,40000008,DXC Technology Switzerland GmbH,2013,CH - Application Developer Java Application De...,['11000976'],['11000976']
47,40000008,DXC Technology Switzerland GmbH,2013,CH - Business Developer Life Sciences,['11000156'],['11000156']
48,40000008,DXC Technology Switzerland GmbH,2013,CH - Business Developer Life Sciences (M/W) - ...,['11000156'],['11000156']
49,40000008,DXC Technology Switzerland GmbH,2013,CH - Solution Architect mit Sales-Erfahrung (m/w),['11000965'],['11000965']

In [63]:
def parse_x28_occupations(x28_str):
    """Parse X28 occupations field into list of clean strings"""
    # Handle PostgreSQL arrays (which come as numpy arrays or lists)
    if hasattr(x28_str, '__iter__') and not isinstance(x28_str, str):
        # It's already an array/list from PostgreSQL
        return [str(x).strip() for x in x28_str if x and str(x).strip()]

    # Handle null/empty values (but only for strings)
    try:
        if not x28_str or pd.isna(x28_str) or str(x28_str).strip() in ('', 'null', 'None'):
            return []
    except ValueError:
        # If we get here, x28_str is likely an array that wasn't caught above
        if hasattr(x28_str, '__len__') and len(x28_str) == 0:
            return []
        # For non-empty arrays, convert to string list
        return [str(x).strip() for x in x28_str if x and str(x).strip()]

    x28_str = str(x28_str).strip()

    # Handle JSON-style arrays: ['123', '456'] or ["123", "456"]
    if x28_str.startswith('[') and x28_str.endswith(']'):
        try:
            # Try JSON parsing first
            parsed = json.loads(x28_str)
            if isinstance(parsed, list):
                return [str(x).strip().strip('\'"') for x in parsed if x]
        except:
            # Fallback: manual parsing for space-separated or comma-separated values
            x28_str = x28_str[1:-1]  # Remove brackets

            # Split by comma first, then by space for each part
            codes = []
            for part in x28_str.split(','):
                part = part.strip().strip('\'"')
                if part:
                    # Handle space-separated codes within this part
                    for code in part.split():
                        code = code.strip().strip('\'"')
                        if code:
                            codes.append(code)

            # If no comma-separated values found, try space-separated
            if not codes:
                for code in x28_str.split():
                    code = code.strip().strip('\'"')
                    if code:
                        codes.append(code)

            return codes

    # Handle comma-separated values
    codes = []
    for code in x28_str.split(','):
        code = code.strip().strip('\'"')
        if code:
            # Also handle space-separated codes within each comma-separated part
            for subcode in code.split():
                subcode = subcode.strip().strip('\'"')
                if subcode:
                    codes.append(subcode)

    return codes
    


df_j = df.head(50)
df_j['x28_codes'] = df_j['x28_occupations'].apply(parse_x28_occupations)
df_jobs_exploded = df_j.explode('x28_codes').reset_index(drop=True)

df_jobs_exploded

/var/folders/3p/bkhpj5cj7p77ghh4hx0hz_cw0000gn/T/ipykernel_76729/1808273318.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_j['x28_codes'] = df_j['x28_occupations'].apply(parse_x28_occupations)

,company_id,company_name,year,title,x28_occupations,x28_codes
0,40000008,DXC Technology Switzerland GmbH,2012,(Junior) Wireless Network Engineer (w/m),['11001015'],11001015
1,40000008,DXC Technology Switzerland GmbH,2012,Application Developer JAVA (m/w),['11000976'],11000976
2,40000008,DXC Technology Switzerland GmbH,2012,Business Analyst (m/w),['11000155'],11000155
3,40000008,DXC Technology Switzerland GmbH,2012,CH - Application Developer Java Application De...,['11000976'],11000976
4,40000008,DXC Technology Switzerland GmbH,2012,CH - Business Developer Life Sciences,['11000156'],11000156
5,40000008,DXC Technology Switzerland GmbH,2012,CH - Solution Architect mit Sales-Erfahrung (m/w),['11000965'],11000965
6,40000008,DXC Technology Switzerland GmbH,2012,CH- Project Manager (m/w),['11000224'],11000224
7,40000008,DXC Technology Switzerland GmbH,2012,CH- VIP Support Engineer (m/w),['11000974' '11002066'],11000974
8,40000008,DXC Technology Switzerland GmbH,2012,CH- VIP Support Engineer (m/w),['11000974' '11002066'],11002066
9,40000008,DXC Technology Switzerland GmbH,2012,CH-Business Architect Rail (m/w),['11000623'],11000623
10,40000008,DXC Technology Switzerland GmbH,2012,CH-Java Application Developer (w/m),['11000976'],11000976
11,40000008,DXC Technology Switzerland GmbH,2012,CH-Network Engineer Avaya Voice Specialist Con...,['11001015' '11001504'],11001015
12,40000008,DXC Technology Switzerland GmbH,2012,CH-Network Engineer Avaya Voice Specialist Con...,['11001015' '11001504'],11001504
13,40000008,DXC Technology Switzerland GmbH,2012,Ch - Functional Coordinator (m/w),['11000980'],11000980
14,40000008,DXC Technology Switzerland GmbH,2012,Consultant / Berater / (Teil-) Projektleiter i...,['11000066' '11000228'],11000066
15,40000008,DXC Technology Switzerland GmbH,2012,Consultant / Berater / (Teil-) Projektleiter i...,['11000066' '11000228'],11000228
16,40000008,DXC Technology Switzerland GmbH,2012,Financial Controller (f/m),['11000344'],11000344
17,40000008,DXC Technology Switzerland GmbH,2012,IT Service Center Support Engineer (m/w),['11000974' '11002066'],11000974
18,40000008,DXC Technology Switzerland GmbH,2012,IT Service Center Support Engineer (m/w),['11000974' '11002066'],11002066
19,40000008,DXC Technology Switzerland GmbH,2012,IT Solution Architekt mit Sales Affinität (w/m),['11000965'],11000965
20,40000008,DXC Technology Switzerland GmbH,2012,IT-Architekt (w/m),['11000975'],11000975
21,40000008,DXC Technology Switzerland GmbH,2012,IT-Projektleiter (w/m),['11000939'],11000939
22,40000008,DXC Technology Switzerland GmbH,2012,Information Security Analyst Identity & Access...,['11000970'],11000970
23,40000008,DXC Technology Switzerland GmbH,2012,Information System Architect (m/w),['11000975'],11000975
24,40000008,DXC Technology Switzerland GmbH,2012,JAVA Application Architect (m/w),['11000976'],11000976
25,40000008,DXC Technology Switzerland GmbH,2012,Java Application Architect (w/m),['11000976'],11000976
26,40000008,DXC Technology Switzerland GmbH,2012,Java Application Developer mit Schwerpunkt Fil...,['11000976'],11000976
27,40000008,DXC Technology Switzerland GmbH,2012,Junior/Senior Business Analyst mit Schwerpunkt...,['11002179'],11002179
28,40000008,DXC Technology Switzerland GmbH,2012,Kaufmännischer Sachbearbeiter / Billing Specia...,['11000034' '11000317'],11000034
29,40000008,DXC Technology Switzerland GmbH,2012,Kaufmännischer Sachbearbeiter / Billing Specia...,['11000034' '11000317'],11000317
30,40000008,DXC Technology Switzerland GmbH,2012,Mehrere Business Consultants / Senior Consulta...,['11000255'],11000255
31,40000008,DXC Technology Switzerland GmbH,2012,Microsoft Application Architect (w/m),['11001045'],11001045
32,40000008,DXC Technology Switzerland GmbH,2012,Network Engineer (w/m) - Engineering Secure Co...,['11001015'],11001015
33,40000008,DXC Technology Switzerland GmbH,2012,Network Engineer (w/m) - Engineering Secure Co...,['11001015'],11001015
34,40000008,DXC Technology Switzerland GmbH,2012,SAP Solution Architekt für den Ausbau unser SA...,['11002063'],11002063
35,40000008,DXC Technology Switzerland GmbH,2012,Senior SharePoint Developer / Architekt (m/w),['11001042' '11000596'],11001042
36,40000008,DXC Technology Switzerland GmbH,2012,Senior SharePoint Developer / Architekt (m/w),['11001042' '11000596'],11000596
37,40000008,DXC Technology Switzerland GmbH,2012,Solution Architect (w/m),['11000965'],11000965
38,40000008,DXC Technology Switzerland GmbH,2012,System Architect (w/m),['11000975'],11000975
39,40000008,DXC Technology Switzerland GmbH,2012,System Engineer - Avaya Operations (w/m),['11000811'],11000811
40,40000008,DXC Technology Switzerland GmbH,2012,System Engineer – Avaya Operations (w/m),['11000811'],11000811
41,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCCM - ConfigMgr,['11000992' '11001563'],11000992
42,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCCM - ConfigMgr,['11000992' '11001563'],11001563
43,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCO - Opalis - Orchestr...,['11001563'],11001563
44,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCO – Opalis - Orchestr...,['11001563'],11001563
45,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCOM - OpsMgr (m/w),['11001563'],11001563
46,40000008,DXC Technology Switzerland GmbH,2012,Traineeprogramm – Ihr Einstieg in die IT (w/m),['11001931'],11001931
47,40000008,DXC Technology Switzerland GmbH,2013,(Junior) Wireless Network Engineer (w/m),['11001015'],11001015
48,40000008,DXC Technology Switzerland GmbH,2013,Application Developer JAVA (m/w),['11000976'],11000976
49,40000008,DXC Technology Switzerland GmbH,2013,Avaya Call Center Specialist,['11001504'],11001504
50,40000008,DXC Technology Switzerland GmbH,2013,Business Analyst,['11000155'],11000155
51,40000008,DXC Technology Switzerland GmbH,2013,Business Analyst (m/w),['11000155'],11000155
52,40000008,DXC Technology Switzerland GmbH,2013,Business Consultant,['11000255'],11000255
53,40000008,DXC Technology Switzerland GmbH,2013,CH - Application Developer Java Application De...,['11000976'],11000976
54,40000008,DXC Technology Switzerland GmbH,2013,CH - Business Developer Life Sciences,['11000156'],11000156
55,40000008,DXC Technology Switzerland GmbH,2013,CH - Business Developer Life Sciences (M/W) - ...,['11000156'],11000156
56,40000008,DXC Technology Switzerland GmbH,2013,CH - Solution Architect mit Sales-Erfahrung (m/w),['11000965'],11000965

In [74]:
non_int_mask = pd.to_numeric(df_jobs_exploded['x28_codes'], errors='coerce').isna()
non_int_count = non_int_mask.sum()
non_int_count

0

In [70]:
df_j['x28_codes'].astype(int)

ValueError: setting an array element with a sequence.

In [59]:
def parse_x28_occupations(x28_str):
    """Parse X28 occupations field into list of clean strings"""
    # Handle PostgreSQL arrays (which come as numpy arrays or lists)
    if hasattr(x28_str, '__iter__') and not isinstance(x28_str, str):
        # It's already an array/list from PostgreSQL
        return [str(x).strip() for x in x28_str if x and str(x).strip()]

    # Handle null/empty values (but only for strings)
    try:
        if not x28_str or pd.isna(x28_str) or str(x28_str).strip() in ('', 'null', 'None'):
            return []
    except ValueError:
        # If we get here, x28_str is likely an array that wasn't caught above
        if hasattr(x28_str, '__len__') and len(x28_str) == 0:
            return []
        # For non-empty arrays, convert to string list
        return [str(x).strip() for x in x28_str if x and str(x).strip()]

    x28_str = str(x28_str).strip()

    # Handle JSON-style arrays: ['123', '456'] or ["123", "456"]
    if x28_str.startswith('[') and x28_str.endswith(']'):
        try:
            # Try JSON parsing first
            parsed = json.loads(x28_str)
            if isinstance(parsed, list):
                return [str(x).strip().strip('\'"') for x in parsed if x]
        except:
            # Fallback: manual parsing for space-separated or comma-separated values
            x28_str = x28_str[1:-1]  # Remove brackets

            # Split by comma first, then by space for each part
            codes = []
            for part in x28_str.split(','):
                part = part.strip().strip('\'"')
                if part:
                    # Handle space-separated codes within this part
                    for code in part.split():
                        code = code.strip().strip('\'"')
                        if code:
                            codes.append(code)

            # If no comma-separated values found, try space-separated
            if not codes:
                for code in x28_str.split():
                    code = code.strip().strip('\'"')
                    if code:
                        codes.append(code)

            return codes

    # Handle comma-separated values
    codes = []
    for code in x28_str.split(','):
        code = code.strip().strip('\'"')
        if code:
            # Also handle space-separated codes within each comma-separated part
            for subcode in code.split():
                subcode = subcode.strip().strip('\'"')
                if subcode:
                    codes.append(subcode)

    return codes

In [75]:
import pandas as pd
df['x28_codes'] = df['x28_occupations'].apply(parse_x28_occupations)
# assuming df is your DataFrame
non_int_mask = pd.to_numeric(df['x28_codes'], errors='coerce').isna()
non_int_count = non_int_mask.sum()

print(f"Number of non-integer rows in x28_codes: {non_int_count}")
non_int_rows = df[non_int_mask]
print(non_int_rows)

Number of non-integer rows in x28_codes: 19001253
          company_id                     company_name  year  \
0           40000008  DXC Technology Switzerland GmbH  2012
1           40000008  DXC Technology Switzerland GmbH  2012
2           40000008  DXC Technology Switzerland GmbH  2012
3           40000008  DXC Technology Switzerland GmbH  2012
4           40000008  DXC Technology Switzerland GmbH  2012
...              ...                              ...   ...
19001248    40194821    Burson Cohn & Wolfe Sports SA  2024
19001249    40194821    Burson Cohn & Wolfe Sports SA  2025
19001250    40194962                      TerreVision  2023
19001251    40194962                      TerreVision  2024
19001252    40194962                      TerreVision  2025

                                                      title x28_occupations  \
0                  (Junior) Wireless Network Engineer (w/m)    ['11001015']
1                          Application Developer JAVA (m/w)    ['11000976']
2                                    Business Analyst (m/w)    ['11000155']
3         CH - Application Developer Java Application De...    ['11000976']
4                     CH - Business Developer Life Sciences    ['11000156']
...                                                     ...             ...
19001248                             Account Executive 100%    ['11001559']
19001249                             Account Executive 100%    ['11001559']
19001250                 Verwaltung der Geschäftsstelle 20%             NaN
19001251                 Verwaltung der Geschäftsstelle 20%             NaN
19001252                 Verwaltung der Geschäftsstelle 20%             NaN

           x28_codes
0         [11001015]
1         [11000976]
2         [11000155]
3         [11000976]
4         [11000156]
...              ...
19001248  [11001559]
19001249  [11001559]
19001250          []
19001251          []
19001252          []

[19001253 rows x 6 columns]

In [76]:
list_like = df[df['x28_codes'].astype(str).str.startswith('[', na=False)]
print(f"Found {len(list_like)} rows that still start with '['")
if len(list_like) > 0:
    print(list_like['x28_codes'].head())

Found 19001253 rows that still start with '['
0    [11001015]
1    [11000976]
2    [11000155]
3    [11000976]
4    [11000156]
Name: x28_codes, dtype: object

In [77]:
non_int_rows.head(50)

,company_id,company_name,year,title,x28_occupations,x28_codes
0,40000008,DXC Technology Switzerland GmbH,2012,(Junior) Wireless Network Engineer (w/m),['11001015'],[11001015]
1,40000008,DXC Technology Switzerland GmbH,2012,Application Developer JAVA (m/w),['11000976'],[11000976]
2,40000008,DXC Technology Switzerland GmbH,2012,Business Analyst (m/w),['11000155'],[11000155]
3,40000008,DXC Technology Switzerland GmbH,2012,CH - Application Developer Java Application De...,['11000976'],[11000976]
4,40000008,DXC Technology Switzerland GmbH,2012,CH - Business Developer Life Sciences,['11000156'],[11000156]
5,40000008,DXC Technology Switzerland GmbH,2012,CH - Solution Architect mit Sales-Erfahrung (m/w),['11000965'],[11000965]
6,40000008,DXC Technology Switzerland GmbH,2012,CH- Project Manager (m/w),['11000224'],[11000224]
7,40000008,DXC Technology Switzerland GmbH,2012,CH- VIP Support Engineer (m/w),['11000974' '11002066'],"[11000974, 11002066]"
8,40000008,DXC Technology Switzerland GmbH,2012,CH-Business Architect Rail (m/w),['11000623'],[11000623]
9,40000008,DXC Technology Switzerland GmbH,2012,CH-Java Application Developer (w/m),['11000976'],[11000976]
10,40000008,DXC Technology Switzerland GmbH,2012,CH-Network Engineer Avaya Voice Specialist Con...,['11001015' '11001504'],"[11001015, 11001504]"
11,40000008,DXC Technology Switzerland GmbH,2012,Ch - Functional Coordinator (m/w),['11000980'],[11000980]
12,40000008,DXC Technology Switzerland GmbH,2012,Consultant / Berater / (Teil-) Projektleiter i...,['11000066' '11000228'],"[11000066, 11000228]"
13,40000008,DXC Technology Switzerland GmbH,2012,Financial Controller (f/m),['11000344'],[11000344]
14,40000008,DXC Technology Switzerland GmbH,2012,IT Service Center Support Engineer (m/w),['11000974' '11002066'],"[11000974, 11002066]"
15,40000008,DXC Technology Switzerland GmbH,2012,IT Solution Architekt mit Sales Affinität (w/m),['11000965'],[11000965]
16,40000008,DXC Technology Switzerland GmbH,2012,IT-Architekt (w/m),['11000975'],[11000975]
17,40000008,DXC Technology Switzerland GmbH,2012,IT-Projektleiter (w/m),['11000939'],[11000939]
18,40000008,DXC Technology Switzerland GmbH,2012,Information Security Analyst Identity & Access...,['11000970'],[11000970]
19,40000008,DXC Technology Switzerland GmbH,2012,Information System Architect (m/w),['11000975'],[11000975]
20,40000008,DXC Technology Switzerland GmbH,2012,JAVA Application Architect (m/w),['11000976'],[11000976]
21,40000008,DXC Technology Switzerland GmbH,2012,Java Application Architect (w/m),['11000976'],[11000976]
22,40000008,DXC Technology Switzerland GmbH,2012,Java Application Developer mit Schwerpunkt Fil...,['11000976'],[11000976]
23,40000008,DXC Technology Switzerland GmbH,2012,Junior/Senior Business Analyst mit Schwerpunkt...,['11002179'],[11002179]
24,40000008,DXC Technology Switzerland GmbH,2012,Kaufmännischer Sachbearbeiter / Billing Specia...,['11000034' '11000317'],"[11000034, 11000317]"
25,40000008,DXC Technology Switzerland GmbH,2012,Mehrere Business Consultants / Senior Consulta...,['11000255'],[11000255]
26,40000008,DXC Technology Switzerland GmbH,2012,Microsoft Application Architect (w/m),['11001045'],[11001045]
27,40000008,DXC Technology Switzerland GmbH,2012,Network Engineer (w/m) - Engineering Secure Co...,['11001015'],[11001015]
28,40000008,DXC Technology Switzerland GmbH,2012,Network Engineer (w/m) - Engineering Secure Co...,['11001015'],[11001015]
29,40000008,DXC Technology Switzerland GmbH,2012,SAP Solution Architekt für den Ausbau unser SA...,['11002063'],[11002063]
30,40000008,DXC Technology Switzerland GmbH,2012,Senior SharePoint Developer / Architekt (m/w),['11001042' '11000596'],"[11001042, 11000596]"
31,40000008,DXC Technology Switzerland GmbH,2012,Solution Architect (w/m),['11000965'],[11000965]
32,40000008,DXC Technology Switzerland GmbH,2012,System Architect (w/m),['11000975'],[11000975]
33,40000008,DXC Technology Switzerland GmbH,2012,System Engineer - Avaya Operations (w/m),['11000811'],[11000811]
34,40000008,DXC Technology Switzerland GmbH,2012,System Engineer – Avaya Operations (w/m),['11000811'],[11000811]
35,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCCM - ConfigMgr,['11000992' '11001563'],"[11000992, 11001563]"
36,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCO - Opalis - Orchestr...,['11001563'],[11001563]
37,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCO – Opalis - Orchestr...,['11001563'],[11001563]
38,40000008,DXC Technology Switzerland GmbH,2012,Technischer Consultant SCOM - OpsMgr (m/w),['11001563'],[11001563]
39,40000008,DXC Technology Switzerland GmbH,2012,Traineeprogramm – Ihr Einstieg in die IT (w/m),['11001931'],[11001931]
40,40000008,DXC Technology Switzerland GmbH,2013,(Junior) Wireless Network Engineer (w/m),['11001015'],[11001015]
41,40000008,DXC Technology Switzerland GmbH,2013,Application Developer JAVA (m/w),['11000976'],[11000976]
42,40000008,DXC Technology Switzerland GmbH,2013,Avaya Call Center Specialist,['11001504'],[11001504]
43,40000008,DXC Technology Switzerland GmbH,2013,Business Analyst,['11000155'],[11000155]
44,40000008,DXC Technology Switzerland GmbH,2013,Business Analyst (m/w),['11000155'],[11000155]
45,40000008,DXC Technology Switzerland GmbH,2013,Business Consultant,['11000255'],[11000255]
46,40000008,DXC Technology Switzerland GmbH,2013,CH - Application Developer Java Application De...,['11000976'],[11000976]
47,40000008,DXC Technology Switzerland GmbH,2013,CH - Business Developer Life Sciences,['11000156'],[11000156]
48,40000008,DXC Technology Switzerland GmbH,2013,CH - Business Developer Life Sciences (M/W) - ...,['11000156'],[11000156]
49,40000008,DXC Technology Switzerland GmbH,2013,CH - Solution Architect mit Sales-Erfahrung (m/w),['11000965'],[11000965]

In [2]:
import pandas as pd
df_task = pd.read_excel('Data/Task Statements.xlsx')
df_task

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
0,11-1011.00,Chief Executives,8823,Direct or coordinate an organization's financi...,Core,87.0,07/2014,Incumbent
1,11-1011.00,Chief Executives,8831,Appoint department heads or managers and assig...,Core,87.0,07/2014,Incumbent
2,11-1011.00,Chief Executives,8825,Analyze operations to evaluate performance of ...,Core,87.0,07/2014,Incumbent
3,11-1011.00,Chief Executives,8826,"Direct, plan, or implement policies, objective...",Core,87.0,07/2014,Incumbent
4,11-1011.00,Chief Executives,8827,"Prepare budgets for approval, including those ...",Core,87.0,07/2014,Incumbent
...,...,...,...,...,...,...,...,...
19226,53-7121.00,"Tank Car, Truck, and Ship Loaders",12807,Unload cars containing liquids by connecting h...,Supplemental,85.0,08/2019,Incumbent
19227,53-7121.00,"Tank Car, Truck, and Ship Loaders",12804,"Clean interiors of tank cars or tank trucks, u...",Supplemental,85.0,08/2019,Incumbent
19228,53-7121.00,"Tank Car, Truck, and Ship Loaders",12803,Lower gauge rods into tanks or read meters to ...,Supplemental,85.0,08/2019,Incumbent
19229,53-7121.00,"Tank Car, Truck, and Ship Loaders",12805,Operate conveyors and equipment to transfer gr...,Supplemental,85.0,08/2019,Incumbent
19230,53-7121.00,"Tank Car, Truck, and Ship Loaders",12810,"Perform general warehouse activities, such as ...",Supplemental,85.0,08/2019,Incumbent

In [4]:
df_ad = df_task[df_task['Title'] == 'Advertising and Promotions Managers']

df_ad[df_ad['Task Type'] == 'Core']

,O*NET-SOC Code,Title,Task ID,Task,Task Type,Incumbents Responding,Date,Domain Source
96,11-2011.00,Advertising and Promotions Managers,3224,Plan and prepare advertising and promotional m...,Core,73.0,08/2018,Incumbent
97,11-2011.00,Advertising and Promotions Managers,3226,Inspect layouts and advertising copy and edit ...,Core,72.0,08/2018,Incumbent
98,11-2011.00,Advertising and Promotions Managers,3231,Confer with department heads or staff to discu...,Core,72.0,08/2018,Incumbent
99,11-2011.00,Advertising and Promotions Managers,3242,Coordinate with the media to disseminate adver...,Core,71.0,08/2018,Incumbent
100,11-2011.00,Advertising and Promotions Managers,3227,"Coordinate activities of departments, such as ...",Core,71.0,08/2018,Incumbent
101,11-2011.00,Advertising and Promotions Managers,3238,Plan and execute advertising policies and stra...,Core,71.0,08/2018,Incumbent
102,11-2011.00,Advertising and Promotions Managers,3237,"Direct, motivate, and monitor the mobilization...",Core,72.0,08/2018,Incumbent
103,11-2011.00,Advertising and Promotions Managers,3223,Prepare budgets and submit estimates for progr...,Core,71.0,08/2018,Incumbent
104,11-2011.00,Advertising and Promotions Managers,3243,Contact organizations to explain services and ...,Core,74.0,08/2018,Incumbent
105,11-2011.00,Advertising and Promotions Managers,3233,Monitor and analyze sales promotion results to...,Core,71.0,08/2018,Incumbent
106,11-2011.00,Advertising and Promotions Managers,3229,Identify and develop contacts for promotional ...,Core,73.0,08/2018,Incumbent
107,11-2011.00,Advertising and Promotions Managers,3239,"Track program budgets, expenses, and campaign ...",Core,72.0,08/2018,Incumbent
108,11-2011.00,Advertising and Promotions Managers,3234,Read trade journals and professional literatur...,Core,72.0,08/2018,Incumbent

In [10]:
df_task_app = pd.read_csv('Data/task_app_matches.csv')
company_data = pd.read_csv('Data/ai_development_training_companies_200_jobs.csv')
df_expanded = pd.read_csv('Data/expanded_jobs_matching.csv')
df_job_app = pd.read_csv('Data/job_app_mapping.csv')

In [6]:
df_task_app

,app_text,onet_task_id,onet_task,similarity,cross_encoder_score
0,detect anomalies in energy consumption time-se...,3683,Monitor and analyze energy consumption.,0.785815,0.998259
1,produce interactive visualizations that presen...,10710,Conduct presentations of analytic findings.,0.681055,0.996358
2,assign employee-specific mandatory training mo...,12118,Assign employees to specific duties.,0.713157,0.995667
3,detect and classify surface defects on watch c...,3992,Inspect parts for surface defects.,0.738975,0.994626
4,detect anomalies in energy consumption time-se...,17963,Monitor equipment operation to detect malfunct...,0.747001,0.994358
...,...,...,...,...,...
1222,forecast future overall traffic volumes from h...,2538,Conduct historical analyses of test results.,0.574146,0.601311
1223,optimize real-time control set-points for dece...,2352,Adjust network sizes to meet volume or capacit...,0.631738,0.600440
1224,assign employee-specific mandatory training mo...,1129,Direct the development or implementation of po...,0.682067,0.600337
1225,detect and flag deviations from expected opera...,7867,Test equipment to ensure proper operation.,0.689896,0.600318
1226,assign employee-specific mandatory training mo...,1101,Train staff in regulatory policies or procedures.,0.692885,0.600300

In [7]:
df_expanded

,app_text,job_uid,company_name,x28_occupations,x28_industries,year,tst_created,first_occurrence_tst_created,provenance_job_uids
0,aggregate and normalize data records pulled fr...,fe2ec994-3665-44dd-a540-6c1ba96c29eb,CKW AG,[],['65000007'],2024,NaN,2024-09-13 12:46:32.673000+02:00,fe2ec994-3665-44dd-a540-6c1ba96c29eb
1,aggregate and output a unified raw dataset tha...,9a9254ed-c57e-4028-9264-6b80823f94a5,CKW AG,['11000888'],['65000007'],2023,NaN,2023-03-30 11:08:28.473000+02:00,9a9254ed-c57e-4028-9264-6b80823f94a5
2,aggregate and transform petabyte-scale raw dat...,98b96b27-0c44-443c-acac-3957458c30f7,Innovation Process Technology AG,['11000066'],['65000019'],2019,NaN,2019-07-16 03:02:01.947000+02:00,98b96b27-0c44-443c-acac-3957458c30f7
3,aggregate decentralized flexibility assets—suc...,a202eb29-fa42-415e-b22f-9fc7e57dd28b,CKW AG,[],['65000007'],2024,NaN,2024-07-17 19:55:37.818000+02:00,a202eb29-fa42-415e-b22f-9fc7e57dd28b
4,aggregate decentralized parameter updates from...,4d3c7506-5753-44af-87ad-f374954db900,Innovation Process Technology AG,['11000879'],['65000019'],2019,NaN,2019-06-27 00:35:00.581000+02:00,4d3c7506-5753-44af-87ad-f374954db900
...,...,...,...,...,...,...,...,...,...
587,visualize detected patterns and model results ...,a956f957-f910-4173-b48b-197cd0d8a909,Innovation Process Technology AG,['11000622'],['65000019'],2020,NaN,2020-04-28 19:04:43.611000+02:00,a956f957-f910-4173-b48b-197cd0d8a909
588,visualize interactive business-intelligence da...,4a726393-e8a7-4476-9c43-e91d42dd509b,Bison Schweiz AG,"['11000965', '11001926', '11000881']",['65000019'],2023,NaN,2023-06-09 10:13:05.405000+02:00,4a726393-e8a7-4476-9c43-e91d42dd509b
589,visualize sensory-analysis results in interact...,84bfc7cb-a8ea-460a-b50b-676f3a12d384,"Manufacture Jaeger-LeCoultre, Branch of Richem...",['11000785'],"['65000037', '65000006']",2025,NaN,2025-05-16 09:52:25.338000+02:00,84bfc7cb-a8ea-460a-b50b-676f3a12d384
590,visualize structured financial data as interac...,0f7221e3-7463-4f9c-bfcf-364a9f21022e,"Manufacture Jaeger-LeCoultre, Branch of Richem...","['11000058', '11000081']","['65000037', '65000006']",2024,NaN,2024-07-29 14:45:05.929000+02:00,0f7221e3-7463-4f9c-bfcf-364a9f21022e
591,visualize system-derived insights in interacti...,c9ac2369-88c6-42a7-8f28-af45cd68e356,Union des Associations Européennes de Football...,['11000879'],['65000034'],2023,NaN,2023-11-22 19:16:21.510000+01:00,c9ac2369-88c6-42a7-8f28-af45cd68e356

In [9]:
df_job_app

,app_text,job_uids,num_jobs,first_occurrence_tst_created
0,aggregate and normalize data records pulled fr...,fe2ec994-3665-44dd-a540-6c1ba96c29eb,1,2024-09-13 12:46:32.673000+02:00
1,aggregate and output a unified raw dataset tha...,9a9254ed-c57e-4028-9264-6b80823f94a5,1,2023-03-30 11:08:28.473000+02:00
2,aggregate and transform petabyte-scale raw dat...,98b96b27-0c44-443c-acac-3957458c30f7,1,2019-07-16 03:02:01.947000+02:00
3,aggregate decentralized flexibility assets—suc...,a202eb29-fa42-415e-b22f-9fc7e57dd28b,1,2024-07-17 19:55:37.818000+02:00
4,aggregate decentralized parameter updates from...,4d3c7506-5753-44af-87ad-f374954db900,1,2019-06-27 00:35:00.581000+02:00
...,...,...,...,...
587,visualize detected patterns and model results ...,a956f957-f910-4173-b48b-197cd0d8a909,1,2020-04-28 19:04:43.611000+02:00
588,visualize interactive business-intelligence da...,4a726393-e8a7-4476-9c43-e91d42dd509b,1,2023-06-09 10:13:05.405000+02:00
589,visualize sensory-analysis results in interact...,84bfc7cb-a8ea-460a-b50b-676f3a12d384,1,2025-05-16 09:52:25.338000+02:00
590,visualize structured financial data as interac...,0f7221e3-7463-4f9c-bfcf-364a9f21022e,1,2024-07-29 14:45:05.929000+02:00
591,visualize system-derived insights in interacti...,c9ac2369-88c6-42a7-8f28-af45cd68e356,1,2023-11-22 19:16:21.510000+01:00

In [11]:
company_data

,uid,title,company_name,company_size,location_raw,content_clean,tst_created,url,matched_keywords,company_id,company_is_recruiter,tst_deleted,x28_industries,x28_occupations,cantons,duplicate_group
0,ec784831-e715-4cdf-bc1a-1e8b8adb77eb,Senior System-Spezialistin / Senior System Spe...,Eidgenössisches Justiz- und Polizeidepartement...,Kleinunternehmen,Bern,Eidgenössisches Justiz- und \nPolizeideparteme...,2014-09-15 22:21:16+02:00,http://direktlink.prospective.ch/?view=79ADE53...,gsm,40016150,False,2014-11-12 00:34:36+01:00,['65000028'],"['11001061', '11000819']",['BE'],NaN
1,f26af5d2-dbe3-4d12-a677-fe7c1f90d902,System-Spezialistin / System-Spezialist Telema...,Eidgenössisches Justiz- und Polizeidepartement...,Kleinunternehmen,Bern,Eidgenössisches Justiz- und \nPolizeideparteme...,2014-11-24 00:11:09+01:00,http://direktlink.prospective.ch/?view=D27C827...,gsm,40016150,False,2014-12-09 00:20:03+01:00,['65000028'],"['11001061', '11000819']",['BE'],01278d5b-ccb5-43c1-a0f4-9fb645d16bdb
2,e2a2ebc9-464c-4bbd-b0a2-8fa828e87084,Senior System Spezialistin / Senior System-Spe...,Eidgenössisches Justiz- und Polizeidepartement...,Kleinunternehmen,Bern,Eidgenössisches Justiz- und \nPolizeideparteme...,2015-06-22 00:19:22+02:00,http://direktlink.prospective.ch/?view=0A4E8E8...,gsm,40016150,False,2015-07-07 23:54:44+02:00,['65000028'],"['11001061', '11000819']",['BE'],NaN
3,3ab8537e-df86-4447-84ea-e2fe66181389,analyste d'affaires (h/f),Eidgenössisches Justiz- und Polizeidepartement...,Kleinunternehmen,CH-3003 Bern,19.08.2016|Secrétariat d'Etat aux migrations S...,2016-08-19 08:32:40+02:00,https://direktlink.prospective.ch/?view=4983E7...,transformer,40016150,False,2016-08-20 19:19:51+02:00,['65000028'],['11000155'],['BE'],f38329cf-ec30-4622-af94-56c57d854e79
4,69eb4346-50d7-4525-afad-496602c3a611,Data Scientist,Ivoclar Vivadent AG,Grossunternehmen,LI-9494 Schaan,Inspiriert zum Lächeln\n\nMit hochwertigen Erz...,2016-10-07 12:07:20+02:00,https://recruitingapp-2652.umantis.com/Vacanci...,"ai, data scientist, deep learning(flexible), p...",40000487,False,2016-12-20 18:02:04+01:00,['65000006'],['11000879'],['LI'],8de8a8d7-2da5-4ff5-856e-d3c99f63d8de
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,375739d6-ba39-4fe9-aca7-27d0573f0f67,Data Scientist (w/m/d),Bison Schweiz AG,Mittelunternehmen,6210 Sursee,DAS MACHST DU\n\nAnalyse und Interpretation gr...,2025-06-05 08:58:12.793000+02:00,https://www.jobs.ch/de/stellenangebote/detail/...,"ai, ki, machine learning(flexible), rag, verte...",40003232,False,2025-06-26 17:32:18.062000+02:00,['65000019'],['11000879'],['LU'],375739d6-ba39-4fe9-aca7-27d0573f0f67
196,afc23f17-b791-4ecf-be0b-b2dded89b165,Data Engineer,Bison Schweiz AG,Mittelunternehmen,6210 Sursee,"Du brennst für Daten, denkst in Lösungen und w...",2025-06-05 14:30:47.126000+02:00,https://www.jobup.ch/fr/emplois/detail/7feca6a...,"ki, machine learning",40003232,False,2025-06-14 06:36:08.821000+02:00,['65000019'],['11000881'],['LU'],afc23f17-b791-4ecf-be0b-b2dded89b165
197,58eee979-6c0d-4025-bd6a-36625dbccac0,Senior Fullstack Development im sicherheitsrel...,Innovation Process Technology AG,Kleinunternehmen,Deutschschweiz,Senior Full Stack Development im sicherheitsre...,2025-06-12 18:58:37.654000+02:00,https://ipt.ch/de/karriere/jobs/senior-full-st...,kafka,40003413,False,NaN,['65000019'],['11001045'],"['AI', 'OW', 'LU', 'GL', 'AR', 'TG', 'BS', 'BL...",58eee979-6c0d-4025-bd6a-36625dbccac0
198,b2782410-be36-4c57-92cc-fc8f4a5cba08,Fullstack Development im sicherheitsrelevanten...,Innovation Process Technology AG,Kleinunternehmen,Deutschschweiz,Fullstack Development im sicherheitsrelevanten...,2025-06-12 18:58:37.658000+02:00,https://ipt.ch/de/karriere/jobs/full-stack-dev...,kafka,40003413,False,NaN,['65000019'],['11001045'],"['GL', 'SH', 'LU', 'OW', 'TG', 'AI', 'NW', 'SG...",b2782410-be36-4c57-92cc-fc8f4a5cba08
199,42b4d243-c7c2-4a33-b202-3f75a30d7da0,Hochschulpraktikant/-in Kriminalanalyse und Kü...,Eidgenössisches Justiz- und Polizeidepartement...,Kleinunternehmen,Bern,Aufgaben\n\nIhr Team bei der Implementierung u...,2025-06-17 01:26:49.929000+02:00,https://jobs.admin.ch/offene-stellen/hochschul...,ki,40016150,False,2025-07-03 13:33:14.308000+02:00,['65000028'],[],['BE'],42b4d243-c7c2-4a33-b202-3f75a30d7da0

In [6]:
import pandas as pd
df_dedup = pd.read_csv('/Users/bradyallardice/Downloads/ai_jobs_from_1000_random_companies-4.csv')
df_dedup

,uid,title,company_name,company_size,location_raw,content_clean,tst_created,url,matched_keywords,company_id,company_is_recruiter,tst_deleted,x28_industries,x28_occupations,cantons,duplicate_group
0,surr_5ba965139b305ba74f1859e6c51d32e9b0f03110,Leiter/in Personaladministration / Personalber...,Bundesverwaltungsgericht (BVGer),Kleinunternehmen,CH-3000 Bern,Leiter/in Personaladministration / Personalber...,2012-01-05 19:06:49.871000+01:00,http://www.bvger.ch/stellen/00572/index.html?l...,ai(punct),40014160,False,2012-03-29 08:41:35.052000+02:00,['65000028'],"['11001447', '11002040']",['BE'],975aa774-83e2-4c3e-aa7b-3020a7fe43c6
1,surr_f7ec8e0940a5b723c7a521c66389d829aef1922a,Mitarbeiter/in Document Management Center (DMC...,Eidgenössische Steuerverwaltung (ESTV),Mittelunternehmen,Bern,Mitarbeiter/in Document Management Center (DMC...,2012-01-11 20:48:28.211000+01:00,http://direktlink.prospective.ch/?view=CBFB3BF...,ai(punct),40015597,False,2012-01-23 18:13:33.670000+01:00,['65000028'],['11000894'],['BE'],742b8358-37ff-4c87-988c-4e7e64b0a3e3
2,surr_2395a8c29362db19891f1123a6b5f25d2c14e616,Mitarbeiter/in Document Management Center (DMC...,Eidgenössische Steuerverwaltung (ESTV),Mittelunternehmen,Bern,Mitarbeiter/in Document Management Center (DMC...,2012-01-11 20:48:32.383000+01:00,http://direktlink.prospective.ch/?view=CC2BBF8...,ai(punct),40015597,False,2012-01-23 18:13:33.690000+01:00,['65000028'],['11000894'],['BE'],0259f975-f3b2-41a1-92a5-0aebfa146f93
3,surr_d2d14c9e39280fb8ec4657ea8084e428727cd4d6,Mitarbeiter/in Document Management Center (DMC...,Eidgenössische Steuerverwaltung (ESTV),Mittelunternehmen,Bern,Mitarbeiter/in Document Management Center (DMC...,2012-01-11 20:48:36.284000+01:00,http://direktlink.prospective.ch/?view=CC542F1...,ai(punct),40015597,False,2012-01-23 18:13:36.677000+01:00,['65000028'],['11000894'],['BE'],306be782-ee05-4eb5-8b0b-38b71a35361c
4,surr_6c3d5d6d046c06628864daaef6eb271b9b60fa70,Research Scientist in Analytical Chemistry,Nestlé Suisse S.A.,Grossunternehmen,Aargau|Bern|Fribourg|Schaffhaussen|St. Gallen|...,Research Scientist in Analytical Chemistry\n%2...,2012-01-13 15:39:09.445000+01:00,https://nestle.taleo.net/careersection/3/jobde...,research scientist,40003804,False,2012-03-09 09:18:34.939000+01:00,['65000021'],['11000303'],"['BE', 'SG', 'ZH', 'FR', 'VD', 'ZG']",6cc97ae4-bd42-40ca-9377-52b74cdc2e73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6768,surr_593366a4ae226e2e6b77d6c1a9992a518af582c2,Enterprise IT Architect 80 - 100% (w/m/d),LGT Capital Partners AG,Kleinunternehmen,8002 Zürich,Seite teilen Diesen Artikel teilen\n\nlinkedin...,2025-06-27 14:57:29.810000+02:00,https://www.lgt.com/global-de/karriere/jobs/en...,"ki, ml",40078183,False,2025-07-31 00:01:13.214000+02:00,['65000011'],['11000975'],['ZH'],8fa59e9d-07a6-4365-92a9-000393026f07
6769,surr_15b03761ec5d7430a7eb6d9e92f9c7daa1575e3b,Private Equity Fund Counsel,LGT Capital Partners AG,Kleinunternehmen,Pfäffikon,Job Description\n\nSet-up of investment funds ...,2025-06-27 18:23:58.258000+02:00,https://lgtcp.wd3.myworkdayjobs.com/lgtcpcurre...,llm,40078183,False,NaN,['65000011'],NaN,"['SZ', 'ZH']",b5867927-d421-4c1d-a993-a8385a35696e
6770,surr_cbc34e3ffa3df81336e2ee9b116907e0aa2f4d57,Un-e assistant-e administratif/ive à 80%,Université de Genève,Mittelunternehmen,CH-1204 Genève,Un-e assistant-e administratif/ive à 80%\npour...,2025-06-30 00:54:36.895000+02:00,https://jobs.unige.ch/www/wd_portal.show_job?p...,aa,40000018,False,2025-07-13 01:59:23.690000+02:00,"['65000003', '65000012']",['11000002'],['GE'],bbedf7cb-1d3e-47b4-9af6-e523c998483a
6771,surr_20ab9d5dfd9d2ca423b9d5ccb767f823d8b3147e,RESPONSABILE SERVICE CENTER & BACK-OFFICE SUD ...,ELCOTHERM AG,Mittelunternehmen,"Bedano, CH, 6930",RESPONSABILE SERVICE CENTER & BACK-OFFICE SUD ...,2025-06-30 12:51:46.302000+02:00,https://careers.aristongroup.com/job/Maerstett...,ai,40003315,False,2025-07-17 17:31:02.908000+02:00,"['65000002', '65000024']",['11000009'],['TI'],32702599-8a9e-41e4-b0a8-e53b57f43a85
6772,surr_37a293ee61c7b41c83e3677185ce000116715715,Sachbearbeiter/in (50%),Haus für Mutter und Kind,Kleinunternehmen,8477 Oberstammheim (ZH),Das „Haus für Mutter und Kind“ in Oberstammhei...,2025-06-30 15:06:06.798000+02:00,https://www.spitalstellenmarkt.ch/job/sachbear...,ai(punct),40114193,False,2025-07-17 20:46:26.949000+02:00,['65000033'],['11002219'],['ZH'],29683975-f5c1-4e70-aed9-9bd56072f339